export const INORGANIC_CHEM_SKILLS = [
    {
        id: 'skill-1',
        title: 'Atomic Structure Calculations',
        desc: 'Given symbol and mass number, calculate protons, neutrons, electrons, and identify isotopes.',
        color: '#10b981',
        icon: '⚛️',
        learnSections: [
            {
                heading: 'Sub-atomic Particles',
                content: 'Every atom is made of three fundamental particles:\n• Proton (p): positive charge (+1), mass ≈ 1 u. Found in the nucleus. Number = Atomic Number Z.\n• Neutron (n): no charge (0), mass ≈ 1 u. Found in the nucleus. Count = A − Z.\n• Electron (e⁻): negative charge (−1), mass ≈ 0. Orbits the nucleus in shells.\n\nIn a neutral atom:\n• Protons = Electrons = Z\n• Mass Number A = Protons + Neutrons',
                example: 'For Chlorine-35 (Z=17, A=35): Protons = 17, Neutrons = 35 − 17 = 18, Electrons = 17.',
                keyLabel: 'key-fact'
            },
            {
                heading: 'Isotopes, Isobars & Ions',
                content: 'Special atomic species:\n• Isotopes: Same Z, different A (same element, different neutron count). Example: ¹H, ²H, ³H.\n• Isobars: Different Z, same A (different elements, same mass). Example: ¹⁴C (Z=6) and ¹⁴N (Z=7).\n• Cation (positive ion): Atom LOSES electrons. Na → Na⁺ (loses 1e⁻). Electrons = Z − charge.\n• Anion (negative ion): Atom GAINS electrons. Cl → Cl⁻ (gains 1e⁻). Electrons = Z + charge.',
                example: 'Cl⁻ ion: Z = 17, gains 1 electron → Electrons = 17 + 1 = 18. Still has 17 protons.',
                keyLabel: 'neet-note'
            }
        ],
        practice: [
            { type: 'mcq', difficulty: 'Basic', question: 'How many neutrons are in a Carbon-12 atom (Z = 6, A = 12)?', options: ['6', '12', '18', '0'], answer: 0, explanation: 'n = A − Z = 12 − 6 = 6 neutrons.' },
            { type: 'mcq', difficulty: 'Basic', question: 'How many protons does Sodium (Na, Z = 11) have?', options: ['11', '12', '23', '22'], answer: 0, explanation: 'Protons = Z = 11 for any sodium atom.' },
            { type: 'mcq', difficulty: 'Basic', question: 'The atomic number of Oxygen is 8 and its mass number is 16. How many electrons does a neutral O atom have?', options: ['8', '16', '24', '4'], answer: 0, explanation: 'For a neutral atom, electrons = protons = Z = 8.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Chlorine-35 has Z = 17 and A = 35. How many neutrons does it have?', options: ['17', '18', '35', '52'], answer: 1, explanation: 'n = A − Z = 35 − 17 = 18 neutrons.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Na⁺ ion has Z = 11. How many electrons does it have?', options: ['11', '10', '12', '23'], answer: 1, explanation: 'Na loses 1 electron to form Na⁺. Electrons = 11 − 1 = 10.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Cl⁻ ion has Z = 17. How many electrons does it have?', options: ['17', '16', '18', '35'], answer: 2, explanation: 'Cl gains 1 electron to form Cl⁻. Electrons = 17 + 1 = 18.' },
            { type: 'mcq', difficulty: 'Basic', question: '¹²C and ¹⁴C are:',  options: ['Isobars', 'Isotopes', 'Isoelectronic', 'Isotones'], answer: 1, explanation: 'Both have Z = 6 (carbon) but different mass numbers (12 and 14). Same Z, different A = isotopes.' },
            { type: 'mcq', difficulty: 'Intermediate', question: '¹⁴C (Z=6) and ¹⁴N (Z=7) are:', options: ['Isotopes', 'Isobars', 'Isotones', 'Isoelectronic'], answer: 1, explanation: 'Different Z (6 vs 7) but same A (14). Different elements, same mass = isobars.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Potassium (K) has Z = 19 and A = 39. Its neutron count is:', options: ['19', '20', '39', '58'], answer: 1, explanation: 'n = A − Z = 39 − 19 = 20 neutrons.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which particle determines the element\'s identity?', options: ['Neutron', 'Electron', 'Proton', 'Nucleus'], answer: 2, explanation: 'The number of protons (atomic number Z) uniquely identifies every element. Two atoms with the same Z are always the same element.' },
            { type: 'mcq', difficulty: 'Basic', question: 'How many electrons does a neutral Calcium (Ca, Z=20) atom have?', options: ['20', '40', '18', '22'], answer: 0, explanation: 'For a neutral atom, electrons = protons = Z = 20.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Oxygen-16 has Z=8 and A=16. How many neutrons does it have?', options: ['8', '16', '4', '24'], answer: 0, explanation: 'n = A − Z = 16 − 8 = 8 neutrons. Oxygen-16 has equal protons and neutrons.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Aluminium (Al) has Z=13. How many protons does it have?', options: ['27', '14', '13', '3'], answer: 2, explanation: 'Protons = Atomic Number Z = 13. Aluminium always has 13 protons.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'F⁻ ion has Z=9. How many electrons does it have?', options: ['9', '8', '10', '18'], answer: 2, explanation: 'Fluorine gains 1 electron to form F⁻. Electrons = 9 + 1 = 10. F⁻ has the same electronic configuration as Ne (Z=10).' },
            { type: 'mcq', difficulty: 'Basic', question: 'Potassium-40 has Z=19 and A=40. Its neutron count is:', options: ['19', '21', '40', '59'], answer: 1, explanation: 'n = A − Z = 40 − 19 = 21 neutrons.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Phosphorus-31 has Z=15 and A=31. How many neutrons does it have?', options: ['15', '16', '31', '46'], answer: 1, explanation: 'n = A − Z = 31 − 15 = 16 neutrons.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Fe³⁺ ion has Z=26. How many electrons does it have?', options: ['29', '23', '26', '56'], answer: 1, explanation: 'Fe³⁺ loses 3 electrons. Electrons = 26 − 3 = 23.' },
            { type: 'mcq', difficulty: 'Basic', question: '²³⁵U and ²³⁸U both have Z=92. They are:', options: ['Isobars', 'Isotones', 'Isotopes', 'Isoelectronic'], answer: 2, explanation: 'Same Z (92, uranium) but different A (235 and 238) → isotopes.' },
            { type: 'mcq', difficulty: 'Basic', question: 'A neutral atom has Z=11. How many electrons does it have?', options: ['10', '12', '11', '23'], answer: 2, explanation: 'In a neutral atom, electrons = protons = Z. For Z=11 (sodium): 11 protons = 11 electrons.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Helium-4 (Z=2, A=4) has how many neutrons?', options: ['2', '4', '1', '6'], answer: 0, explanation: 'n = A − Z = 4 − 2 = 2 neutrons. Helium-4 has 2 protons and 2 neutrons in its nucleus.' },
        ],
        assess: [
            { type: 'mcq', difficulty: 'Basic', question: 'How many neutrons are in Nitrogen-14 (Z = 7, A = 14)?', options: ['7', '14', '21', '0'], answer: 0, explanation: 'n = A − Z = 14 − 7 = 7 neutrons.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Magnesium (Mg) has Z = 12. How many electrons does a neutral Mg atom have?', options: ['12', '24', '6', '18'], answer: 0, explanation: 'Neutral atom: electrons = Z = 12.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Iron-56 has Z = 26 and A = 56. Its neutron count is:', options: ['26', '30', '56', '82'], answer: 1, explanation: 'n = A − Z = 56 − 26 = 30 neutrons.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Mg²⁺ ion has Z = 12. How many electrons does it have?', options: ['12', '10', '14', '24'], answer: 1, explanation: 'Mg²⁺ loses 2 electrons. Electrons = 12 − 2 = 10.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'O²⁻ ion has Z = 8. How many electrons does it have?', options: ['8', '6', '10', '16'], answer: 2, explanation: 'O²⁻ gains 2 electrons. Electrons = 8 + 2 = 10.' },
            { type: 'mcq', difficulty: 'Basic', question: '¹⁶O and ¹⁸O (both Z = 8) are:', options: ['Isobars', 'Isotopes', 'Isoelectronic', 'Isoneutrons'], answer: 1, explanation: 'Same Z (8), different A (16 vs 18). Same element, different mass = isotopes.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which quantity equals Z + n?', options: ['Atomic Number', 'Electron count', 'Mass Number', 'Valency'], answer: 2, explanation: 'A = Z + n (protons + neutrons = mass number).' },
            { type: 'mcq', difficulty: 'Basic', question: 'Calcium (Ca) has Z = 20 and A = 40. Its neutron count is:', options: ['20', '40', '60', '10'], answer: 0, explanation: 'n = A − Z = 40 − 20 = 20 neutrons. Ca has equal protons and neutrons.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'An ion has 11 protons and 10 electrons. It is:', options: ['Na⁻', 'Na⁺', 'Mg²⁺', 'F⁻'], answer: 1, explanation: 'Z = 11 is Sodium. Protons (11) > Electrons (10) → positive ion. Lost 1e⁻ → Na⁺.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'An atom has 17 protons and 18 neutrons. Its mass number is:', options: ['17', '18', '35', '1'], answer: 2, explanation: 'A = protons + neutrons = 17 + 18 = 35. This is Chlorine-35.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Carbon-14 (Z=6, A=14) has how many neutrons?', options: ['6', '8', '14', '20'], answer: 1, explanation: 'n = A − Z = 14 − 6 = 8 neutrons. ¹⁴C has 2 more neutrons than ¹²C — used in radiocarbon dating.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Ca²⁺ ion has Z=20. How many electrons does it have?', options: ['20', '22', '18', '40'], answer: 2, explanation: 'Ca²⁺ loses 2 electrons. Electrons = 20 − 2 = 18. Ca²⁺ has the same configuration as Argon (Z=18).' },
            { type: 'mcq', difficulty: 'Basic', question: 'Sulfur-32 (Z=16, A=32) has how many neutrons?', options: ['16', '32', '48', '8'], answer: 0, explanation: 'n = A − Z = 32 − 16 = 16 neutrons. Sulfur-32 has equal protons and neutrons.' },
            { type: 'mcq', difficulty: 'Intermediate', question: '⁴⁰Ar (Z=18) and ⁴⁰Ca (Z=20) both have A=40. They are:', options: ['Isotopes', 'Isobars', 'Isotones', 'Isoelectronic'], answer: 1, explanation: 'Different Z (18 vs 20) but same A (40) → isobars. Different elements, same mass number.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Al³⁺ ion has Z=13. How many electrons does it have?', options: ['13', '16', '10', '3'], answer: 2, explanation: 'Al³⁺ loses 3 electrons. Electrons = 13 − 3 = 10. Al³⁺ has the same electron count as Ne (Z=10).' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'N³⁻ ion has Z=7. How many electrons does it have?', options: ['7', '4', '10', '14'], answer: 2, explanation: 'Nitrogen gains 3 electrons to form N³⁻. Electrons = 7 + 3 = 10.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Silicon-28 (Z=14, A=28) has how many neutrons?', options: ['14', '28', '12', '42'], answer: 0, explanation: 'n = A − Z = 28 − 14 = 14 neutrons. Silicon-28 has equal protons and neutrons.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'An ion has 12 protons and 10 electrons. It is:', options: ['Na⁺', 'Mg²⁺', 'Al³⁺', 'Ca²⁺'], answer: 1, explanation: 'Z=12 is Magnesium. Protons(12) > Electrons(10) → positive ion. Lost 2 electrons → Mg²⁺.' },
            { type: 'mcq', difficulty: 'Intermediate', question: '²H (deuterium) and ³H (tritium) both have Z=1. They are:', options: ['Isobars', 'Isotopes', 'Isoelectronic', 'Isoneutrons'], answer: 1, explanation: 'Same Z (1, hydrogen) but different A (2 and 3) → isotopes. ¹H, ²H, and ³H are the three isotopes of hydrogen.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Copper-64 (Z=29, A=64) has how many neutrons?', options: ['29', '64', '35', '93'], answer: 2, explanation: 'n = A − Z = 64 − 29 = 35 neutrons.' },
        ]
    },
    {
        id: 'skill-2',
        title: 'Electronic Configuration',
        desc: 'Fill electrons into K, L, M, N shells using 2n². Identify valency from outermost shell.',
        color: '#0d9488',
        icon: '🔧',
        learnSections: [
            {
                heading: 'Electron Shell Filling',
                content: 'Electrons fill shells starting from the innermost (lowest energy) outward:\n• K-shell (n=1): max 2 electrons\n• L-shell (n=2): max 8 electrons\n• M-shell (n=3): max 18 electrons\n• N-shell (n=4): max 32 electrons\n\nRule: Max electrons in shell n = 2n²\nFilling rule: Never exceed the maximum for each shell. Fill innermost first.',
                example: 'Sodium (Z=11): K=2, L=8, M=1. Outer shell has 1 electron → valency = 1.',
                keyLabel: 'key-fact',
                table: {
                    headers: ['Element', 'Z', 'K (max 2)', 'L (max 8)', 'M (max 18)', 'Valency'],
                    rows: [
                        ['Hydrogen (H)', '1', '1', '—', '—', '1'],
                        ['Carbon (C)', '6', '2', '4', '—', '4'],
                        ['Nitrogen (N)', '7', '2', '5', '—', '3'],
                        ['Oxygen (O)', '8', '2', '6', '—', '2'],
                        ['Sodium (Na)', '11', '2', '8', '1', '1'],
                        ['Chlorine (Cl)', '17', '2', '8', '7', '1'],
                        ['Calcium (Ca)', '20', '2', '8', '8, 2', '2'],
                    ]
                }
            },
            {
                heading: 'Valency from Electronic Configuration',
                content: 'Valency is the number of electrons in the outermost (valence) shell:\n• If outer electrons ≤ 4: valency = number of outer electrons\n• If outer electrons > 4: valency = 8 − outer electrons\n\nThis is because atoms can GAIN electrons to complete the octet instead of losing many.',
                example: 'Chlorine has 7 outer electrons. Valency = 8 − 7 = 1 (easier to gain 1 than lose 7).',
                keyLabel: 'neet-note'
            }
        ],
        practice: [
            { type: 'mcq', difficulty: 'Basic', question: 'What is the electronic configuration of Carbon (Z = 6)?', options: ['K=2, L=2, M=2', 'K=2, L=4', 'K=6', 'K=2, L=2, M=1, N=1'], answer: 1, explanation: 'Z=6: fill K=2 first, then remaining 4 in L. Configuration: K=2, L=4.' },
            { type: 'mcq', difficulty: 'Basic', question: 'What is the maximum number of electrons in the L-shell?', options: ['2', '8', '18', '32'], answer: 1, explanation: 'L-shell: n=2. Max = 2n² = 2×4 = 8 electrons.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Sodium (Z=11) has the configuration K=2, L=8, M=1. What is its valency?', options: ['1', '2', '3', '4'], answer: 0, explanation: 'Valency = outer shell electrons = 1 (M-shell has 1). Na easily loses this 1 electron.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Oxygen (Z=8) has configuration K=2, L=6. What is its valency?', options: ['6', '2', '4', '8'], answer: 1, explanation: 'Outer electrons = 6. Valency = 8 − 6 = 2 (gains 2 electrons to complete octet).' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'What is the electronic configuration of Chlorine (Z = 17)?', options: ['K=2, L=8, M=7', 'K=2, L=7, M=8', 'K=2, L=8, M=8', 'K=8, L=8, M=1'], answer: 0, explanation: 'Z=17: K=2, L=8, M=7 (2+8+7=17). M-shell fills next after L is full.' },
            { type: 'mcq', difficulty: 'Basic', question: 'How many electrons does the K-shell hold at maximum?', options: ['1', '2', '8', '18'], answer: 1, explanation: 'K-shell: n=1. Max = 2n² = 2×1 = 2 electrons.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Calcium (Z=20) has configuration K=2, L=8, M=8, N=2. Its valency is:', options: ['2', '8', '4', '1'], answer: 0, explanation: 'Outer shell (N) has 2 electrons. Valency = 2. Ca easily loses 2 electrons.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which element has the configuration K=2, L=8, M=3 (Z=13)?', options: ['Nitrogen', 'Aluminium', 'Phosphorus', 'Silicon'], answer: 1, explanation: 'Z=13 is Aluminium (Al). Configuration: K=2, L=8, M=3.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Nitrogen (Z=7) has configuration K=2, L=5. Its valency is:', options: ['5', '3', '2', '7'], answer: 1, explanation: 'Outer electrons = 5. Valency = 8 − 5 = 3 (gains 3 electrons to complete octet). NH₃ shows this.' },
            { type: 'mcq', difficulty: 'Basic', question: 'What is the maximum number of electrons in the M-shell?', options: ['8', '18', '32', '2'], answer: 1, explanation: 'M-shell: n=3. Max = 2n² = 2×9 = 18 electrons.' },
            { type: 'mcq', difficulty: 'Basic', question: 'What is the electronic configuration of Oxygen (Z=8)?', options: ['K=2, L=6', 'K=2, L=4, M=2', 'K=8', 'K=2, L=2, M=4'], answer: 0, explanation: 'Z=8: K fills first with 2, then 6 remaining go into L. Configuration: K=2, L=6.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'What is the electronic configuration of Sulphur (Z=16)?', options: ['K=2, L=6, M=8', 'K=2, L=8, M=6', 'K=2, L=6, M=6, N=2', 'K=16'], answer: 1, explanation: 'Z=16: K=2, L=8, M=6 (2+8+6=16). After filling K and L fully, the remaining 6 go into M.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which element has configuration K=2, L=8, M=8, N=1 (Z=19)?', options: ['Calcium (Ca)', 'Potassium (K)', 'Argon (Ar)', 'Sodium (Na)'], answer: 1, explanation: 'K=2+L=8+M=8+N=1=19. Z=19 is Potassium (K). Its outer N-shell has 1 electron → valency = 1.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Potassium (Z=19) configuration is K=2, L=8, M=8, N=1. Its valency is:', options: ['8', '1', '2', '4'], answer: 1, explanation: 'Outer shell (N) has 1 electron → valency = 1. K easily loses this 1 electron to form K⁺.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which element has configuration K=2, L=8, M=8 (Z=18)?', options: ['Chlorine (Cl)', 'Calcium (Ca)', 'Argon (Ar)', 'Sulfur (S)'], answer: 2, explanation: 'K=2+L=8+M=8 = 18. Z=18 is Argon (Ar), a noble gas with complete outer shell. Valency = 0.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Helium (Z=2) has configuration K=2. Why is its valency 0?', options: ['It has too many electrons', 'K-shell is full with 2 electrons (duplet rule for H and He)', 'Helium has no electrons', 'Helium is a metal'], answer: 1, explanation: 'Hydrogen and helium follow the duplet rule (stable with 2 electrons). He has K=2, which is full — no bonding needed. Valency = 0.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Iron (Z=26) has configuration K=2, L=8, M=14, N=2. Its outermost shell has how many electrons?', options: ['14', '2', '8', '26'], answer: 1, explanation: 'The outermost shell is N with 2 electrons. Valency of iron = 2 (it can also show valency 3 as a transition metal).' },
            { type: 'mcq', difficulty: 'Basic', question: 'How many total electrons can the first THREE shells (K+L+M) hold at maximum?', options: ['18', '28', '32', '20'], answer: 1, explanation: 'K=2, L=8, M=18. Total = 2+8+18 = 28 electrons maximum in the first 3 shells.' },
            { type: 'mcq', difficulty: 'Basic', question: 'The formula 2n² gives maximum electrons in a shell. For the N-shell (n=4):', options: ['8', '18', '32', '2'], answer: 2, explanation: '2n² = 2×4² = 2×16 = 32. The N-shell can hold a maximum of 32 electrons.' },
        ],
        assess: [
            { type: 'mcq', difficulty: 'Basic', question: 'What is the electronic configuration of Phosphorus (Z = 15)?', options: ['K=2, L=8, M=5', 'K=2, L=5, M=8', 'K=5, L=8, M=2', 'K=2, L=8, M=4, N=1'], answer: 0, explanation: 'Z=15: K=2, L=8, M=5 (2+8+5=15).' },
            { type: 'mcq', difficulty: 'Basic', question: 'Maximum electrons in N-shell (n=4)?', options: ['8', '18', '32', '2'], answer: 2, explanation: 'N-shell: n=4. Max = 2n² = 2×16 = 32 electrons.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Magnesium (Z=12) has configuration K=2, L=8, M=2. Its valency is:', options: ['2', '8', '4', '6'], answer: 0, explanation: 'Outer shell (M) has 2 electrons. Valency = 2. Mg loses 2 electrons in bonding.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Which element has electronic configuration K=2, L=8, M=6?', options: ['Oxygen', 'Sulfur (Z=16)', 'Chlorine', 'Argon'], answer: 1, explanation: 'K=2 + L=8 + M=6 = 16. Z=16 is Sulfur (S).' },
            { type: 'mcq', difficulty: 'Basic', question: 'The formula 2n² gives the maximum electrons in a shell. For n=2, this gives:', options: ['4', '8', '12', '2'], answer: 1, explanation: '2n² = 2 × 2² = 2 × 4 = 8 electrons maximum in L-shell.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Fluorine (Z=9) has configuration K=2, L=7. Its valency is:', options: ['7', '1', '2', '9'], answer: 1, explanation: 'Outer electrons = 7. Valency = 8 − 7 = 1. F gains 1 electron to complete its octet.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Silicon (Z=14) has configuration K=2, L=8, M=4. Its valency is:', options: ['2', '4', '6', '8'], answer: 1, explanation: 'Outer electrons = 4. Since outer electrons = 4, valency = 4 (exactly half an octet).' },
            { type: 'mcq', difficulty: 'Basic', question: 'After filling K=2 and L=8, the next 10 electrons go into:', options: ['Another L-shell', 'N-shell', 'M-shell', 'O-shell'], answer: 2, explanation: 'Electrons fill shells in order: K → L → M → N. After L is full, the 11th electron enters M-shell.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Argon (Z=18) has configuration K=2, L=8, M=8. Its valency is:', options: ['0', '8', '2', '6'], answer: 0, explanation: 'Noble gases have 8 electrons in outer shell (complete octet). They don\'t bond — valency = 0.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Which has 2 electrons in its outermost shell — Magnesium (Z=12) or Calcium (Z=20)?', options: ['Only Magnesium', 'Only Calcium', 'Both', 'Neither'], answer: 2, explanation: 'Mg: K=2,L=8,M=2 → outer=2. Ca: K=2,L=8,M=8,N=2 → outer=2. Both have 2 outer electrons and valency 2.' },
            { type: 'mcq', difficulty: 'Basic', question: 'What is the electronic configuration of Neon (Z=10)?', options: ['K=2, L=8', 'K=10', 'K=2, L=6, M=2', 'K=2, L=4, M=4'], answer: 0, explanation: 'Z=10: K=2, L=8 (2+8=10). Neon has a complete L-shell → noble gas with valency 0.' },
            { type: 'mcq', difficulty: 'Basic', question: 'What is the electronic configuration of Magnesium (Z=12)?', options: ['K=2, L=10', 'K=2, L=8, M=2', 'K=2, L=4, M=6', 'K=12'], answer: 1, explanation: 'Z=12: K=2, L=8, M=2 (2+8+2=12). Outer M-shell has 2 electrons → valency = 2.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'An element has Z=17. Its valency is:', options: ['7', '1', '3', '17'], answer: 1, explanation: 'Z=17 is Chlorine: K=2, L=8, M=7. Outer electrons=7. Valency = 8−7 = 1 (gains 1 electron to complete octet).' },
            { type: 'mcq', difficulty: 'Basic', question: 'Lithium (Z=3) has configuration K=2, L=1. Its valency is:', options: ['2', '1', '3', '0'], answer: 1, explanation: 'Outer shell (L) has 1 electron → valency = 1. Li easily loses this 1 electron to form Li⁺.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Which pair of elements have the SAME valency?', options: ['Na (Z=11) and Mg (Z=12)', 'Na (Z=11) and K (Z=19)', 'Na (Z=11) and Cl (Z=17)', 'O (Z=8) and C (Z=6)'], answer: 1, explanation: 'Na: K=2,L=8,M=1 → valency 1. K: K=2,L=8,M=8,N=1 → valency 1. Both have 1 outer electron.' },
            { type: 'mcq', difficulty: 'Basic', question: 'What is the electronic configuration of Fluorine (Z=9)?', options: ['K=2, L=7', 'K=2, L=6, M=1', 'K=9', 'K=2, L=5, M=2'], answer: 0, explanation: 'Z=9: K=2, L=7 (2+7=9). Outer L-shell has 7 electrons → valency = 8−7 = 1.' },
            { type: 'mcq', difficulty: 'Basic', question: 'The Octet Rule states atoms tend to have _____ electrons in their outermost shell when bonding:', options: ['2', '4', '6', '8'], answer: 3, explanation: 'The Octet Rule: atoms tend to gain, lose, or share electrons to achieve 8 electrons in the outer shell. H and He are exceptions (duplet: 2).' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'An element has K=2, L=8, M=5. Its valency is:', options: ['5', '3', '8', '2'], answer: 1, explanation: 'Outer electrons = 5. Valency = 8−5 = 3 (gains 3 electrons to complete octet). This is Phosphorus (Z=15).' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Why do noble gases (He, Ne, Ar) have valency 0?', options: ['They are gases', 'Their outer shells are completely filled — no electrons to gain or lose', 'They have no electrons', 'They have high atomic mass'], answer: 1, explanation: 'Noble gases have complete outer electron shells (He: 2, others: 8 electrons). A complete shell is stable — no tendency to gain, lose, or share electrons. Valency = 0.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Beryllium (Z=4) has configuration K=2, L=2. Its valency is:', options: ['2', '4', '6', '1'], answer: 0, explanation: 'Outer shell (L) has 2 electrons. Valency = 2. Be loses 2 electrons to form Be²⁺.' },
        ]
    },
    {
        id: 'skill-3',
        title: 'Ionic vs Covalent Bonds',
        desc: 'Identify whether a compound has ionic (electron transfer) or covalent (electron sharing) bonding.',
        color: '#0891b2',
        icon: '🔗',
        learnSections: [
            {
                heading: 'Ionic Bonds — Electron Transfer',
                content: 'Ionic bonds form when a metal atom transfers electrons to a non-metal atom:\n• Metal loses electrons → forms cation (positive ion)\n• Non-metal gains electrons → forms anion (negative ion)\n• Opposite charges attract → ionic bond\n\nRule: Metal + Non-metal compound = Ionic\nExamples: NaCl, KBr, MgO, CaCl₂, KCl, LiF',
                example: 'NaCl: Na (metal, Z=11) transfers 1e⁻ to Cl (non-metal, Z=17). Na⁺ + Cl⁻ → held by electrostatic attraction.',
                keyLabel: 'key-fact'
            },
            {
                heading: 'Covalent Bonds — Electron Sharing',
                content: 'Covalent bonds form when two non-metal atoms share electron pairs:\n• Single bond: 1 shared pair (e.g. H–H, H–Cl)\n• Double bond: 2 shared pairs (e.g. O=O, C=O)\n• Triple bond: 3 shared pairs (e.g. N≡N)\n\nRule: Non-metal + Non-metal compound = Covalent\nExamples: H₂, O₂, N₂, H₂O, CO₂, CH₄, HCl, NH₃',
                example: 'H₂O: O (non-metal) shares 2 electron pairs with 2 H atoms. Both atoms benefit from a complete outer shell.',
                keyLabel: 'neet-note'
            }
        ],
        practice: [
            { type: 'mcq', difficulty: 'Basic', question: 'NaCl (table salt) is formed by Na giving 1 electron to Cl. The bond type is:', options: ['Covalent', 'Ionic', 'Metallic', 'Hydrogen'], answer: 1, explanation: 'Na (metal) transfers an electron to Cl (non-metal) → ionic bond. Na⁺Cl⁻.' },
            { type: 'mcq', difficulty: 'Basic', question: 'H₂O has oxygen sharing electron pairs with hydrogen. The bond type is:', options: ['Ionic', 'Metallic', 'Covalent', 'None'], answer: 2, explanation: 'O (non-metal) and H (non-metal) share electrons → covalent bond.' },
            { type: 'mcq', difficulty: 'Basic', question: 'CO₂ contains carbon sharing electron pairs with oxygen. The bond type is:', options: ['Ionic', 'Covalent', 'Metallic', 'Coordinate'], answer: 1, explanation: 'Non-metal (C) + Non-metal (O) sharing electrons = covalent. CO₂ has two C=O double bonds.' },
            { type: 'mcq', difficulty: 'Basic', question: 'KCl (potassium chloride) bond type is:', options: ['Covalent', 'Ionic', 'Metallic', 'Coordinate'], answer: 1, explanation: 'K is a metal, Cl is a non-metal. Metal + non-metal = ionic bond.' },
            { type: 'mcq', difficulty: 'Basic', question: 'NH₃ (ammonia) — nitrogen and hydrogen are both non-metals. Bond type is:', options: ['Ionic', 'Covalent', 'Metallic', 'Van der Waals'], answer: 1, explanation: 'N + H = non-metal + non-metal → covalent bond. N shares 3 pairs with 3 H atoms.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'MgCl₂ — magnesium chloride. Identify the bond type.', options: ['Covalent', 'Ionic', 'Both', 'Neither'], answer: 1, explanation: 'Mg is a metal, Cl is a non-metal. Metal + non-metal = ionic. Mg gives 2e⁻ to form Mg²⁺ and 2 Cl⁻.' },
            { type: 'mcq', difficulty: 'Basic', question: 'N₂ molecule — nitrogen sharing electrons with nitrogen. Bond type is:', options: ['Ionic', 'Covalent', 'Metallic', 'Coordinate'], answer: 1, explanation: 'Non-metal + non-metal (same element) = covalent. N₂ has a N≡N triple bond.' },
            { type: 'mcq', difficulty: 'Basic', question: 'In a covalent bond, electrons are:', options: ['Transferred from metal to non-metal', 'Shared between non-metals', 'Lost to form ions', 'Delocalised in a sea'], answer: 1, explanation: 'Covalent bonding involves sharing electron pairs between atoms, usually both non-metals.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'CaO (calcium oxide) — identify the bond type.', options: ['Covalent', 'Ionic', 'Both', 'Neither'], answer: 1, explanation: 'Ca is a metal (Z=20), O is a non-metal (Z=8). Metal + non-metal = ionic. Ca²⁺ + O²⁻.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which compound is covalent?', options: ['NaCl', 'KBr', 'CH₄', 'MgO'], answer: 2, explanation: 'CH₄ (methane): C and H are both non-metals, sharing electron pairs → covalent. The others are all metal-nonmetal ionic compounds.' },
            { type: 'mcq', difficulty: 'Basic', question: 'CaCl₂ (calcium chloride) — Ca is a metal. Bond type is:', options: ['Covalent', 'Ionic', 'Metallic', 'Coordinate'], answer: 1, explanation: 'Ca (metal) + Cl (non-metal) = ionic bond. Ca gives 2 electrons to form Ca²⁺; each Cl gains 1 to form Cl⁻.' },
            { type: 'mcq', difficulty: 'Basic', question: 'HF (hydrogen fluoride) — both H and F are non-metals. Bond type is:', options: ['Ionic', 'Covalent', 'Metallic', 'Van der Waals'], answer: 1, explanation: 'H (non-metal) + F (non-metal) share 1 electron pair = covalent bond.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Which compound would you expect to have a HIGH melting point?', options: ['CH₄ (covalent)', 'O₂ (covalent)', 'NaCl (ionic)', 'CO₂ (covalent)'], answer: 2, explanation: 'Ionic compounds (NaCl) have high melting points because strong electrostatic forces hold ions together. Covalent compounds have weaker intermolecular forces → lower melting points.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Potassium bromide (KBr) — K is a metal, Br is a non-metal. Bond type is:', options: ['Covalent', 'Ionic', 'Metallic', 'Coordinate'], answer: 1, explanation: 'K (metal) + Br (non-metal) → ionic bond. K gives 1 electron to Br: K⁺ and Br⁻.' },
            { type: 'mcq', difficulty: 'Basic', question: 'In N₂ (nitrogen gas), the two nitrogen atoms are held by a:', options: ['Single bond (N–N)', 'Double bond (N=N)', 'Triple bond (N≡N)', 'Ionic bond'], answer: 2, explanation: 'N₂ has a N≡N triple bond (3 shared pairs, 6 electrons shared). This makes N₂ very stable and unreactive.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Ionic compounds conduct electricity when:', options: ['In solid state', 'In dissolved (aqueous) solution or molten state', 'Never — they are insulators', 'Only in gas state'], answer: 1, explanation: 'Ionic compounds conduct electricity only when dissolved in water or melted — because ions are then free to move. In solid state, ions are fixed in a crystal lattice.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'In ionic bonding, the metal atom typically:', options: ['Shares electrons', 'Gains electrons to form anion', 'Loses electrons to form cation', 'Shares one electron only'], answer: 2, explanation: 'Metals lose electrons to form positive cations. Non-metals gain those electrons to form negative anions. Opposite charges attract → ionic bond.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'MgO — what type of ion does each element form?', options: ['Mg⁻ and O⁺', 'Mg²⁺ and O²⁻', 'Mg⁺ and O⁻', 'Mg³⁺ and O³⁻'], answer: 1, explanation: 'Mg (K=2,L=8,M=2) loses 2 electrons → Mg²⁺. O (K=2,L=6) gains 2 electrons → O²⁻. Charges balance.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Cl₂ molecule — two chlorine atoms sharing one pair of electrons. Bond type:', options: ['Ionic', 'Metallic', 'Covalent single bond', 'Covalent double bond'], answer: 2, explanation: 'Cl (non-metal) + Cl (non-metal) share 1 pair = covalent single bond (Cl–Cl).' },
        ],
        assess: [
            { type: 'mcq', difficulty: 'Basic', question: 'LiF (lithium fluoride) — identify the bond type.', options: ['Covalent', 'Ionic', 'Metallic', 'Coordinate'], answer: 1, explanation: 'Li is a metal, F is a non-metal. Metal + non-metal = ionic bond. Li⁺ + F⁻.' },
            { type: 'mcq', difficulty: 'Basic', question: 'HCl molecule — hydrogen and chlorine share an electron pair. Bond type is:', options: ['Ionic', 'Covalent', 'Metallic', 'Hydrogen bond'], answer: 1, explanation: 'H (non-metal) + Cl (non-metal) share 1 electron pair = covalent bond.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which of these is an ionic compound?', options: ['H₂O', 'CO₂', 'NaCl', 'NH₃'], answer: 2, explanation: 'NaCl — Na is a metal, Cl is non-metal → ionic. H₂O, CO₂, NH₃ are all non-metal compounds (covalent).' },
            { type: 'mcq', difficulty: 'Basic', question: 'In an ionic bond, the metal atom:', options: ['Gains electrons', 'Shares electrons', 'Loses electrons', 'Neither gains nor loses'], answer: 2, explanation: 'Metals lose electrons to form positive ions (cations). The electrons transfer to non-metal atoms.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Na₂O (sodium oxide) — identify the bond type.', options: ['Covalent', 'Ionic', 'Both', 'Metallic'], answer: 1, explanation: 'Na is a metal, O is non-metal. Metal + non-metal = ionic. 2 Na atoms each donate 1 e⁻ to O.' },
            { type: 'mcq', difficulty: 'Basic', question: 'O₂ molecule — two oxygen atoms share electrons. Bond type is:', options: ['Ionic', 'Metallic', 'Covalent', 'Coordinate'], answer: 2, explanation: 'Non-metal (O) + non-metal (O) = covalent. O₂ has a O=O double bond.' },
            { type: 'mcq', difficulty: 'Basic', question: 'The bond in H₂ (hydrogen gas) is:', options: ['Ionic', 'Metallic', 'Covalent', 'None'], answer: 2, explanation: 'Two H atoms (both non-metals) share 1 electron pair = covalent single bond.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'AlCl₃ (aluminium chloride) — Al is a metal. Bond type is:', options: ['Covalent', 'Ionic', 'Metallic', 'Coordinate'], answer: 1, explanation: 'Al (metal) + Cl (non-metal) = ionic. Al loses 3 electrons to form Al³⁺; 3 Cl atoms each gain 1 e⁻.' },
            { type: 'mcq', difficulty: 'Basic', question: 'In covalent compounds, the electrons come from:', options: ['One atom only', 'A third atom', 'Both bonding atoms', 'Outside the molecule'], answer: 2, explanation: 'In covalent bonding, both atoms contribute electrons to the shared pair. Both atoms benefit from the shared electrons.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Which pair represents one ionic and one covalent compound?', options: ['NaCl and KBr', 'H₂O and CO₂', 'NaCl and H₂O', 'CH₄ and NH₃'], answer: 2, explanation: 'NaCl = ionic (Na metal + Cl non-metal). H₂O = covalent (O and H both non-metals sharing electrons).' },
            { type: 'mcq', difficulty: 'Basic', question: 'CaF₂ (calcium fluoride) bond type is:', options: ['Covalent', 'Ionic', 'Metallic', 'Coordinate'], answer: 1, explanation: 'Ca (metal) + F (non-metal) = ionic. Ca²⁺ + 2F⁻.' },
            { type: 'mcq', difficulty: 'Basic', question: 'SO₂ (sulfur dioxide) bond type is:', options: ['Ionic', 'Metallic', 'Covalent', 'Both ionic and covalent'], answer: 2, explanation: 'S (non-metal) + O (non-metal) share electrons = covalent. SO₂ has S=O double bonds.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which element forms the cation in NaCl?', options: ['Chlorine', 'Sodium', 'Both', 'Neither'], answer: 1, explanation: 'Sodium (Na) LOSES 1 electron → Na⁺ (cation, positive). Chlorine gains 1 electron → Cl⁻ (anion, negative).' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Which of these is NOT a covalent compound?', options: ['NH₃', 'CH₄', 'H₂S', 'KCl'], answer: 3, explanation: 'KCl — K is a metal, Cl is non-metal → ionic. NH₃, CH₄, H₂S all have non-metal + non-metal = covalent.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Magnesium oxide (MgO) forms when Mg burns. What ions are present?', options: ['Mg⁺ and O⁻', 'Mg²⁺ and O²⁻', 'Mg³⁺ and O³⁻', 'Mg⁴⁺ and O⁴⁻'], answer: 1, explanation: 'Mg (valency 2) gives 2e⁻ → Mg²⁺. O (valency 2) gains 2e⁻ → O²⁻. Opposite charges attract.' },
            { type: 'mcq', difficulty: 'Basic', question: 'F₂ (fluorine gas) bond type is:', options: ['Ionic', 'Metallic', 'Covalent', 'Coordinate'], answer: 2, explanation: 'F (non-metal) + F (non-metal) share 1 electron pair = covalent single bond (F–F).' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Covalent compounds are generally poor conductors of electricity because:', options: ['They have high melting points', 'They have no charged particles (no ions or free electrons)', 'They are all gases', 'They contain only carbon'], answer: 1, explanation: 'Covalent compounds consist of neutral molecules with no free ions or electrons. Without charged mobile particles, they cannot conduct electricity.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Which compound conducts electricity when dissolved in water?', options: ['CO₂', 'CH₄', 'NaCl', 'H₂'], answer: 2, explanation: 'NaCl (ionic) dissolves in water to release Na⁺ and Cl⁻ ions that carry electrical current. Covalent compounds form no ions.' },
            { type: 'mcq', difficulty: 'Basic', question: 'The bond in H₂O between oxygen and hydrogen is:', options: ['Ionic', 'Metallic', 'Covalent', 'Coordinate'], answer: 2, explanation: 'O (non-metal, Z=8) and H (non-metal, Z=1) share electron pairs = covalent bonds. O forms 2 covalent bonds with 2 H atoms.' },
        ]
    },
    {
        id: 'skill-4',
        title: 'Metals, Non-metals & Metalloids',
        desc: 'Classify elements as metals, non-metals, or metalloids based on their properties and position in the Periodic Table.',
        color: '#7c3aed',
        icon: '⚗️',
        learnSections: [
            {
                heading: 'Classification of Elements',
                content: 'Elements are broadly divided into three categories:\n\nMetals (left/centre of Periodic Table):\n• Shiny (lustre), hard, malleable (can be beaten flat)\n• Good conductors of heat and electricity\n• Form positive ions (cations) by losing electrons\n• Examples: Na, K, Mg, Ca, Fe, Cu, Al, Zn, Ag, Au\n\nNon-metals (top right of Periodic Table):\n• Dull, brittle (for solids), poor conductors\n• Form negative ions (anions) by gaining electrons OR covalent molecules\n• Examples: H, C, N, O, F, S, P, Cl, Br, I, noble gases\n\nMetalloids (along the staircase line):\n• Properties intermediate between metals and non-metals\n• Used as semiconductors in electronics\n• Examples: B, Si, Ge, As, Sb, Te',
                example: 'Silicon (Si) is a metalloid — it looks like a metal (shiny) but conducts electricity only partially (semiconductor). That\'s why it\'s used in computer chips!',
                keyLabel: 'key-fact',
                table: {
                    headers: ['Property', 'Metals', 'Non-metals', 'Metalloids'],
                    rows: [
                        ['Lustre', 'Shiny', 'Dull', 'Semi-shiny'],
                        ['Conductivity', 'Good', 'Poor', 'Semiconductor'],
                        ['Malleability', 'Malleable', 'Brittle', 'Brittle'],
                        ['Ion formed', 'Cation (+)', 'Anion (−)', 'Both possible'],
                        ['State (at 25°C)', 'Mostly solid', 'Mostly gas/solid', 'Solid'],
                    ]
                }
            }
        ],
        practice: [
            { type: 'mcq', difficulty: 'Basic', question: 'Iron (Fe, Z=26) is:', options: ['Non-metal', 'Metal', 'Metalloid', 'Noble gas'], answer: 1, explanation: 'Iron is a typical metal — shiny, hard, malleable, good conductor. Used in construction.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Oxygen (O, Z=8) is:', options: ['Metal', 'Metalloid', 'Non-metal', 'Noble gas'], answer: 2, explanation: 'Oxygen is a non-metal — it\'s a gas at room temperature, poor conductor, forms negative O²⁻ ions.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Silicon (Si, Z=14) is used in computer chips because it is a:', options: ['Metal', 'Non-metal', 'Metalloid (semiconductor)', 'Noble gas'], answer: 2, explanation: 'Silicon is a metalloid — it has intermediate properties and acts as a semiconductor.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Sodium (Na, Z=11) is:', options: ['Non-metal', 'Metalloid', 'Noble gas', 'Metal'], answer: 3, explanation: 'Sodium is an alkali metal — shiny, very reactive, loses 1 electron to form Na⁺.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Which of these is a metalloid?', options: ['Sodium (Na)', 'Germanium (Ge)', 'Chlorine (Cl)', 'Calcium (Ca)'], answer: 1, explanation: 'Germanium (Ge, Z=32) is a metalloid, used as a semiconductor. The others are metal, non-metal, and metal respectively.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Sulfur (S, Z=16) is:', options: ['Metal', 'Non-metal', 'Metalloid', 'Transition metal'], answer: 1, explanation: 'Sulfur is a non-metal — yellow solid, poor conductor, forms S²⁻ ions or covalent bonds.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which element is a good conductor of electricity?', options: ['Sulfur', 'Phosphorus', 'Copper (Cu)', 'Silicon'], answer: 2, explanation: 'Copper (Cu) is a metal and excellent conductor. It\'s the most widely used material for electrical wires.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Carbon (C, Z=6) is:', options: ['Metal', 'Non-metal', 'Metalloid', 'Noble gas'], answer: 1, explanation: 'Carbon is a non-metal — forms covalent compounds, basis of all organic chemistry. Poor electrical conductor (except graphite).' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Which set contains ONLY metals?', options: ['Na, K, Ca, Fe', 'Na, Cl, O, H', 'Si, Ge, B, As', 'C, N, O, S'], answer: 0, explanation: 'Na (sodium), K (potassium), Ca (calcium), Fe (iron) are all metals. The other sets include non-metals or metalloids.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which property is characteristic of metals?', options: ['Dull appearance', 'Brittle when hit', 'Good electrical conductors', 'Form anions easily'], answer: 2, explanation: 'Metals are good conductors of heat and electricity due to their free electrons. They are shiny, malleable, and form cations.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Gold (Au, Z=79) is:', options: ['Non-metal', 'Metalloid', 'Metal', 'Noble gas'], answer: 2, explanation: 'Gold is a metal — shiny, malleable, excellent conductor. Used in jewellery and electronics.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Bromine (Br, Z=35) is:', options: ['Metal', 'Metalloid', 'Non-metal', 'Noble gas'], answer: 2, explanation: 'Bromine is a non-metal — the only non-metal that is a liquid at room temperature. Forms Br⁻ ions.' },
            { type: 'mcq', difficulty: 'Basic', question: 'The ability of metals to be drawn into thin wires is called:', options: ['Malleability', 'Conductivity', 'Ductility', 'Lustre'], answer: 2, explanation: 'Ductility is the ability to be drawn into thin wires. Malleability is beating into sheets. Both are metal properties.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Boron (B, Z=5) lies along the staircase in the Periodic Table. It is:', options: ['Metal', 'Non-metal', 'Metalloid', 'Noble gas'], answer: 2, explanation: 'Boron is a metalloid — it has intermediate properties, is a semiconductor, and lies on the boundary between metals and non-metals.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Non-metals generally form _____ ions.', options: ['Cations (positive)', 'Anions (negative)', 'Both equally', 'No ions'], answer: 1, explanation: 'Non-metals gain electrons to form anions (negative ions). e.g., Cl → Cl⁻, O → O²⁻, N → N³⁻.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Lithium (Li, Z=3) is:', options: ['Non-metal', 'Metalloid', 'Metal', 'Noble gas'], answer: 2, explanation: 'Lithium is an alkali metal — the lightest metal, reacts vigorously with water, forms Li⁺ ions.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which set contains ONLY non-metals?', options: ['Fe, Cu, Zn, Al', 'C, N, O, F', 'Si, Ge, B, As', 'Na, K, Ca, Mg'], answer: 1, explanation: 'C (carbon), N (nitrogen), O (oxygen), F (fluorine) are all non-metals.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Germanium (Ge, Z=32) is used in semiconductors because it is a:', options: ['Metal with low resistance', 'Non-metal', 'Metalloid with intermediate conductivity', 'Noble gas'], answer: 2, explanation: 'Germanium is a metalloid — its semiconducting properties make it useful in transistors and early computer chips.' },
        ],
        assess: [
            { type: 'mcq', difficulty: 'Basic', question: 'Aluminium (Al, Z=13) is:', options: ['Non-metal', 'Metalloid', 'Metal', 'Noble gas'], answer: 2, explanation: 'Aluminium is a metal — shiny, light, good conductor, used in aircraft and packaging.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Chlorine (Cl, Z=17) is:', options: ['Metal', 'Metalloid', 'Noble gas', 'Non-metal'], answer: 3, explanation: 'Chlorine is a non-metal — yellow-green gas, forms Cl⁻ ions, used in water purification.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Which element is a metalloid?', options: ['Potassium (K)', 'Boron (B)', 'Hydrogen (H)', 'Neon (Ne)'], answer: 1, explanation: 'Boron (B, Z=5) is a metalloid — hard solid with properties between metals and non-metals.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which type of element forms positive ions (cations)?', options: ['Non-metals', 'Noble gases', 'Metals', 'Metalloids'], answer: 2, explanation: 'Metals lose electrons to form positive ions (cations). Na → Na⁺, Mg → Mg²⁺, Ca → Ca²⁺.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Phosphorus (P, Z=15) is:', options: ['Metal', 'Non-metal', 'Metalloid', 'Noble gas'], answer: 1, explanation: 'Phosphorus is a non-metal — exists as P₄ solid, forms covalent bonds, poor conductor.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which element forms a negative ion (anion)?', options: ['Sodium (Na)', 'Calcium (Ca)', 'Chlorine (Cl)', 'Iron (Fe)'], answer: 2, explanation: 'Chlorine (non-metal) gains 1 electron to form Cl⁻ (anion). Metals form cations, not anions.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Arsenic (As, Z=33) lies along the staircase line in the Periodic Table. It is a:', options: ['Metal', 'Non-metal', 'Metalloid', 'Noble gas'], answer: 2, explanation: 'Arsenic lies on the staircase line between metals and non-metals — it is a metalloid.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which set contains ONLY non-metals?', options: ['Na, K, Li', 'H, O, N, S', 'Si, Ge, B', 'Fe, Cu, Zn'], answer: 1, explanation: 'H, O, N, S are all non-metals. Na/K/Li are alkali metals; Si/Ge/B are metalloids; Fe/Cu/Zn are transition metals.' },
            { type: 'mcq', difficulty: 'Basic', question: 'The property of a metal that allows it to be beaten into thin sheets is called:', options: ['Conductivity', 'Lustre', 'Malleability', 'Ductility'], answer: 2, explanation: 'Malleability is the ability to be beaten into sheets. Ductility is the ability to be drawn into wires. Both are properties of metals.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Mercury (Hg, Z=80) is the only metal that is a liquid at room temperature. It is classified as a:', options: ['Non-metal', 'Metalloid', 'Metal', 'Noble gas'], answer: 2, explanation: 'Mercury is a metal — despite being liquid, it conducts electricity, has metallic lustre, and forms Hg²⁺ ions.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Copper (Cu, Z=29) is:', options: ['Non-metal', 'Metalloid', 'Metal', 'Noble gas'], answer: 2, explanation: 'Copper is a metal — excellent electrical conductor (used in wires), red-orange colour, malleable.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Nitrogen (N, Z=7) is:', options: ['Metal', 'Metalloid', 'Non-metal', 'Noble gas'], answer: 2, explanation: 'Nitrogen is a non-metal — colourless gas, makes up 78% of air, forms N³⁻ ions (or covalent bonds like NH₃).' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Tellurium (Te, Z=52) lies on the staircase line. It is:', options: ['Metal', 'Non-metal', 'Metalloid', 'Noble gas'], answer: 2, explanation: 'Tellurium is a metalloid — lies along the staircase dividing metals from non-metals, has semiconductor properties.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Which property is characteristic of non-metals?', options: ['Good conductors of heat', 'Shiny lustre', 'Brittle when solid', 'Form positive ions'], answer: 2, explanation: 'Non-metals are brittle when solid — they break easily rather than bending. They are dull, poor conductors, and form anions or covalent compounds.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Silver (Ag, Z=47) is:', options: ['Non-metal', 'Metalloid', 'Noble gas', 'Metal'], answer: 3, explanation: 'Silver is a metal — the best conductor of electricity among metals, shiny, malleable.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Which set contains ONLY metalloids?', options: ['Na, K, Li', 'C, N, O', 'Si, Ge, As', 'Fe, Cu, Zn'], answer: 2, explanation: 'Silicon (Si), Germanium (Ge), and Arsenic (As) are all metalloids — they lie along the staircase line between metals and non-metals.' },
            { type: 'mcq', difficulty: 'Basic', question: 'The shiny appearance of metals is called:', options: ['Conductivity', 'Malleability', 'Lustre', 'Ductility'], answer: 2, explanation: 'Lustre is the shiny appearance of metals due to their ability to reflect light.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Hydrogen (H, Z=1) is classified as a:', options: ['Metal', 'Metalloid', 'Non-metal', 'Noble gas'], answer: 2, explanation: 'Hydrogen is a non-metal — a gas at room temperature, forms H⁺ ions or covalent bonds.' },
            { type: 'mcq', difficulty: 'Intermediate', question: 'Why are metals good conductors of electricity?', options: ['Because they are heavy', 'Because they have free electrons that can move through the metal', 'Because they are shiny', 'Because they form ionic bonds'], answer: 1, explanation: 'In metals, outer electrons are loosely held and form a "sea" of free electrons. These mobile electrons carry electrical current through the metal.' },
            { type: 'mcq', difficulty: 'Basic', question: 'Magnesium (Mg, Z=12) is:', options: ['Non-metal', 'Metalloid', 'Noble gas', 'Metal'], answer: 3, explanation: 'Magnesium is a metal — light, shiny, burns with a bright white flame, forms Mg²⁺ ions.' },
        ]
    },
];
