export const cards5W1H = [
    {
        q: 'WHAT',
        label: 'What is the Number System?',
        icon: '🔢',
        gradFrom: '#0891b2',
        gradTo: '#06b6d4',
        shadow: 'rgba(6,182,212,0.35)',
        content: `A number system is a way to express numbers using symbols. In Grade 9, we dive deep into "Real Numbers" (\\mathbb{R}). This includes Rational numbers (like $2/3$) and Irrational numbers (like $\\sqrt{2}$). It's the complete collection of all points on an infinite line!`,
        fact: '💡 Every single point on the number line represents a unique real number.',
    },
    {
        q: 'WHO',
        label: 'Who discovered these numbers?',
        icon: '👥',
        gradFrom: '#059669',
        gradTo: '#10b981',
        shadow: 'rgba(16,185,129,0.35)',
        content: `Mathematicians across centuries! Indians like Aryabhata gave us zero. Pythagoras and his followers discovered irrationals like $\\sqrt{2}$ (and were shocked by them!). Later, Georg Cantor defined different "sizes" of infinity within the number system!`,
        fact: '💡 The concept of "Zero" and the decimal system originated in India over 1,500 years ago!',
    },
    {
        q: 'WHEN',
        label: 'When do we use Real Numbers?',
        icon: '📅',
        gradFrom: '#b45309',
        gradTo: '#f59e0b',
        shadow: 'rgba(245,158,11,0.35)',
        content: `Always! When measuring length, time, or temperature. Unlike integers (counting 1, 2, 3), real numbers allow us to measure the exact distance between two points, no matter how small or irregular that distance is.`,
        fact: '💡 Computers use the Binary Number System (0s and 1s) to perform all their calculations!',
    },
    {
        q: 'WHERE',
        label: 'Where is this applied?',
        icon: '🌍',
        gradFrom: '#be185d',
        gradTo: '#ec4899',
        shadow: 'rgba(236,72,153,0.35)',
        content: `Everywhere! Architects use irrationals for precise angles. Physicists use exponents to calculate the speed of light ($3 \\times 10^8$ m/s). Banks use decimals for exact currency exchange. Without a precise number system, modern technology would collapse!`,
        fact: '💡 $\\pi$ (Pi) is an irrational number used in every single circle-related calculation in engineering!',
    },
    {
        q: 'WHY',
        label: 'Why classify numbers?',
        icon: '🚀',
        gradFrom: '#7c3aed',
        gradTo: '#a855f7',
        shadow: 'rgba(168,85,247,0.35)',
        content: `Classifying numbers helps us understand their properties and behavior. Rational numbers can be written as fractions, while irrationals cannot. Knowing the difference helps us decide whether to use exact calculations or decimal approximations in science.`,
        fact: '💡 Understanding number types is crucial for higher-level math like Calculus and Algebra!',
    },
    {
        q: 'HOW',
        label: 'How do numbers behave?',
        icon: '🎯',
        gradFrom: '#0369a1',
        gradTo: '#3b82f6',
        shadow: 'rgba(59,130,246,0.35)',
        content: `Numbers follow strict rules called "Laws." Whether it's the $a^m \\cdot a^n = a^{m+n}$ laws of exponents or the rules for rationalizing denominators, these properties allow us to simplify complex expressions and solve real-world problems.`,
        fact: '💡 Mastering these laws makes solving complex algebraic equations significantly easier!',
    },
];
