// skillsData.js for Grade 4 - Shapes Around Us
// 20 practice + 20 assessment questions per skill
// Questions include image/visual fields for interactive picture-based content

export const skillsData = [
    {
        id: 'identifying-3d-shapes',
        title: 'Identifying 3D Shapes',
        desc: 'Learn about faces, edges, and corners of 3D solids.',
        color: '#d97706',
        icon: '<svg width="1em" height="1em" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><polygon points="50,15 85,32 50,50 15,32" fill="#dbeafe" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="15,32 50,50 50,85 15,68" fill="#60a5fa" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="50,50 85,32 85,68 50,85" fill="#93c5fd" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/></svg>',
        learnSections: [
            {
                heading: 'Faces, Edges, and Vertices',
                content: '3D objects are made of flat surfaces (faces), the lines where faces meet (edges), and the sharp points where edges meet (vertices/corners).',
                example: 'A cube has 6 flat faces, 12 edges, and 8 vertices.',
            },
            {
                heading: 'Curved vs Flat',
                content: 'Some objects only have flat faces (like a box). Some only have curved faces (like a ball/sphere). And some have both (like a cylinder/can).',
                example: 'A sphere has 1 curved face, 0 edges, and 0 vertices.',
            }
        ],
        practice: [
            { type: 'multiple-choice', question: 'How many flat faces does a standard cube have?', options: ['4', '6', '8', '12'], correctAnswer: 1, explanation: 'A cube has 6 flat faces (like the 6 numbered sides on a dice).', image: '<svg width="1em" height="1em" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><polygon points="50,15 85,32 50,50 15,32" fill="#dbeafe" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="15,32 50,50 50,85 15,68" fill="#60a5fa" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="50,50 85,32 85,68 50,85" fill="#93c5fd" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/></svg>' },
            { type: 'multiple-choice', question: 'Which of these 3D shapes has ZERO flat faces?', options: ['Cube', 'Cone', 'Sphere', 'Cylinder'], correctAnswer: 2, explanation: 'A sphere is completely round — it only has 1 curved face and 0 flat faces.', image: '⚽' },
            { type: 'multiple-choice', question: 'A shape with a circular base and a point at the top is called a...', options: ['Cylinder', 'Cone', 'Pyramid', 'Prism'], correctAnswer: 1, explanation: 'A cone has a circular flat base and gently curves up to a single point (apex).', image: '🍦' },
            { type: 'multiple-choice', question: 'How many corners (vertices) does a square pyramid have?', options: ['4', '5', '6', '8'], correctAnswer: 1, explanation: 'A square pyramid has 4 corners at the base + 1 at the top = 5 vertices.' },
            { type: 'multiple-choice', question: 'What is the math word for a corner on a 3D shape?', options: ['Face', 'Edge', 'Vertex', 'Line'], correctAnswer: 2, explanation: 'The sharp point where edges meet is called a Vertex (plural: Vertices).' },
            { type: 'multiple-choice', question: 'I have 6 flat faces. All my faces are identical squares. What am I?', options: ['Cuboid', 'Square Pyramid', 'Cube', 'Cylinder'], correctAnswer: 2, explanation: 'A cube is built entirely from 6 identical square faces.', image: '<svg width="1em" height="1em" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><polygon points="50,15 85,32 50,50 15,32" fill="#dbeafe" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="15,32 50,50 50,85 15,68" fill="#60a5fa" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="50,50 85,32 85,68 50,85" fill="#93c5fd" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/></svg>' },
            { type: 'multiple-choice', question: 'Which shape can roll?', options: ['Cube', 'Pyramid', 'Cylinder', 'Cuboid'], correctAnswer: 2, explanation: 'A cylinder can roll because it has a curved face around its middle.', image: '🥫' },
            { type: 'multiple-choice', question: 'Look at this cube. How many edges does it have?', options: ['6', '8', '10', '12'], correctAnswer: 3, explanation: 'A cube has 12 edges: 4 on top, 4 on bottom, and 4 verticals.', image: '<svg width="1em" height="1em" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><polygon points="50,15 85,32 50,50 15,32" fill="#dbeafe" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="15,32 50,50 50,85 15,68" fill="#60a5fa" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="50,50 85,32 85,68 50,85" fill="#93c5fd" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/></svg>' },
            { type: 'multiple-choice', question: 'Which shape has exactly 1 flat face and 1 curved face?', options: ['Sphere', 'Cylinder', 'Cone', 'Cuboid'], correctAnswer: 2, explanation: 'A cone has 1 flat circular base and 1 curved face that wraps around to the tip.', image: '🍦' },
            { type: 'multiple-choice', question: 'Look at a football (soccer ball). What 3D shape is it closest to?', options: ['Cube', 'Cylinder', 'Sphere', 'Cone'], correctAnswer: 2, explanation: 'A football is round from every direction, making it a sphere.', image: '⚽' },
            { type: 'multiple-choice', question: 'A rectangular prism (like a brick) has how many faces?', options: ['4', '5', '6', '8'], correctAnswer: 2, explanation: 'A rectangular prism has 6 faces: top, bottom, front, back, left, right.', image: '<svg width="1.2em" height="0.9em" viewBox="0 0 120 90" xmlns="http://www.w3.org/2000/svg"><polygon points="60,15 105,30 60,45 15,30" fill="#dbeafe" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="15,30 60,45 60,75 15,60" fill="#60a5fa" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="60,45 105,30 105,60 60,75" fill="#93c5fd" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/></svg>' },
            { type: 'multiple-choice', question: 'How many vertices does a sphere have?', options: ['0', '1', '4', '8'], correctAnswer: 0, explanation: 'A sphere is perfectly round with no corners or vertices at all.' },
            { type: 'multiple-choice', question: 'Look at an ice cream cone. Which 3D shapes combine to make it?', options: ['Cube + Sphere', 'Cone + Sphere', 'Cylinder + Cone', 'Pyramid + Cube'], correctAnswer: 1, explanation: 'The cone holds the scoop, and the scoop is a sphere (half-sphere) sitting on top!', image: '🍨' },
            { type: 'multiple-choice', question: 'A cereal box is an example of which 3D shape?', options: ['Cube', 'Cylinder', 'Rectangular Prism', 'Cone'], correctAnswer: 2, explanation: 'A cereal box has 6 rectangular faces, making it a rectangular prism (cuboid).', image: '🥣' },
            { type: 'multiple-choice', question: 'Which shape has more edges: a cube or a square pyramid?', options: ['Cube', 'Square Pyramid', 'Both have the same', 'Neither has edges'], correctAnswer: 0, explanation: 'A cube has 12 edges. A square pyramid has only 8 edges.' },
            { type: 'multiple-choice', question: 'If you stack 2 cubes on top of each other, what shape do you get?', options: ['Cube', 'Rectangular Prism', 'Cylinder', 'Pyramid'], correctAnswer: 1, explanation: 'Stacking two identical cubes creates a tall rectangular prism.', image: '<svg width="1em" height="1.5em" viewBox="0 0 100 150" xmlns="http://www.w3.org/2000/svg"><polygon points="15,82 50,100 50,135 15,118" fill="#60a5fa" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="50,100 85,82 85,118 50,135" fill="#93c5fd" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="50,15 85,32 50,50 15,32" fill="#dbeafe" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="15,32 50,50 50,85 15,68" fill="#60a5fa" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="50,50 85,32 85,68 50,85" fill="#93c5fd" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/></svg>' },
            { type: 'multiple-choice', question: 'Which of these real objects looks like a cylinder?', options: ['Basketball', 'Soda can', 'Dice', 'Birthday cap'], correctAnswer: 1, explanation: 'A soda can has 2 flat circular faces (top and bottom) and 1 curved face.', image: '🥫' },
            { type: 'multiple-choice', question: 'A triangular prism has how many flat faces?', options: ['3', '4', '5', '6'], correctAnswer: 2, explanation: 'A triangular prism has 2 triangular ends + 3 rectangular sides = 5 flat faces.' },
            { type: 'multiple-choice', question: 'Which 3D shape has the MOST vertices: cube or triangular prism?', options: ['Cube (8)', 'Triangular Prism (6)', 'They are equal', 'Cannot compare'], correctAnswer: 0, explanation: 'A cube has 8 vertices while a triangular prism has only 6.' },
            { type: 'multiple-choice', question: 'A party hat is shaped like which 3D figure?', options: ['Cube', 'Cylinder', 'Cone', 'Sphere'], correctAnswer: 2, explanation: 'A party hat is cone-shaped — it has a circular base and comes to a point at the top.', image: '🎉' }
        ],
        assessment: [
            { type: 'multiple-choice', question: 'How many faces does a cube have?', options: ['4', '6', '8', '12'], correctAnswer: 1, explanation: 'A cube has exactly 6 square faces.' },
            { type: 'multiple-choice', question: 'How many edges does a cube have?', options: ['6', '8', '10', '12'], correctAnswer: 3, explanation: '4 edges on top + 4 on bottom + 4 connecting = 12 edges.' },
            { type: 'multiple-choice', question: 'Which 3D shape has exactly 1 curved face and NO flat faces?', options: ['Cylinder', 'Cone', 'Sphere', 'Cube'], correctAnswer: 2, explanation: 'A sphere is perfectly round with only 1 curved surface.' },
            { type: 'multiple-choice', question: 'A square pyramid has how many corners?', options: ['4', '5', '6', '8'], correctAnswer: 1, explanation: '4 base corners + 1 apex = 5 vertices.' },
            { type: 'multiple-choice', question: 'I have 2 flat circular faces and 1 curved face. What am I?', options: ['Cylinder', 'Cone', 'Sphere', 'Prism'], correctAnswer: 0, explanation: 'A cylinder has 2 circular flat faces (top and bottom) and 1 curved face.' },
            { type: 'multiple-choice', question: 'How many flat faces does a sphere have?', options: ['0', '1', '2', '6'], correctAnswer: 0, explanation: 'A sphere has zero flat faces — it is entirely curved.' },
            { type: 'multiple-choice', question: 'A rectangular prism has how many rectangular faces?', options: ['4', '6', '8', '12'], correctAnswer: 1, explanation: 'A rectangular prism (cuboid) has 6 rectangular faces.' },
            { type: 'multiple-choice', question: 'What is the line called where two flat faces meet?', options: ['Vertex', 'Corner', 'Edge', 'Slice'], correctAnswer: 2, explanation: 'An edge is the line segment where two faces of a 3D shape meet.' },
            { type: 'multiple-choice', question: 'Which of these shapes CANNOT roll?', options: ['Cylinder', 'Cone', 'Sphere', 'Cube'], correctAnswer: 3, explanation: 'A cube has only flat faces and no curves, so it cannot roll.' },
            { type: 'multiple-choice', question: 'How many vertices does a cone have?', options: ['0', '1', '2', '3'], correctAnswer: 1, explanation: 'A cone has just 1 vertex — the pointed tip at the top.' },
            { type: 'multiple-choice', question: 'A triangular prism has how many edges?', options: ['6', '8', '9', '12'], correctAnswer: 2, explanation: '3 edges on each triangular end (6) + 3 connecting edges = 9 total.' },
            { type: 'multiple-choice', question: 'Which real-world object is closest to a sphere?', options: ['Tissue box', 'Tennis ball', 'Soda can', 'Book'], correctAnswer: 1, explanation: 'A tennis ball is round from every direction, like a sphere.', image: '🎾' },
            { type: 'multiple-choice', question: 'A cone has how many edges?', options: ['0', '1', '2', '3'], correctAnswer: 1, explanation: 'A cone has 1 curved edge where the circular base meets the curved surface.' },
            { type: 'multiple-choice', question: 'Which shape has both flat and curved faces?', options: ['Cube', 'Sphere', 'Cylinder', 'Square Pyramid'], correctAnswer: 2, explanation: 'A cylinder has 2 flat circular faces and 1 curved face.' },
            { type: 'multiple-choice', question: 'How many faces does a triangular pyramid (tetrahedron) have?', options: ['3', '4', '5', '6'], correctAnswer: 1, explanation: 'A triangular pyramid has 4 triangular faces.' },
            { type: 'multiple-choice', question: 'Which has more faces: a cube or a square pyramid?', options: ['Cube (6)', 'Square Pyramid (5)', 'They are equal', 'Cannot tell'], correctAnswer: 0, explanation: 'A cube has 6 faces; a square pyramid has 5.' },
            { type: 'multiple-choice', question: 'If you cut a cylinder in half horizontally, the cross-section is a...', options: ['Square', 'Circle', 'Triangle', 'Rectangle'], correctAnswer: 1, explanation: 'Cutting a cylinder horizontally reveals a circle (its base shape).' },
            { type: 'multiple-choice', question: 'A pencil without the sharpened tip is closest to which shape?', options: ['Cone', 'Cylinder', 'Sphere', 'Cube'], correctAnswer: 1, explanation: 'An unsharpened pencil is a long cylinder.', image: '✏️' },
            { type: 'multiple-choice', question: 'How many vertices does a rectangular prism have?', options: ['4', '6', '8', '12'], correctAnswer: 2, explanation: '4 vertices on the top face + 4 on the bottom = 8 vertices.' },
            { type: 'multiple-choice', question: 'Which shape has exactly 5 faces, 8 edges, and 5 vertices?', options: ['Cube', 'Triangular Prism', 'Square Pyramid', 'Cylinder'], correctAnswer: 2, explanation: 'A square pyramid: 1 square base + 4 triangular sides = 5 faces, 8 edges, 5 vertices.' }
        ]
    },
    {
        id: 'nets-of-shapes',
        title: 'Nets of Solids',
        desc: 'Understand how flat 2D shapes fold into 3D objects.',
        color: '#059669',
        icon: '<svg width="1em" height="1em" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><polygon points="50,15 85,32 50,50 15,32" fill="#dbeafe" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="15,32 50,50 50,85 15,68" fill="#60a5fa" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="50,50 85,32 85,68 50,85" fill="#93c5fd" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/></svg>',
        learnSections: [
            {
                heading: 'What is a Net?',
                content: 'A net is a 2D flat shape that can be folded along its edges to form a 3D object. Imagine unfolding a cardboard box and laying it completely flat.',
                example: 'The net of a cube is made of 6 connected squares. If you cut it out and fold the lines, it makes a perfect box.',
            },
            {
                heading: 'Visualizing Prisms and Pyramids',
                content: 'You can identify a shape from its net. If the net has a square in the middle with 4 triangles attached, it folds into a square pyramid!',
                example: 'A cylinder net looks like a large rectangle with two circles attached to opposite edges.',
            }
        ],
        practice: [
            { type: 'multiple-choice', question: 'The net of a cube consists of how many squares?', options: ['4', '5', '6', '8'], correctAnswer: 2, explanation: 'A cube has 6 faces, so its flat net must also have 6 squares.', image: '⬜⬜⬜⬜⬜⬜' },
            { type: 'multiple-choice', question: 'A net with 1 large rectangle and 2 identical circles folds into a...', options: ['Cone', 'Cylinder', 'Rectangular Prism', 'Sphere'], correctAnswer: 1, explanation: 'The rectangle rolls up and the circles become the top and bottom of the cylinder.', image: '🔴▬🔴' },
            { type: 'multiple-choice', question: 'A net with 1 square center and 4 triangles on its sides folds into a...', options: ['Triangular Prism', 'Square Pyramid', 'Cube', 'Cone'], correctAnswer: 1, explanation: 'The square is the base, and the 4 triangles fold up to meet at a point.' },
            { type: 'multiple-choice', question: 'The net of a cone is made from...', options: ['1 circle and 1 rectangle', '1 circle and 1 curved fan shape', '2 circles and 1 rectangle', '2 circles only'], correctAnswer: 1, explanation: 'A cone net has a circular base and a curved pie/fan shape.' },
            { type: 'multiple-choice', question: 'If you unfold a cereal box, how many rectangles will you see?', options: ['4', '6', '8', '12'], correctAnswer: 1, explanation: 'A cereal box has 6 rectangular faces, so the net has 6 rectangles.', image: '🥣' },
            { type: 'multiple-choice', question: 'Can ANY arrangement of 6 connected squares form a cube net?', options: ['Yes, always', 'No, only certain arrangements', 'Only if squares overlap', 'Only with tape'], correctAnswer: 1, explanation: 'The squares must be in specific patterns (like a cross shape) to fold without overlapping.' },
            { type: 'multiple-choice', question: 'Which 3D shape CANNOT be made by folding a flat paper net?', options: ['Cylinder', 'Pyramid', 'Sphere', 'Cube'], correctAnswer: 2, explanation: 'A sphere is curved in every direction. You cannot fold flat paper into a perfect sphere.' },
            { type: 'multiple-choice', question: 'A net made of 4 identical triangles folds into a...', options: ['Square Pyramid', 'Triangular Pyramid', 'Triangular Prism', 'Cone'], correctAnswer: 1, explanation: 'A triangular pyramid (tetrahedron) is made entirely of 4 triangular faces.' },
            { type: 'multiple-choice', question: 'A net with 2 triangles and 3 rectangles folds into a...', options: ['Triangular Prism', 'Square Pyramid', 'Triangular Pyramid', 'Cube'], correctAnswer: 0, explanation: 'Two triangles make the ends; three rectangles form the sides of a triangular prism.' },
            { type: 'multiple-choice', question: 'How many squares must a cube net have?', options: ['4', '5', '6', '7'], correctAnswer: 2, explanation: 'Every cube net has exactly 6 squares, one for each face.' },
            { type: 'multiple-choice', question: 'If you cut open a toilet paper roll and flatten it, what shape do you get?', options: ['Circle', 'Square', 'Rectangle', 'Triangle'], correctAnswer: 2, explanation: 'The curved surface of a cylinder unrolls into a flat rectangle.', image: '🧻' },
            { type: 'multiple-choice', question: 'A net shaped like a plus/cross (+) with 6 squares folds into a...', options: ['Pyramid', 'Prism', 'Cube', 'Cylinder'], correctAnswer: 2, explanation: 'The cross/plus shape is one of the most common cube nets!', image: '➕' },
            { type: 'multiple-choice', question: 'The net of a rectangular prism has...', options: ['6 identical squares', '6 rectangles (3 pairs)', '4 rectangles', '8 rectangles'], correctAnswer: 1, explanation: 'A rectangular prism has 3 pairs of matching rectangular faces = 6 rectangles total.' },
            { type: 'multiple-choice', question: 'Which net will NOT fold into a closed 3D shape?', options: ['6 squares in a cross', '4 triangles', '3 separate squares', '1 rectangle + 2 circles'], correctAnswer: 2, explanation: '3 separate (disconnected) squares cannot fold into anything — the pieces must be connected!' },
            { type: 'multiple-choice', question: 'A hexagonal prism net would include which shapes?', options: ['2 hexagons + 6 rectangles', '6 hexagons', '2 squares + 4 triangles', '1 circle + 1 rectangle'], correctAnswer: 0, explanation: 'A hexagonal prism has 2 hexagonal ends and 6 rectangular sides.' },
            { type: 'multiple-choice', question: 'If a shape has 5 faces (1 square + 4 triangles), its net has...', options: ['5 shapes total', '4 shapes total', '6 shapes total', '9 shapes total'], correctAnswer: 0, explanation: 'Each face becomes one shape in the net. 5 faces = 5 shapes.' },
            { type: 'multiple-choice', question: 'Look at this cube. If you unfolded it, opposite faces must NOT be...', options: ['The same color', 'Next to each other in the net', 'Squares', 'Flat'], correctAnswer: 1, explanation: 'In a valid cube net, opposite faces of the cube are never adjacent/touching.', image: '<svg width="1em" height="1em" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><polygon points="50,15 85,32 50,50 15,32" fill="#dbeafe" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="15,32 50,50 50,85 15,68" fill="#60a5fa" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/><polygon points="50,50 85,32 85,68 50,85" fill="#93c5fd" stroke="#1e3a8a" stroke-width="4" stroke-linejoin="miter"/></svg>' },
            { type: 'multiple-choice', question: 'How many different valid nets can a cube have?', options: ['1', '6', '11', '20'], correctAnswer: 2, explanation: 'There are exactly 11 different ways to arrange 6 squares into a valid cube net.' },
            { type: 'multiple-choice', question: 'A pentagonal pyramid net has 1 pentagon and how many triangles?', options: ['3', '4', '5', '6'], correctAnswer: 2, explanation: 'A pentagon has 5 sides, so 5 triangles fold up from each side to meet at the top.' },
            { type: 'multiple-choice', question: 'If you see a T-shaped arrangement of 6 squares, can it fold into a cube?', options: ['Yes', 'No', 'Only with glue', 'Only if rotated'], correctAnswer: 0, explanation: 'The T-shape is one of the 11 valid cube nets!' }
        ],
        assessment: [
            { type: 'multiple-choice', question: 'How many squares are in the net of a cube?', options: ['4', '5', '6', '8'], correctAnswer: 2, explanation: 'A cube has 6 faces, all squares, so its net has 6 squares.' },
            { type: 'multiple-choice', question: 'A net with 1 square and 4 triangles folds into a...', options: ['Cube', 'Square Pyramid', 'Prism', 'Cone'], correctAnswer: 1, explanation: 'Square base + 4 triangular sides = square pyramid.' },
            { type: 'multiple-choice', question: 'Which shape CANNOT have a flat paper net?', options: ['Sphere', 'Cube', 'Pyramid', 'Cylinder'], correctAnswer: 0, explanation: 'A sphere is curved everywhere — flat paper cannot form it.' },
            { type: 'multiple-choice', question: 'A net of 1 rectangle and 2 circles folds into a...', options: ['Cone', 'Sphere', 'Cylinder', 'Prism'], correctAnswer: 2, explanation: 'Rectangle becomes the curved surface; circles become top and bottom.' },
            { type: 'multiple-choice', question: 'How many rectangles are in the net of a rectangular prism?', options: ['4', '5', '6', '8'], correctAnswer: 2, explanation: 'A rectangular prism has 6 faces, all rectangles.' },
            { type: 'multiple-choice', question: 'A net with 4 identical triangles folds into a...', options: ['Square Pyramid', 'Triangular Pyramid', 'Cube', 'Cone'], correctAnswer: 1, explanation: 'Four identical triangles form a tetrahedron (triangular pyramid).' },
            { type: 'multiple-choice', question: 'Can all arrangements of 6 connected squares fold into a cube?', options: ['Yes', 'No'], correctAnswer: 1, explanation: 'Only 11 specific arrangements (out of 35) can fold into a cube.' },
            { type: 'multiple-choice', question: 'The net of a cone has a circle and a...', options: ['Rectangle', 'Triangle', 'Curved Fan Shape', 'Square'], correctAnswer: 2, explanation: 'The curved surface of a cone becomes a fan/sector shape when flattened.' },
            { type: 'multiple-choice', question: 'If a shape has 6 faces, its net has how many 2D shapes?', options: ['4', '5', '6', '8'], correctAnswer: 2, explanation: 'Each face maps to one 2D shape in the net.' },
            { type: 'multiple-choice', question: 'A net with 2 triangles and 3 rectangles folds into a...', options: ['Triangular Prism', 'Square Pyramid', 'Triangular Pyramid', 'Rectangular Prism'], correctAnswer: 0, explanation: 'Two triangular ends + three rectangular sides = triangular prism.' },
            { type: 'multiple-choice', question: 'How many valid nets does a cube have?', options: ['1', '6', '11', '24'], correctAnswer: 2, explanation: 'There are exactly 11 unique cube nets.' },
            { type: 'multiple-choice', question: 'A plus (+) shaped net of 6 squares folds into a...', options: ['Pyramid', 'Cylinder', 'Cube', 'Cone'], correctAnswer: 2, explanation: 'The cross/plus shape is one of the standard cube net patterns.' },
            { type: 'multiple-choice', question: 'Which net piece is NOT needed for a cylinder?', options: ['Rectangle', 'Circle', 'Triangle', 'Another Circle'], correctAnswer: 2, explanation: 'A cylinder net needs 1 rectangle + 2 circles. No triangles.' },
            { type: 'multiple-choice', question: 'Unfolding a gift box (cube) would give you...', options: ['6 connected squares', '4 connected squares', '6 separate squares', '8 connected squares'], correctAnswer: 0, explanation: 'An unfolded cube is 6 connected squares in a valid net pattern.', image: '🎁' },
            { type: 'multiple-choice', question: 'A pentagonal prism net has...', options: ['2 pentagons + 5 rectangles', '5 pentagons', '2 squares + 5 triangles', '1 pentagon + 5 triangles'], correctAnswer: 0, explanation: '2 pentagonal ends + 5 rectangular sides for a pentagonal prism.' },
            { type: 'multiple-choice', question: 'In a cube net, opposite faces are...', options: ['Always next to each other', 'Never adjacent', 'Always the same size', 'Both B and C'], correctAnswer: 3, explanation: 'In any cube net, opposite faces never touch AND are always the same size (squares).' },
            { type: 'multiple-choice', question: 'Which statement about nets is TRUE?', options: ['Every shape has exactly 1 net', 'Nets are always square', 'A net folds into a 3D shape', 'Nets cannot have triangles'], correctAnswer: 2, explanation: 'By definition, a net is a 2D pattern that folds into a 3D shape.' },
            { type: 'multiple-choice', question: 'The curved surface of a cylinder unrolls into a...', options: ['Circle', 'Triangle', 'Rectangle', 'Pentagon'], correctAnswer: 2, explanation: 'The curved surface becomes a flat rectangle when unrolled.' },
            { type: 'multiple-choice', question: 'A square pyramid net has a total of how many shapes?', options: ['4', '5', '6', '8'], correctAnswer: 1, explanation: '1 square base + 4 triangular sides = 5 shapes.' },
            { type: 'multiple-choice', question: 'If a net has 3 disconnected pieces, can it form a 3D shape?', options: ['Yes', 'No', 'Only with glue', 'Sometimes'], correctAnswer: 1, explanation: 'A valid net must be one connected piece that folds without gaps.' }
        ]
    },
    {
        id: 'types-of-angles',
        title: 'Types of Angles',
        desc: 'Learn to distinguish between Acute, Right, and Obtuse angles.',
        color: '#dc2626',
        icon: '📐',
        learnSections: [
            {
                heading: 'Right Angles',
                content: 'A right angle is exactly 90 degrees. It looks like the perfect corner of a square, the letter L, or the corner of your screen.',
                example: 'A square or rectangle has exactly 4 right angles.',
            },
            {
                heading: 'Acute and Obtuse Angles',
                content: 'An Acute angle is smaller/sharper than a right angle (less than 90°). An Obtuse angle is wider/larger than a right angle (more than 90°).',
                example: 'Acute = sharp pizza slice. Obtuse = a wide open book lying almost flat.',
            }
        ],
        practice: [
            { type: 'multiple-choice', question: 'What do we call an angle that forms a perfect "L" shape corner?', options: ['Acute Angle', 'Obtuse Angle', 'Right Angle', 'Straight Angle'], correctAnswer: 2, explanation: 'A Right Angle is a perfect 90° corner, just like the letter L.' },
            { type: 'multiple-choice', question: 'Which of the following is an Acute angle?', options: ['A perfect square corner', 'An angle smaller than a right angle', 'An angle larger than a right angle', 'A straight line'], correctAnswer: 1, explanation: 'Acute angles are smaller and sharper than right angles.' },
            { type: 'multiple-choice', question: 'If you open a door just past a right angle, what angle have you made?', options: ['Acute Angle', 'Right Angle', 'Obtuse Angle', 'Narrow Angle'], correctAnswer: 2, explanation: 'Wider than 90° = Obtuse angle.', image: '🚪' },
            { type: 'multiple-choice', question: 'How many right angles does a standard rectangle have?', options: ['0', '2', '4', '8'], correctAnswer: 2, explanation: 'All 4 corners of a rectangle are perfect right angles.' },
            { type: 'multiple-choice', question: 'What time on a clock makes a perfect 90° Right Angle?', options: ['12:00', '3:00', '6:00', '8:00'], correctAnswer: 1, explanation: 'At 3:00, the minute hand at 12 and hour hand at 3 form a 90° angle.', image: '🕒' },
            { type: 'multiple-choice', question: 'The letter V makes what kind of angle at the bottom?', options: ['Acute', 'Right', 'Obtuse', 'Straight'], correctAnswer: 0, explanation: 'The V narrows to a sharp point, smaller than 90°, making it acute.' },
            { type: 'multiple-choice', question: 'A thin slice of pizza has what kind of angle at the tip?', options: ['Right Angle', 'Obtuse Angle', 'Acute Angle', 'Straight Angle'], correctAnswer: 2, explanation: 'A thin slice has a sharp, narrow tip = acute angle.', image: '🍕' },
            { type: 'multiple-choice', question: 'Clock hands at 4:00 — the smaller angle is...', options: ['Acute', 'Right', 'Obtuse', 'Straight'], correctAnswer: 2, explanation: '3:00 is 90°, so 4:00 is wider = Obtuse.', image: '🕓' },
            { type: 'multiple-choice', question: 'The letter L forms what kind of angle?', options: ['Acute', 'Right', 'Obtuse', 'Straight'], correctAnswer: 1, explanation: 'L forms a perfect 90° square corner = Right Angle.' },
            { type: 'multiple-choice', question: 'Can an Obtuse angle eventually become Acute if you squeeze it?', options: ['Yes', 'No', 'Only if you push hard', 'Angles cannot change'], correctAnswer: 0, explanation: 'As you close the arms, an obtuse angle passes through right and becomes acute.' },
            { type: 'multiple-choice', question: 'Look at your open laptop screen at about 120°. What type of angle?', options: ['Acute', 'Right', 'Obtuse', 'Straight'], correctAnswer: 2, explanation: '120° is more than 90°, making it obtuse.', image: '💻' },
            { type: 'multiple-choice', question: 'A corner of a book page is always what angle?', options: ['Acute', 'Right', 'Obtuse', 'Reflex'], correctAnswer: 1, explanation: 'Book pages have square (90°) corners = right angles.', image: '📕' },
            { type: 'multiple-choice', question: 'Clock hands at 2:00 — the angle between them is...', options: ['Acute (60°)', 'Right (90°)', 'Obtuse (120°)', 'Straight (180°)'], correctAnswer: 0, explanation: 'Each hour = 30°. Two hours = 60°, which is less than 90° = acute.', image: '🕑' },
            { type: 'multiple-choice', question: 'How many acute angles does an equilateral triangle have?', options: ['0', '1', '2', '3'], correctAnswer: 3, explanation: 'All 3 angles of an equilateral triangle are 60°, making all 3 acute.' },
            { type: 'multiple-choice', question: 'An angle of exactly 45° is...', options: ['Acute', 'Right', 'Obtuse', 'Straight'], correctAnswer: 0, explanation: '45° is less than 90°, so it is an acute angle.' },
            { type: 'multiple-choice', question: 'An angle of exactly 180° is called...', options: ['Acute', 'Right', 'Obtuse', 'Straight'], correctAnswer: 3, explanation: '180° forms a straight line, called a Straight Angle.' },
            { type: 'multiple-choice', question: 'The hands of a clock at 6:00 form what kind of angle?', options: ['Acute', 'Right', 'Obtuse', 'Straight'], correctAnswer: 3, explanation: 'At 6:00 the hands point in opposite directions = 180° straight angle.', image: '🕕' },
            { type: 'multiple-choice', question: 'A door opened exactly halfway (90°) demonstrates a...', options: ['Acute Angle', 'Right Angle', 'Obtuse Angle', 'Straight Angle'], correctAnswer: 1, explanation: 'A 90° open door forms a right angle with the wall.', image: '🚪' },
            { type: 'multiple-choice', question: 'Which angle is the SMALLEST: 30°, 90°, or 150°?', options: ['30° (Acute)', '90° (Right)', '150° (Obtuse)', 'All are equal'], correctAnswer: 0, explanation: '30° is the smallest — it is an acute angle.' },
            { type: 'multiple-choice', question: 'A right angle plus an acute angle gives you an...', options: ['Acute Angle', 'Right Angle', 'Obtuse Angle', 'Straight Angle'], correctAnswer: 2, explanation: '90° + any positive angle > 90°, which is obtuse.' }
        ],
        assessment: [
            { type: 'multiple-choice', question: 'An angle smaller than a right angle is called...', options: ['Obtuse', 'Straight', 'Acute', 'Right'], correctAnswer: 2, explanation: 'Angles less than 90° are called acute angles.' },
            { type: 'multiple-choice', question: 'A perfect 90° corner is called a...', options: ['Acute Angle', 'Right Angle', 'Obtuse Angle', 'Straight Angle'], correctAnswer: 1, explanation: '90° = Right Angle, like a square corner.' },
            { type: 'multiple-choice', question: 'An angle wider than a right angle is called...', options: ['Obtuse', 'Acute', 'Right', 'Pointy'], correctAnswer: 0, explanation: 'Angles between 90° and 180° are obtuse.' },
            { type: 'multiple-choice', question: 'How many right angles does a square have?', options: ['2', '3', '4', '5'], correctAnswer: 2, explanation: 'All 4 corners of a square are right angles.' },
            { type: 'multiple-choice', question: 'The letter V forms what kind of angle?', options: ['Acute', 'Right', 'Obtuse', 'Straight'], correctAnswer: 0, explanation: 'V narrows to a sharp point = acute.' },
            { type: 'multiple-choice', question: 'What time on a clock forms a right angle?', options: ['6:00', '12:00', '3:00', '4:30'], correctAnswer: 2, explanation: '3:00 = 90° between hour and minute hands.' },
            { type: 'multiple-choice', question: 'A sharp needle tip resembles what angle?', options: ['Acute', 'Right', 'Obtuse', 'Wide'], correctAnswer: 0, explanation: 'Very sharp, narrow point = acute angle.' },
            { type: 'multiple-choice', question: 'A reclining chair opened wide forms what kind of angle?', options: ['Acute', 'Right', 'Obtuse', 'Corner'], correctAnswer: 2, explanation: 'A wide-open recline is greater than 90° = obtuse.' },
            { type: 'multiple-choice', question: 'The letter L represents which angle type?', options: ['Acute', 'Right', 'Obtuse', 'None'], correctAnswer: 1, explanation: 'L has a perfect 90° corner = right angle.' },
            { type: 'multiple-choice', question: 'If an angle is NOT acute and NOT right, it MUST be...', options: ['Sharp', 'Straight', 'Obtuse or Straight', 'Narrow'], correctAnswer: 2, explanation: 'The remaining options above 90° are obtuse (90°-180°) or straight (180°).' },
            { type: 'multiple-choice', question: 'An equilateral triangle has what types of angles?', options: ['All acute', 'All right', 'All obtuse', 'Mixed'], correctAnswer: 0, explanation: 'Each angle is 60°, and 60° < 90° = all acute.' },
            { type: 'multiple-choice', question: 'Clock at 6:00 forms a...', options: ['Right angle', 'Acute angle', 'Straight angle', 'Obtuse angle'], correctAnswer: 2, explanation: 'Hands point in opposite directions = 180° = straight angle.' },
            { type: 'multiple-choice', question: 'An angle of 45° is classified as...', options: ['Acute', 'Right', 'Obtuse', 'Reflex'], correctAnswer: 0, explanation: '45° < 90° = acute.' },
            { type: 'multiple-choice', question: 'How many degrees is a right angle?', options: ['45°', '90°', '120°', '180°'], correctAnswer: 1, explanation: 'By definition, a right angle is exactly 90°.' },
            { type: 'multiple-choice', question: 'A 150° angle is...', options: ['Acute', 'Right', 'Obtuse', 'Straight'], correctAnswer: 2, explanation: '150° is between 90° and 180° = obtuse.' },
            { type: 'multiple-choice', question: 'Two right angles placed together make a...', options: ['Right angle', 'Acute angle', 'Obtuse angle', 'Straight angle'], correctAnswer: 3, explanation: '90° + 90° = 180° = straight angle.' },
            { type: 'multiple-choice', question: 'A clock at 10:10 — the smaller angle is approximately...', options: ['Acute', 'Right', 'Obtuse', 'Straight'], correctAnswer: 0, explanation: 'The hands are close together at ~60° = acute.' },
            { type: 'multiple-choice', question: 'Which shape has only acute angles?', options: ['Square', 'Rectangle', 'Equilateral Triangle', 'Right Triangle'], correctAnswer: 2, explanation: 'An equilateral triangle has three 60° angles, all acute.' },
            { type: 'multiple-choice', question: 'A right angle is also called a...', options: ['Square angle', 'Quarter turn', 'Both A and B', 'Neither'], correctAnswer: 2, explanation: 'A right angle = 90° = quarter of a full turn = also called a square angle.' },
            { type: 'multiple-choice', question: 'Can a triangle have two right angles?', options: ['Yes', 'No', 'Sometimes', 'Only in 3D'], correctAnswer: 1, explanation: 'No — two right angles = 180°, leaving 0° for the third angle, which is impossible.' }
        ]
    },
    {
        id: 'exploring-circles',
        title: 'Exploring Circles',
        desc: 'Understand circle properties like radius, diameter, and center.',
        color: '#be185d',
        icon: '⭕',
        learnSections: [
            {
                heading: 'Center and Radius',
                content: 'The "Center" is the exact middle point of a circle. The "Radius" is the distance from the center straight out to the edge.',
                example: 'Think of a bicycle wheel: the axle is the center, and the metal spokes are the radius lines.',
            },
            {
                heading: 'Diameter',
                content: 'The "Diameter" is a straight line cutting all the way across the entire circle, passing directly through the center point.',
                example: 'Because it goes all the way across, the Diameter is exactly DOUBLE the length of the Radius! (D = 2 × R)',
            }
        ],
        practice: [
            { type: 'multiple-choice', question: 'The distance from the center of a circle to its edge is called the...', options: ['Center', 'Diameter', 'Circumference', 'Radius'], correctAnswer: 3, explanation: 'The Radius is the line from the middle to the edge.', image: '⭕' },
            { type: 'multiple-choice', question: 'The line that goes straight across the circle through the center is called the...', options: ['Radius', 'Edge', 'Diameter', 'Corner'], correctAnswer: 2, explanation: 'The Diameter cuts a circle completely in half.' },
            { type: 'multiple-choice', question: 'If the Radius is 4 cm, what is the Diameter?', options: ['2 cm', '4 cm', '8 cm', '16 cm'], correctAnswer: 2, explanation: 'Diameter = 2 × Radius. 2 × 4 = 8 cm.' },
            { type: 'multiple-choice', question: 'If the Diameter of a pizza is 20 inches, what is the Radius?', options: ['5 inches', '10 inches', '20 inches', '40 inches'], correctAnswer: 1, explanation: 'Radius = Diameter ÷ 2. 20 ÷ 2 = 10 inches.', image: '🍕' },
            { type: 'multiple-choice', question: 'Where is the center of a circle?', options: ['On the edge', 'Outside the circle', 'Exactly in the middle', 'On the radius line'], correctAnswer: 2, explanation: 'The center is the exact middle point of the circle.' },
            { type: 'multiple-choice', question: 'True or False: A circle has 0 straight edges and 0 vertices.', options: ['True', 'False'], correctAnswer: 0, explanation: 'True! A circle is perfectly round with no corners or straight edges.' },
            { type: 'multiple-choice', question: 'Draw many dots all 5 cm away from a center point. What shape forms?', options: ['Square', 'Circle', 'Triangle', 'Line'], correctAnswer: 1, explanation: 'All points equidistant from a center form a circle.' },
            { type: 'multiple-choice', question: 'If Diameter = 12 cm, Radius = ?', options: ['3 cm', '6 cm', '12 cm', '24 cm'], correctAnswer: 1, explanation: 'Radius = 12 ÷ 2 = 6 cm.' },
            { type: 'multiple-choice', question: 'Can you draw a line from edge to edge WITHOUT going through the center?', options: ['Yes, it is called a chord', 'No, impossible', 'Only with a ruler', 'Only if the circle is large'], correctAnswer: 0, explanation: 'A chord is any straight line connecting two points on a circle. Only a diameter passes through the center.' },
            { type: 'multiple-choice', question: 'Two identical circles have the same...', options: ['Color', 'Radius', 'Location', 'Direction'], correctAnswer: 1, explanation: 'Identical circles have the same radius (and therefore the same diameter).' },
            { type: 'multiple-choice', question: 'A bicycle wheel is an example of a circle. The axle is the...', options: ['Diameter', 'Radius', 'Center', 'Edge'], correctAnswer: 2, explanation: 'The axle sits at the very center of the wheel.', image: '🚲' },
            { type: 'multiple-choice', question: 'Each spoke of a bicycle wheel represents a...', options: ['Diameter', 'Radius', 'Chord', 'Center'], correctAnswer: 1, explanation: 'Spokes go from the center (axle) to the edge (rim) = radius.', image: '🚲' },
            { type: 'multiple-choice', question: 'If R = 7 cm, D = ?', options: ['3.5 cm', '7 cm', '14 cm', '21 cm'], correctAnswer: 2, explanation: 'D = 2 × R = 2 × 7 = 14 cm.' },
            { type: 'multiple-choice', question: 'If D = 30 cm, R = ?', options: ['10 cm', '15 cm', '30 cm', '60 cm'], correctAnswer: 1, explanation: 'R = D ÷ 2 = 30 ÷ 2 = 15 cm.' },
            { type: 'multiple-choice', question: 'Which is always longer: the radius or the diameter?', options: ['Radius', 'Diameter', 'They are equal', 'Depends on the circle'], correctAnswer: 1, explanation: 'The diameter is always twice the radius, so always longer.' },
            { type: 'multiple-choice', question: 'The outer boundary of a circle is called the...', options: ['Radius', 'Diameter', 'Circumference', 'Center'], correctAnswer: 2, explanation: 'The circumference is the distance around the outside of a circle.' },
            { type: 'multiple-choice', question: 'How many diameters can you draw in a circle?', options: ['1', '2', '4', 'Infinite'], correctAnswer: 3, explanation: 'You can draw unlimited diameters — every line through the center counts!' },
            { type: 'multiple-choice', question: 'A clock face is circular. The minute hand acts like a...', options: ['Diameter', 'Radius', 'Chord', 'Circumference'], correctAnswer: 1, explanation: 'The minute hand goes from the center to the edge = radius.', image: '🕐' },
            { type: 'multiple-choice', question: 'If one circle has R = 5 and another has R = 10, which is bigger?', options: ['First circle', 'Second circle', 'Both are the same', 'Cannot tell'], correctAnswer: 1, explanation: 'Larger radius = larger circle. R=10 > R=5.' },
            { type: 'multiple-choice', question: 'A chord that passes through the center of a circle is called a...', options: ['Radius', 'Diameter', 'Arc', 'Segment'], correctAnswer: 1, explanation: 'A diameter is the special chord that goes through the center.' }
        ],
        assessment: [
            { type: 'multiple-choice', question: 'The line from the center to the edge of a circle is called the...', options: ['Diameter', 'Radius', 'Center', 'Circumference'], correctAnswer: 1, explanation: 'Radius = center to edge.' },
            { type: 'multiple-choice', question: 'The line across the entire circle through the center is called the...', options: ['Radius', 'Diameter', 'Edge', 'Corner'], correctAnswer: 1, explanation: 'Diameter passes through the center, edge to edge.' },
            { type: 'multiple-choice', question: 'If radius is 6 cm, what is the diameter?', options: ['3 cm', '6 cm', '12 cm', '18 cm'], correctAnswer: 2, explanation: 'D = 2 × R = 2 × 6 = 12 cm.' },
            { type: 'multiple-choice', question: 'If diameter is 18 cm, what is the radius?', options: ['6 cm', '9 cm', '18 cm', '36 cm'], correctAnswer: 1, explanation: 'R = D ÷ 2 = 18 ÷ 2 = 9 cm.' },
            { type: 'multiple-choice', question: 'What is the relationship between R and D?', options: ['R is double D', 'D is double R', 'D and R are equal', 'D is triple R'], correctAnswer: 1, explanation: 'Diameter = 2 × Radius.' },
            { type: 'multiple-choice', question: 'How many straight edges does a circle have?', options: ['0', '1', '2', 'Infinite'], correctAnswer: 0, explanation: 'A circle has no straight edges — only a curved boundary.' },
            { type: 'multiple-choice', question: 'How many corners (vertices) does a circle have?', options: ['4', '1', '0', 'Infinite'], correctAnswer: 2, explanation: 'A circle has zero corners or vertices.' },
            { type: 'multiple-choice', question: 'The exact middle point of a circle is called its...', options: ['Edge', 'Center', 'Corner', 'Radius'], correctAnswer: 1, explanation: 'The center is the middle point equidistant from all edge points.' },
            { type: 'multiple-choice', question: 'If R = 15, D = ?', options: ['7.5', '15', '30', '45'], correctAnswer: 2, explanation: 'D = 2 × 15 = 30.' },
            { type: 'multiple-choice', question: 'If D = 50, R = ?', options: ['10', '25', '50', '100'], correctAnswer: 1, explanation: 'R = 50 ÷ 2 = 25.' },
            { type: 'multiple-choice', question: 'The boundary/perimeter of a circle is called the...', options: ['Diameter', 'Radius', 'Circumference', 'Area'], correctAnswer: 2, explanation: 'Circumference is the distance around the circle.' },
            { type: 'multiple-choice', question: 'A chord is a line segment that...', options: ['Goes from center to edge', 'Connects two points on the circle', 'Goes around the circle', 'Is always the diameter'], correctAnswer: 1, explanation: 'A chord connects any two points on the circle\'s edge.' },
            { type: 'multiple-choice', question: 'How many radii can you draw in a circle?', options: ['1', '2', '4', 'Infinite'], correctAnswer: 3, explanation: 'You can draw infinite radii from the center to any edge point.' },
            { type: 'multiple-choice', question: 'Which is longer: a chord or the diameter?', options: ['Chord is always longer', 'Diameter is always longer or equal', 'They are always equal', 'Cannot compare'], correctAnswer: 1, explanation: 'The diameter is the longest possible chord in a circle.' },
            { type: 'multiple-choice', question: 'If R = 0, what do you have?', options: ['A circle', 'A point', 'A line', 'Nothing'], correctAnswer: 1, explanation: 'A circle with radius 0 is just a single point (the center).' },
            { type: 'multiple-choice', question: 'A wheel with a diameter of 1 meter has a radius of...', options: ['25 cm', '50 cm', '100 cm', '200 cm'], correctAnswer: 1, explanation: 'R = 100 cm ÷ 2 = 50 cm.', image: '🛞' },
            { type: 'multiple-choice', question: 'Two circles with the same center but different radii are called...', options: ['Identical', 'Concentric', 'Parallel', 'Perpendicular'], correctAnswer: 1, explanation: 'Concentric circles share the same center point.' },
            { type: 'multiple-choice', question: 'If you double the radius, the diameter becomes...', options: ['Same', 'Doubled', 'Tripled', 'Halved'], correctAnswer: 1, explanation: 'D = 2R. If R doubles, D also doubles.' },
            { type: 'multiple-choice', question: 'A semicircle is...', options: ['A full circle', 'Half a circle', 'Quarter of a circle', 'Two circles'], correctAnswer: 1, explanation: '"Semi" means half. A semicircle is exactly half of a circle.' },
            { type: 'multiple-choice', question: 'The longest chord in any circle is always the...', options: ['Radius', 'Arc', 'Diameter', 'Circumference'], correctAnswer: 2, explanation: 'The diameter is the longest possible straight line across a circle.' }
        ]
    }
];
