export const TERMS = [
    { name: 'Evaporation', def: 'The process where liquid water turns into water vapour (gas) when heated by the sun. It happens at any temperature but faster when it\'s hot.', icon: '☀️', color: '#f59e0b', examples: ['Puddles drying up on a hot day', 'Wet clothes drying on a clothesline', 'Water disappearing from a bowl left in the sun'], inUse: 'Evaporation is the first step of the water cycle — it lifts water from Earth to the sky.', memory: '"Eva-pour-away" — water pours away into the air as invisible vapour!' },
    { name: 'Condensation', def: 'The process where water vapour (gas) cools down and turns back into tiny liquid water droplets. This is how clouds and fog form.', icon: '💧', color: '#0ea5e9', examples: ['Water drops on a cold glass of juice', 'Fog forming on a bathroom mirror after a shower', 'Morning dew on grass'], inUse: 'Condensation creates clouds in the sky — billions of tiny water droplets grouped together.', memory: '"Con-DENSE" — vapour gets DENSE (thick) and turns into visible drops!' },
    { name: 'Precipitation', def: 'Water falling from clouds back to Earth in the form of rain, snow, sleet, or hail. It happens when cloud droplets get too heavy.', icon: '🌧️', color: '#6366f1', examples: ['Rain during monsoon season', 'Snowfall in the Himalayas', 'Hailstones during a storm'], inUse: 'Precipitation returns water from the sky to the Earth, completing the water cycle.', memory: '"Pre-SIP-itation" — water pre-sips its way down from clouds for us to drink!' },
    { name: 'Water Cycle', def: 'The continuous journey of water between the Earth and atmosphere. Water evaporates, forms clouds, falls as rain, and flows back — repeating forever.', icon: '🔄', color: '#10b981', examples: ['Sun heats ocean → water rises → clouds form → rain falls → rivers flow → back to ocean', 'The same water has been recycling for billions of years!'], inUse: 'The water cycle ensures we never "run out" of water — nature recycles it endlessly.', memory: 'Water goes round and round like a merry-go-round — it never stops!' },
    { name: 'Groundwater', def: 'Water that seeps through soil and collects deep underground in spaces between rocks and sand layers.', icon: '🕳️', color: '#8b5cf6', examples: ['Water from wells and borewells', 'Springs that bubble up from underground', 'Handpump water comes from underground'], inUse: 'Groundwater is our hidden treasure — many villages and cities depend on it for drinking water.', memory: 'Water hiding under the GROUND, like a buried treasure waiting to be pumped up!' },
    { name: 'Freshwater', def: 'Water with very low salt content that is safe for drinking, cooking, and farming. Only about 3% of all Earth\'s water is freshwater.', icon: '🚰', color: '#0d9488', examples: ['River water (Ganga, Yamuna)', 'Lake water (Dal Lake)', 'Rainwater', 'Groundwater from wells'], inUse: 'Freshwater is precious — if all Earth\'s water fit in a glass, freshwater would be just one teaspoon!', memory: '"FRESH" enough to drink — not salty like the ocean!' },
    { name: 'Aquifer', def: 'An underground layer of porous rock, sand, or gravel that can hold and carry large amounts of groundwater.', icon: '🪨', color: '#475569', examples: ['The Indo-Gangetic aquifer supplies water to millions in North India', 'Desert oases are fed by hidden aquifers'], inUse: 'Aquifers are nature\'s underground water tanks — they store water for thousands of years.', memory: '"AQUA" (water) + "FER" (carry) — rocks that CARRY water underground!' },
    { name: 'Adaptation', def: 'A special body feature or behaviour that helps a living thing survive in its environment.', icon: '🦆', color: '#ec4899', examples: ['Fish have gills to breathe underwater', 'Ducks have webbed feet to swim', 'Water lily leaves float because of waxy coating'], inUse: 'Every creature has unique adaptations — they\'re nature\'s survival toolkit!', memory: 'Animals ADAPT (adjust) to their home — like choosing the right outfit for the weather!' },
    { name: 'Food Chain', def: 'A sequence showing how energy passes from one living thing to another through eating. Each link depends on the previous one.', icon: '🔗', color: '#ef4444', examples: ['Algae → Small fish → Big fish → Eagle', 'Grass → Grasshopper → Frog → Snake → Eagle'], inUse: 'Food chains show that every living thing is connected — if one disappears, the whole chain suffers.', memory: 'A CHAIN of who eats whom — break one link and everything falls apart!' },
    { name: 'Conservation', def: 'The careful use and protection of natural resources like water, forests, and wildlife to prevent waste and destruction.', icon: '💚', color: '#059669', examples: ['Turning off taps when not in use', 'Rainwater harvesting', 'Protecting rivers from pollution', 'Planting trees to help groundwater recharge'], inUse: 'Conservation is everyone\'s responsibility — small actions today save water for tomorrow!', memory: '"CON-SERVE" — to SERVE and protect our planet\'s water for the future!' }
];

export const COOL_FACTS = [
    { num: 1, title: 'The Great Water Illusion', emoji: '🌍', color: '#0ea5e9', rule: '97% of Earth\'s water is salty ocean water that we cannot drink!', detail: 'Even though our planet looks blue from space with water everywhere, only about 3% is freshwater. And most of that freshwater is locked in glaciers and ice caps! The water we can actually use (from rivers, lakes, and underground) is less than 1% of all water on Earth.', examples: ['Earth has about 1.4 billion km³ of water', 'Only 0.5% is available freshwater', 'If all water fit in a glass, drinkable water = one teaspoon'], tip: 'Next time you see a large glass of water, imagine only one teaspoon of it is drinkable — that\'s how precious freshwater is!' },
    { num: 2, title: 'Water is Ancient!', emoji: '🦕', color: '#8b5cf6', rule: 'The water you drink today is the same water that dinosaurs drank 65 million years ago!', detail: 'Water on Earth has been recycled through the water cycle for billions of years. No new water is created — it just keeps moving between oceans, clouds, rivers, ice, and underground. So the water in your glass may have once been in a prehistoric ocean!', examples: ['Water cycle has been running for 4 billion+ years', 'Every drop has been recycled millions of times', 'Rain today = ancient ocean water evaporated'], tip: 'Think about this: the next time you drink water, you might be sipping the same molecules a T-Rex once drank!' },
    { num: 3, title: 'Cities vs Forests', emoji: '🏙️', color: '#10b981', rule: 'Concrete cities block rainwater from reaching underground, but forests let water seep in naturally!', detail: 'In cities, roads and buildings are covered with concrete and tar. When it rains, water runs off the surface into drains instead of seeping into the ground. In forests, soft soil and tree roots absorb rainwater like a sponge, refilling underground water supplies.', examples: ['Forest soil absorbs 10x more water than concrete', 'Trees roots create channels for water to seep down', 'Cities face water shortages because groundwater isn\'t refilled'], tip: 'This is why planting trees and having parks in cities is so important — they help recharge groundwater!' },
    { num: 4, title: 'Fish Breathe Water!', emoji: '🐟', color: '#f59e0b', rule: 'Fish don\'t actually breathe water — they extract dissolved oxygen FROM water using their gills!', detail: 'Water contains dissolved oxygen (just like sugar dissolves in water). Fish take in water through their mouths, pass it over their gills which have thin blood vessels, and these gills absorb the oxygen. The water then flows out — it\'s like breathing, but through water instead of air!', examples: ['Fish gills have thousands of tiny blood vessels', 'Warm water holds less oxygen than cold water', 'Fish can "drown" if there\'s not enough oxygen in water'], tip: 'Next time you see a fish opening and closing its mouth, it\'s not talking — it\'s breathing!' },
    { num: 5, title: 'Rivers of India', emoji: '🗺️', color: '#ec4899', rule: 'Indian rivers flow either east to the Bay of Bengal or west to the Arabian Sea — geography decides!', detail: 'The Western Ghats mountains act as a water divide. Rivers like the Ganga, Yamuna, Brahmaputra, and Godavari flow eastward to the Bay of Bengal. Rivers like the Narmada and Tapi flow westward to the Arabian Sea. The direction depends on the slope of the land!', examples: ['To Bay of Bengal: Ganga, Yamuna, Brahmaputra, Godavari', 'To Arabian Sea: Narmada, Tapi, Periyar', 'Western Ghats create the east-west divide'], tip: 'Look at a map of India and trace the rivers — can you see how mountains decide which way they flow?' }
];

export const VOCAB_QUIZ = [
    { question: 'What is the process of liquid water turning into water vapour called?', options: ['Condensation', 'Evaporation', 'Precipitation', 'Seepage'], correct: 1, explanation: 'Evaporation is the process where liquid water changes to water vapour (gas) due to heat from the sun.' },
    { question: 'What falls from clouds as rain, snow, or hail?', options: ['Evaporation', 'Condensation', 'Precipitation', 'Transpiration'], correct: 2, explanation: 'Precipitation is water falling from clouds to Earth in any form — rain, snow, sleet, or hail.' },
    { question: 'What special organ do fish use to breathe underwater?', options: ['Lungs', 'Gills', 'Fins', 'Scales'], correct: 1, explanation: 'Fish use gills to extract dissolved oxygen from water — gills work like underwater lungs!' },
    { question: 'What is an underground layer of rock that stores water called?', options: ['Aquifer', 'Glacier', 'Canyon', 'Ecosystem'], correct: 0, explanation: 'An aquifer is a layer of porous rock underground that holds and carries groundwater.' },
    { question: 'What do we call the careful use and protection of natural resources?', options: ['Pollution', 'Consumption', 'Conservation', 'Evaporation'], correct: 2, explanation: 'Conservation means using natural resources carefully and protecting them for the future.' }
];
