export const TERMS = [
    {
        name: 'Complex Number',
        color: '#6366f1',
        icon: '🔮',
        def: 'A number of the form $z = a + ib$ where $a, b \\in \\mathbb{R}$ and $i = \\sqrt{-1}$. Every real number is a complex number with $b = 0$.',
        examples: ['$z = 3 + 5i$', '$z = -1 + i\\sqrt{3}$', '$z = 2 + 0i = 2$ (real)', '$z = 0 + 4i = 4i$ (purely imaginary)'],
        inUse: 'We use the letter $z$ for a complex number and write it as $z = a + ib$.',
        memory: 'Think of a complex number as a pair of coordinates: one real, one imaginary — like a map address for the number plane.',
    },
    {
        name: 'Imaginary Unit (i)',
        color: '#0d9488',
        icon: '🔵',
        def: 'The symbol $i$ denotes $\\sqrt{-1}$, satisfying $i^2 = -1$. By convention, $\\sqrt{-a} = i\\sqrt{a}$ for $a > 0$.',
        examples: ['$i^1 = i$', '$i^2 = -1$', '$i^3 = -i$', '$i^4 = 1$'],
        inUse: 'Convert first: $\\sqrt{-9} = i\\sqrt{9} = 3i$. Never leave $\\sqrt{\\text{negative}}$ unconverted.',
        memory: 'The powers of $i$ cycle every 4 steps: i, −1, −i, 1. Memorise this cycle!',
    },
    {
        name: 'Real & Imaginary Parts',
        color: '#f59e0b',
        icon: '↔️',
        def: 'For $z = a + ib$: $\\text{Re}(z) = a$ is the real part and $\\text{Im}(z) = b$ is the imaginary part — a real number, not $ib$.',
        examples: ['$z = 4 - 3i \\Rightarrow \\text{Re}(z) = 4,\\;\\text{Im}(z) = -3$', '$z = 7i \\Rightarrow \\text{Re}(z) = 0,\\;\\text{Im}(z) = 7$'],
        inUse: '$\\text{Im}(z) = b$, NOT $ib$. The imaginary part is always a real number.',
        memory: 'Split the number at the $+$ sign: left of $i$ is real, the coefficient of $i$ is imaginary.',
    },
    {
        name: 'Conjugate (z̄)',
        color: '#ec4899',
        icon: '🪞',
        def: 'The conjugate of $z = a + ib$ is $\\bar{z} = a - ib$. Geometrically it is the reflection of $z$ in the real axis of the Argand plane.',
        examples: ['$z = 3 + 4i \\Rightarrow \\bar{z} = 3 - 4i$', '$z \\cdot \\bar{z} = a^2 + b^2 = |z|^2$'],
        inUse: 'To rationalise: multiply numerator and denominator by the conjugate of the denominator.',
        memory: 'A conjugate is the "mirror image" — flip the sign of the imaginary part only.',
    },
    {
        name: 'Modulus (|z|)',
        color: '#7c3aed',
        icon: '📏',
        def: 'The modulus of $z = a + ib$ is $|z| = \\sqrt{a^2 + b^2}$. It equals the distance from the origin to the point $(a, b)$ in the Argand plane.',
        examples: ['$|3 + 4i| = \\sqrt{9+16} = 5$', '$|z_1 z_2| = |z_1||z_2|$', '$|\\bar{z}| = |z|$'],
        inUse: '$|z|^2 = z \\cdot \\bar{z}$ — use this shortcut when computing inverses.',
        memory: 'Modulus = distance from origin. It is always a non-negative real number.',
    },
    {
        name: 'Argand Plane',
        color: '#3b82f6',
        icon: '🗺️',
        def: 'A coordinate plane where the complex number $a + ib$ is plotted as the point $(a, b)$. The $x$-axis is the real axis and the $y$-axis is the imaginary axis.',
        examples: ['$2 + 3i \\to$ point $(2,\\,3)$', '$\\bar{z}$ is the mirror image of $z$ across the real axis'],
        inUse: 'Every complex number corresponds to a unique point on the Argand plane.',
        memory: 'Think of the Argand plane as the ordinary $xy$-plane relabelled: $x$ is real, $y$ is imaginary.',
    },
    {
        name: 'Multiplicative Inverse (z⁻¹)',
        color: '#10b981',
        icon: '⁻¹',
        def: 'For non-zero $z = a + ib$, $z^{-1} = \\dfrac{\\bar{z}}{|z|^2} = \\dfrac{a - ib}{a^2 + b^2}$.',
        examples: ['$z = 2 - 3i \\Rightarrow z^{-1} = \\frac{2+3i}{13}$', '$z \\cdot z^{-1} = 1$'],
        inUse: 'Always: $z^{-1} = \\bar{z} / |z|^2$. Never just $\\bar{z}$.',
        memory: 'Invert = conjugate ÷ modulus-squared. Conjugate over square of modulus.',
    },
];

export const FIVE_RULES = [
    {
        num: 1,
        title: 'The i-Cycle',
        rule: 'Powers of $i$ cycle with period 4: $i^1=i,\\;i^2=-1,\\;i^3=-i,\\;i^4=1$.',
        emoji: '⚡',
        color: '#6366f1',
        detail: 'For any integer $n$, divide $n$ by 4 and use the remainder: remainder 0 → 1, remainder 1 → $i$, remainder 2 → $-1$, remainder 3 → $-i$. Works for negative powers too.',
        examples: ['$i^{18} = i^{4\\times4+2} = i^2 = -1$', '$i^{-1} = i^3 = -i$'],
        tip: 'Divide the exponent by 4 — the remainder tells you everything. No need to expand step by step.',
    },
    {
        num: 2,
        title: 'Equality Rule',
        rule: 'Two complex numbers are equal iff their real parts are equal AND their imaginary parts are equal.',
        emoji: '⚖️',
        color: '#0d9488',
        detail: '$a + ib = c + id \\Leftrightarrow a = c$ and $b = d$. This converts one complex equation into two real equations. There is NO ordering in $\\mathbb{C}$ — never write $z_1 > z_2$.',
        examples: ['$x + iy = 3 - 5i \\Rightarrow x = 3,\\;y = -5$', '$3+5i > 2+4i$ is meaningless'],
        tip: 'Always separate a complex equation into real and imaginary parts — you get two equations for the price of one.',
    },
    {
        num: 3,
        title: 'Square Root Warning',
        rule: '$\\sqrt{a} \\times \\sqrt{b} = \\sqrt{ab}$ holds ONLY when at least one of $a, b$ is non-negative.',
        emoji: '⚠️',
        color: '#ef4444',
        detail: 'For $a, b < 0$: $\\sqrt{-2} \\times \\sqrt{-3} \\neq \\sqrt{6}$. Convert to $i$-form first: $(i\\sqrt{2})(i\\sqrt{3}) = i^2\\sqrt{6} = -\\sqrt{6}$.',
        examples: ['$\\sqrt{-4} \\times \\sqrt{-9} = (2i)(3i) = 6i^2 = -6$', 'NOT $\\sqrt{36} = 6$'],
        tip: 'Whenever you see $\\sqrt{\\text{negative}}$, convert to $i$-form immediately before multiplying.',
    },
    {
        num: 4,
        title: 'Conjugate–Modulus Link',
        rule: '$z \\cdot \\bar{z} = |z|^2$. Use this to rationalise denominators and find inverses.',
        emoji: '🔗',
        color: '#7c3aed',
        detail: 'Multiplying $z$ by its conjugate eliminates the imaginary part: $(a+ib)(a-ib) = a^2+b^2$. This is the key technique for division: multiply top and bottom by the conjugate of the denominator.',
        examples: ['$z^{-1} = \\bar{z} / |z|^2$', '$\\dfrac{1}{3+4i} = \\dfrac{3-4i}{25}$'],
        tip: 'Division of complex numbers = multiply by conjugate of denominator. Always.',
    },
    {
        num: 5,
        title: 'Algebra Identities Transfer',
        rule: 'All standard algebraic identities hold for complex numbers exactly as for reals.',
        emoji: '🧮',
        color: '#f59e0b',
        detail: '$(z_1+z_2)^2 = z_1^2 + 2z_1z_2 + z_2^2$, $(z_1-z_2)^2 = z_1^2 - 2z_1z_2 + z_2^2$, $z_1^2 - z_2^2 = (z_1+z_2)(z_1-z_2)$ — all apply in $\\mathbb{C}$.',
        examples: ['$(1+i)^2 = 1 + 2i + i^2 = 2i$', '$(3+i)(3-i) = 9 - i^2 = 10$'],
        tip: 'Treat $i$ like a variable in algebra — but always replace $i^2$ with $-1$ at the end.',
    },
];

export const VOCAB_QUIZ = [
    {
        question: 'What is the imaginary part of $z = 5 - 3i$?',
        options: ['$5$', '$-3i$', '$-3$', '$3$'],
        correct: 2,
        explanation: '$\\text{Im}(z)$ is the coefficient of $i$, which is $-3$ — a real number, not $-3i$.',
    },
    {
        question: 'What is the value of $i^{47}$?',
        options: ['$1$', '$i$', '$-1$', '$-i$'],
        correct: 3,
        explanation: '$47 = 4 \\times 11 + 3$, so $i^{47} = i^3 = -i$.',
    },
    {
        question: 'The conjugate of $z = 2 - 7i$ is:',
        options: ['$-2 + 7i$', '$2 + 7i$', '$7 + 2i$', '$-2 - 7i$'],
        correct: 1,
        explanation: 'The conjugate flips only the imaginary sign: $\\bar{z} = 2 + 7i$.',
    },
    {
        question: 'Find $|3 + 4i|$.',
        options: ['$7$', '$\\sqrt{7}$', '$5$', '$25$'],
        correct: 2,
        explanation: '$|3+4i| = \\sqrt{3^2 + 4^2} = \\sqrt{25} = 5$.',
    },
    {
        question: 'Which statement about complex numbers is TRUE?',
        options: ['$3+2i > 1+i$', '$\\sqrt{-4}\\times\\sqrt{-9} = 6$', '$|z_1 z_2| = |z_1||z_2|$', '$z + \\bar{z} = 2i\\,\\text{Im}(z)$'],
        correct: 2,
        explanation: '$|z_1 z_2| = |z_1||z_2|$ is a valid modulus property. Ordering ($>$) doesn\'t apply in $\\mathbb{C}$; $\\sqrt{-4}\\times\\sqrt{-9} = -6$ (not $6$); and $z+\\bar{z} = 2\\,\\text{Re}(z)$.',
    },
];
