export const complexIntroData = {
    prerequisites: [
        {
            icon: '🔢',
            title: 'Real Numbers',
            desc: 'Familiarity with integers, rationals, and irrationals — the number line.',
        },
        {
            icon: '📐',
            title: 'Quadratic Equations',
            desc: 'Solving ax² + bx + c = 0 and understanding the discriminant D = b² − 4ac.',
        },
        {
            icon: '🧮',
            title: 'Basic Algebra',
            desc: 'Expanding brackets, algebraic identities like (a+b)² and (a−b)(a+b).',
        },
    ],
    cards5W1H: [
        {
            q: 'WHAT',
            label: 'What is a Complex Number?',
            icon: '🔮',
            gradFrom: '#6366f1',
            gradTo: '#8b5cf6',
            shadow: 'rgba(99,102,241,0.25)',
            content: 'A complex number is a number of the form a + ib, where a and b are real numbers and i = √(−1). Here a is the real part (Re z) and b is the imaginary part (Im z). For example, z = 3 + 5i has Re z = 3 and Im z = 5.',
            fact: 'The set of all complex numbers is denoted ℂ. Every real number is a complex number with imaginary part 0.',
        },
        {
            q: 'WHY',
            label: 'Why study Complex Numbers?',
            icon: '💡',
            gradFrom: '#f59e0b',
            gradTo: '#f97316',
            shadow: 'rgba(245,158,11,0.25)',
            content: 'The equation x² + 1 = 0 has no real solution — no real number squared gives −1. Complex numbers extend the real number system so that every quadratic (and in fact every polynomial) has solutions. They are also fundamental in electrical engineering, quantum mechanics, and signal processing.',
            fact: 'Euler\'s formula e^(iπ) + 1 = 0 — considered the most beautiful equation in mathematics — uses complex numbers.',
        },
        {
            q: 'WHO',
            label: 'Who discovered Complex Numbers?',
            icon: '🧑‍🔬',
            gradFrom: '#0d9488',
            gradTo: '#06b6d4',
            shadow: 'rgba(13,148,136,0.25)',
            content: 'Gerolamo Cardano (1545) encountered square roots of negatives while solving cubics. Rafael Bombelli gave rules for working with them. Euler introduced the symbol i for √(−1). W. R. Hamilton (1830) gave complex numbers a rigorous definition as ordered pairs (a, b) of reals.',
            fact: 'Indian mathematician Mahavira (850 CE) first clearly stated that a negative number has no square root in the real number system.',
        },
        {
            q: 'WHERE',
            label: 'Where are Complex Numbers used?',
            icon: '🌐',
            gradFrom: '#ec4899',
            gradTo: '#f43f5e',
            shadow: 'rgba(236,72,153,0.25)',
            content: 'Complex numbers appear in AC circuit analysis (impedance), Fourier transforms (audio/image processing), quantum mechanics (wave functions), control systems, fractals (Mandelbrot set), and computer graphics (rotations in 2D).',
            fact: 'Every time you stream music or video, Fourier analysis — built on complex numbers — is working behind the scenes.',
        },
        {
            q: 'WHEN',
            label: 'When should I use which form?',
            icon: '⏱️',
            gradFrom: '#7c3aed',
            gradTo: '#6366f1',
            shadow: 'rgba(124,58,237,0.25)',
            content: 'Use a + ib (Cartesian form) for addition, subtraction, and finding real/imaginary parts. Use r(cos θ + i sin θ) (polar form) for multiplication, division, and finding powers. The Argand plane gives you a geometric view of any complex number.',
            fact: 'De Moivre\'s theorem (zⁿ = rⁿ(cos nθ + i sin nθ)) is the bridge between polar form and powers — covered in higher classes.',
        },
        {
            q: 'HOW',
            label: 'How do we visualise Complex Numbers?',
            icon: '📊',
            gradFrom: '#10b981',
            gradTo: '#34d399',
            shadow: 'rgba(16,185,129,0.25)',
            content: 'Each complex number z = a + ib corresponds to the point P(a, b) in the Argand plane. The x-axis is the real axis and the y-axis is the imaginary axis. The modulus |z| = √(a² + b²) is the distance from the origin to P, and the conjugate z̄ = a − ib is its mirror image across the real axis.',
            fact: 'The Argand plane is named after Jean-Robert Argand (1806), though Caspar Wessel described it first in 1797.',
        },
    ],
};
