export const generateTheCellSkillsData = () => {
    return [
        {
            id: 'cell-theory-basics',
            title: 'Cell Theory & Basics',
            desc: 'Understand the foundation of biology: Cell Theory, and cell types.',
            color: '#059669',
            icon: '🔬',
            learnSections: [
                {
                    heading: 'The Cell Theory',
                    content: 'Proposed by Schleiden and Schwann. Later, Rudolf Virchow added "Omnis cellula-e cellula" (All cells arise from pre-existing cells).',
                    example: 'Virchow modified the hypothesis to give the cell theory a final shape in 1855.',
                },
                {
                    heading: 'Prokaryotes vs Eukaryotes',
                    content: 'Prokaryotes lack a membrane-bound nucleus and organelles (e.g. Bacteria, Mycoplasma). Eukaryotes have compartmentalized organelles and a true nucleus.',
                    example: 'Mycoplasma are the smallest living cells known and lack a cell wall completely!',
                }
            ],
            practice: [
                { type: 'multiple-choice', question: 'Who formulated the first cell theory?', options: ['Schleiden and Schwann', 'Anton Van Leeuwenhoek', 'Robert Hooke', 'Rudolf Virchow'], correctAnswer: 0, explanation: 'Matthias Schleiden (Botanist) and Theodore Schwann (Zoologist) together formulated the cell theory.' },
                { type: 'multiple-choice', question: '"Omnis cellula-e cellula" means:', options: ['All cells have a nucleus', 'All cells arise from pre-existing cells', 'Cells are the fundamental unit of life', 'Cells contain DNA'], correctAnswer: 1, explanation: 'Rudolf Virchow stated this in 1855.' },
                { type: 'multiple-choice', question: 'Which of the following lacks a cell wall?', options: ['Mycoplasma', 'Bacteria', 'Fungi', 'Blue-green algae'], correctAnswer: 0, explanation: 'Mycoplasma are the smallest living cells and completely lack a cell wall.' },
                { type: 'multiple-choice', question: 'Prokaryotic cells have which type of ribosome?', options: ['70S', '80S', '90S', '100S'], correctAnswer: 0, explanation: 'Prokaryotes have 70S ribosomes (50S + 30S subunits).' },
                { type: 'multiple-choice', question: 'What is the main function of the plasma membrane?', options: ['Protein synthesis', 'Selective permeability', 'Energy production', 'Lipid synthesis'], correctAnswer: 1, explanation: 'The cell membrane is selectively permeable, controlling transport of molecules.' },
                { type: 'multiple-choice', question: 'Who first saw and described a live cell?', options: ['Robert Hooke', 'Rudolf Virchow', 'Anton Van Leeuwenhoek', 'Schleiden'], correctAnswer: 2, explanation: 'Anton Van Leeuwenhoek first saw and described a live cell.' },
                { type: 'multiple-choice', question: 'The fluid mosaic model of the plasma membrane was proposed by:', options: ['Singer and Nicolson', 'Schleiden and Schwann', 'Camillo Golgi', 'Robert Brown'], correctAnswer: 0, explanation: 'Proposed in 1972 by Singer and Nicolson.' },
                { type: 'multiple-choice', question: 'Which structure is unique to plant cells but absent in animal cells?', options: ['Mitochondria', 'Cell Wall', 'Nucleoplasm', 'Ribosomes'], correctAnswer: 1, explanation: 'Plant cells have a rigid cell wall, which animal cells lack.' },
                { type: 'multiple-choice', question: 'A specialised differentiated form of cell membrane in prokaryotes is called:', options: ['Mesosome', 'Lysosome', 'Nucleoid', 'Plasmid'], correctAnswer: 0, explanation: 'Mesosomes are infoldings of the cell membrane in prokaryotes.' },
                { type: 'multiple-choice', question: 'The main chemical component of a fungal cell wall is:', options: ['Cellulose', 'Chitin', 'Peptidoglycan', 'Pectin'], correctAnswer: 1, explanation: 'Fungal cell walls are mainly composed of chitin.' },
                { type: 'multiple-choice', question: 'Which of these is NOT a eukaryote?', options: ['Protists', 'Fungi', 'Plants', 'Bacteria'], correctAnswer: 3, explanation: 'Bacteria are prokaryotes (Monera).' },
                { type: 'multiple-choice', question: 'Plasmids in bacteria carry genes for:', options: ['Photosynthesis', 'Respiration', 'Antibiotic resistance', 'Protein folding'], correctAnswer: 2, explanation: 'Plasmids are extrachromosomal DNA often conferring traits like antibiotic resistance.' },
                { type: 'multiple-choice', question: 'The quasi-fluid nature of lipids enables:', options: ['Rigidity', 'Lateral movement of proteins', 'Active transport', 'Osmosis'], correctAnswer: 1, explanation: 'The fluid mosaic model explains that the quasi-fluid lipid layer allows lateral protein movement.' },
                { type: 'multiple-choice', question: 'Which organelle is non-membrane bound and found in ALL cells?', options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Vacuole'], correctAnswer: 2, explanation: 'Ribosomes are found in both prokaryotes and eukaryotes and lack a membrane.' },
                { type: 'multiple-choice', question: 'Active transport across a cell membrane requires:', options: ['No energy', 'ATP', 'Only a concentration gradient', 'Osmosis'], correctAnswer: 1, explanation: 'Active transport acts against the concentration gradient and requires ATP energy.' },
            ],
            assessment: [
                { type: 'multiple-choice', question: 'Which of the following are exceptions to the cell theory?', options: ['Bacteria', 'Fungi', 'Viruses', 'Algae'], correctAnswer: 2, explanation: 'Viruses do not have a cellular structure and thus are an exception to the cell theory.' },
                { type: 'multiple-choice', question: 'Who discovered the nucleus?', options: ['Robert Hooke', 'Robert Brown', 'Rudolf Virchow', 'Anton Van Leeuwenhoek'], correctAnswer: 1, explanation: 'Robert Brown discovered the nucleus in 1831.' },
                { type: 'multiple-choice', question: 'Gram staining is used to classify:', options: ['Viruses', 'Bacteria', 'Fungi', 'Plants'], correctAnswer: 1, explanation: 'Bacteria can be Gram-positive or Gram-negative based on their cell envelope.' },
                { type: 'multiple-choice', question: 'The most abundant lipid in the cell membrane is:', options: ['Cholesterol', 'Phospholipid', 'Glycolipid', 'Sphingolipid'], correctAnswer: 1, explanation: 'Phospholipids form the primary bilayer of the membrane.' },
                { type: 'multiple-choice', question: 'What is the function of pili and fimbriae in bacteria?', options: ['Motility', 'Attachment/Adhesion', 'Conjugation', 'Both B and C'], correctAnswer: 3, explanation: 'They are surface structures used for attachment and some forms of DNA transfer (conjugation), not motility.' },
                { type: 'multiple-choice', question: 'Ostrich egg is an example of:', options: ['The smallest cell', 'The longest cell', 'The largest isolated single cell', 'A prokaryote'], correctAnswer: 2, explanation: 'The egg of an ostrich is the largest isolated single cell.' },
                { type: 'multiple-choice', question: 'Which scientist examined plant cells to form part of the Cell Theory?', options: ['Schwann', 'Virchow', 'Schleiden', 'Hooke'], correctAnswer: 2, explanation: 'Matthias Schleiden (Botanist) examined plant cells.' },
                { type: 'multiple-choice', question: 'The genetic material of a prokaryote is called:', options: ['Nucleolus', 'Nucleoid', 'Nucleus', 'Nucleoplasm'], correctAnswer: 1, explanation: 'It is a naked mass of DNA not enclosed by a nuclear membrane, called a nucleoid.' },
                { type: 'multiple-choice', question: 'Algal cell walls are made of cellulose, galactans, mannans and minerals like:', options: ['Silica', 'Calcium carbonate', 'Magnesium sulfate', 'Iron oxide'], correctAnswer: 1, explanation: 'Algal cell walls contain cellulose, galactans, mannans and calcium carbonate.' },
                { type: 'multiple-choice', question: 'In the fluid mosaic model, proteins are arranged:', options: ['In a continuous layer', 'As a rigid sheet', 'Like icebergs floating in a sea of lipids', 'Only on the inner surface'], correctAnswer: 2, explanation: 'Proteins are irregularly scattered in the fluid lipid bilayer.' },
                { type: 'multiple-choice', question: 'Passive transport of water across a selectively permeable membrane is called:', options: ['Osmosis', 'Diffusion', 'Active transport', 'Exocytosis'], correctAnswer: 0, explanation: 'Osmosis is the diffusion of water.' },
                { type: 'multiple-choice', question: 'Which cell shape is characteristic of human red blood cells?', options: ['Long and narrow', 'Round and biconcave', 'Amoeboid', 'Branched'], correctAnswer: 1, explanation: 'RBCs are round and biconcave.' },
                { type: 'multiple-choice', question: 'Flagella in prokaryotes differ from eukaryotic flagella in:', options: ['Being absent', 'Having a 9+2 arrangement', 'Lacking a 9+2 arrangement', 'Being made of tubulin'], correctAnswer: 2, explanation: 'Prokaryotic flagella use flagellin and lack the 9+2 microtubule structure of eukaryotes.' },
                { type: 'multiple-choice', question: 'Which of the following can pass freely through the lipid bilayer?', options: ['Charged ions', 'Large polar molecules', 'Small non-polar molecules', 'Proteins'], correctAnswer: 2, explanation: 'Non-polar (lipid-soluble) molecules pass easily. Polar molecules need carrier proteins.' },
                { type: 'multiple-choice', question: 'A continuous network of interconnected sacs/tubules spreading through the cytoplasm is:', options: ['Golgi apparatus', 'Endoplasmic Reticulum', 'Lysosomes', 'Mitochondria'], correctAnswer: 1, explanation: 'This describes the Endoplasmic Reticulum.' },
            ]
        },
        {
            id: 'endomembrane-system',
            title: 'The Endomembrane System',
            desc: 'Explore the ER, Golgi, Lysosomes, and Vacuoles working together.',
            color: '#7c3aed',
            icon: '📦',
            learnSections: [
                {
                    heading: 'System Components',
                    content: 'The endomembrane system includes the Endoplasmic Reticulum (ER), Golgi complex, lysosomes, and vacuoles because their functions are coordinated.',
                    example: 'Mitochondria and chloroplasts are NOT part of this system because their functions are independent.',
                },
                {
                    heading: 'Roles',
                    content: 'RER synthesizes proteins, SER synthesizes lipids. Golgi packages and modifies materials. Lysosomes are the "suicide bags" (digestion).',
                    example: 'Golgi receives proteins from the ER, modifies them, and ships them to their destination.',
                }
            ],
            practice: [
                { type: 'multiple-choice', question: 'Which organelles are part of the endomembrane system?', options: ['ER, Golgi, Lysosomes, Vacuoles', 'Mitochondria, Chloroplasts, Nucleus', 'Ribosomes, Cytoskeleton, Centrioles', 'Nucleus, ER, Golgi, Mitochondria'], correctAnswer: 0, explanation: 'Their functions are coordinated in transport and processing.' },
                { type: 'multiple-choice', question: 'Smooth Endoplasmic Reticulum (SER) is primarily involved in:', options: ['Protein synthesis', 'Lipid synthesis', 'ATP production', 'Photosynthesis'], correctAnswer: 1, explanation: 'SER lacks ribosomes and synthesizes lipids/steroids.' },
                { type: 'multiple-choice', question: 'Rough Endoplasmic Reticulum (RER) is "rough" because it has:', options: ['Lysosomes attached', 'Ribosomes attached', 'Microtubules attached', 'Golgi bodies attached'], correctAnswer: 1, explanation: 'Ribosomes on its surface give it a rough appearance and synthesize proteins.' },
                { type: 'multiple-choice', question: 'The Golgi apparatus was discovered by:', options: ['George Palade', 'Camillo Golgi', 'Christian de Duve', 'Robert Brown'], correctAnswer: 1, explanation: 'Camillo Golgi observed densely stained reticular structures near the nucleus (1898).' },
                { type: 'multiple-choice', question: 'The main function of the Golgi apparatus is:', options: ['Energy generation', 'Packaging and secretion of materials', 'Lipid synthesis', 'Digestion'], correctAnswer: 1, explanation: 'It acts as the packaging and dispatch center of the cell.' },
                { type: 'multiple-choice', question: 'Lysosomes are rich in which type of enzymes?', options: ['Ligases', 'Hydrolytic enzymes (Hydrolases)', 'Transferases', 'Isomerases'], correctAnswer: 1, explanation: 'Lysosomes contain lipases, proteases, carbohydrases active at acidic pH.' },
                { type: 'multiple-choice', question: 'In plant cells, vacuoles can occupy up to:', options: ['10% of cell volume', '50% of cell volume', '90% of cell volume', '1% of cell volume'], correctAnswer: 2, explanation: 'The large central vacuole is a prominent feature of mature plant cells.' },
                { type: 'multiple-choice', question: 'The membrane surrounding the vacuole is called:', options: ['Tonoplast', 'Plasma membrane', 'Cell wall', 'Nuclear envelope'], correctAnswer: 0, explanation: 'The tonoplast facilitates active transport of ions into the vacuole.' },
                { type: 'multiple-choice', question: 'Which face of the Golgi apparatus receives vesicles from the ER?', options: ['Trans face (Maturing)', 'Cis face (Forming)', 'Lateral face', 'Basal face'], correctAnswer: 1, explanation: 'Materials enter via the convex cis face and exit from the concave trans face.' },
                { type: 'multiple-choice', question: 'Lysosomes are formed by the process of packaging in the:', options: ['Endoplasmic Reticulum', 'Mitochondria', 'Golgi apparatus', 'Nucleus'], correctAnswer: 2, explanation: 'Hydrolytic enzymes from ER are packaged into lysosomes by the Golgi.' },
                { type: 'multiple-choice', question: 'Contractile vacuoles in Amoeba are important for:', options: ['Digestion', 'Excretion and Osmoregulation', 'Respiration', 'Reproduction'], correctAnswer: 1, explanation: 'They pump out excess water.' },
                { type: 'multiple-choice', question: 'Food vacuoles in Protists are formed by:', options: ['Exocytosis', 'Engulfing the food particles (Phagocytosis)', 'Division of the nucleus', 'Synthesis in the ER'], correctAnswer: 1, explanation: 'They form around engulfed food particles.' },
                { type: 'multiple-choice', question: 'Important site for the formation of glycoproteins and glycolipids is the:', options: ['Lysosome', 'Vacuole', 'Golgi apparatus', 'Plastids'], correctAnswer: 2, explanation: 'Proteins and lipids from the ER are modified in the Golgi apparatus by adding carbohydrate chains.' },
                { type: 'multiple-choice', question: 'In animal cells, lipid-like steroidal hormones are synthesized in the:', options: ['RER', 'SER', 'Golgi apparatus', 'Lysosomes'], correctAnswer: 1, explanation: 'SER is responsible for synthesizing lipids and steroidal hormones.' },
                { type: 'multiple-choice', question: 'Are mitochondria part of the endomembrane system?', options: ['Yes', 'No'], correctAnswer: 1, explanation: 'No, their functions are not intricately coordinated with the ER/Golgi transport pathway.' },
            ],
            assessment: [
                { type: 'multiple-choice', question: 'If a cell is actively synthesizing secretory proteins, it will have an abundance of:', options: ['SER', 'RER', 'Lysosomes', 'Vacuoles'], correctAnswer: 1, explanation: 'RER is heavily involved in synthesizing proteins meant for secretion.' },
                { type: 'multiple-choice', question: 'Which organelle is considered the "suicide bag" of the cell?', options: ['Golgi', 'Mitochondria', 'Lysosome', 'Ribosome'], correctAnswer: 2, explanation: 'Lysosomes contain powerful hydrolytic enzymes that can digest the cell if released.' },
                { type: 'multiple-choice', question: 'The stacked, flattened disc-like sacs in the Golgi apparatus are called:', options: ['Cristae', 'Cisternae', 'Thylakoids', 'Granum'], correctAnswer: 1, explanation: 'Cisternae are the flattened sacs of the Golgi.' },
                { type: 'multiple-choice', question: 'What does the tonoplast actively pump INTO the vacuole?', options: ['Water only', 'Ions and other materials', 'Proteins', 'Lipids'], correctAnswer: 1, explanation: 'The tonoplast actively transports ions against their concentration gradient into the vacuole.' },
                { type: 'multiple-choice', question: 'A lysosome\'s enzymes are optimally active under which condition?', options: ['Basic pH', 'Neutral pH', 'Acidic pH', 'Any pH'], correctAnswer: 2, explanation: 'Lysosomal hydrolases require an acidic environment to function.' },
                { type: 'multiple-choice', question: 'Where do the materials packaged by the Golgi apparatus usually come from?', options: ['Mitochondria', 'Endoplasmic Reticulum', 'Plasma Membrane', 'Nucleus'], correctAnswer: 1, explanation: 'Proteins and lipids are synthesized in the ER and sent to the Golgi.' },
                { type: 'multiple-choice', question: 'Detoxification of drugs in the liver is primarily handled by the:', options: ['RER', 'SER', 'Golgi', 'Lysosomes'], correctAnswer: 1, explanation: 'SER plays a major role in detoxifying drugs and poisons.' },
                { type: 'multiple-choice', question: 'Which face of the Golgi is also known as the convex face?', options: ['Cis face', 'Trans face', 'Maturing face', 'Lateral face'], correctAnswer: 0, explanation: 'The Cis face or forming face is convex.' },
                { type: 'multiple-choice', question: 'Which cell structure is NOT part of the endomembrane system?', options: ['Vacuole', 'Golgi', 'Peroxisome', 'Lysosome'], correctAnswer: 2, explanation: 'Peroxisomes, Mitochondria, and Chloroplasts are excluded.' },
                { type: 'multiple-choice', question: 'Which of the following describes the relationship between cis and trans faces of the Golgi?', options: ['They are entirely different and unconnected', 'They are interconnected but distinctly different', 'They are identical in structure and function', 'They lie parallel but don\'t interact'], correctAnswer: 1, explanation: 'They have distinct roles but are interconnected through vesicle transport.' },
                { type: 'multiple-choice', question: 'The space inside the ER is called the:', options: ['Luminal compartment', 'Extraluminal compartment', 'Stroma', 'Matrix'], correctAnswer: 0, explanation: 'Inside the ER is the luminal space; the cytoplasm is the extraluminal space.' },
                { type: 'multiple-choice', question: 'Proteins synthesized by ribosomes on the ER are modified in the:', options: ['Lysosome cisternae', 'Golgi cisternae', 'Mitochondrial cristae', 'Vacuole'], correctAnswer: 1, explanation: 'They are modified in the Golgi cisternae before release.' },
                { type: 'multiple-choice', question: 'Which organelle is large and centrally located in a typical plant cell but small/absent in an animal cell?', options: ['Nucleus', 'Vacuole', 'Mitochondria', 'Golgi apparatus'], correctAnswer: 1, explanation: 'Plant cells have a huge central vacuole.' },
                { type: 'multiple-choice', question: 'Autolysis (self-digestion) of a dying cell is carried out by:', options: ['Lysosomes', 'Peroxisomes', 'Dietary vacuoles', 'SER'], correctAnswer: 0, explanation: 'Lysosomes rupture and their hydrolases digest the cell.' },
                { type: 'multiple-choice', question: 'A cell with extensive SER would likely synthesize large amounts of:', options: ['Enzymes', 'Lipids/Steroids', 'Carbohydrates', 'Nucleic acids'], correctAnswer: 1, explanation: 'SER is the major site of lipid synthesis.' },
            ]
        },
        {
            id: 'energy-organelles',
            title: 'Energy & Core Organelles',
            desc: 'Understand Mitochondria, Plastids, and the mighty Nucleus.',
            color: '#dc2626',
            icon: '⚡',
            learnSections: [
                {
                    heading: 'The Powerhouses',
                    content: 'Mitochondria produce ATP (cellular energy). Chloroplasts (a type of plastid) trap solar energy for photosynthesis.',
                    example: 'Both have double membranes and contain their own circular DNA and 70S ribosomes! They are semi-autonomous.',
                },
                {
                    heading: 'The Nucleus',
                    content: 'The control center. It contains chromatin (DNA + histones) which condenses into chromosomes during cell division.',
                    example: 'The nucleolus inside the nucleus is the site for ribosomal RNA (rRNA) synthesis.',
                }
            ],
            practice: [
                { type: 'multiple-choice', question: 'Which organelle is known as the powerhouse of the cell?', options: ['Nucleus', 'Chloroplast', 'Mitochondria', 'Golgi'], correctAnswer: 2, explanation: 'Mitochondria produce cellular energy in the form of ATP.' },
                { type: 'multiple-choice', question: 'What are the infoldings of the inner mitochondrial membrane called?', options: ['Cisternae', 'Thylakoids', 'Cristae', 'Matrix'], correctAnswer: 2, explanation: 'Cristae increase the surface area for ATP production.' },
                { type: 'multiple-choice', question: 'Plastids are found in:', options: ['All plant cells only', 'All animal cells', 'All plant cells and in euglenoides', 'Only in algae'], correctAnswer: 2, explanation: 'Plastids are found in all plant cells and in euglenoides.' },
                { type: 'multiple-choice', question: 'Which type of plastid stores starch?', options: ['Amyloplast', 'Elaioplast', 'Aleuroplast', 'Chromoplast'], correctAnswer: 0, explanation: 'Amyloplasts store carbohydrates like starch.' },
                { type: 'multiple-choice', question: 'The flat, membranous sacs inside the chloroplast are called:', options: ['Cristae', 'Stroma', 'Thylakoids', 'Cisternae'], correctAnswer: 2, explanation: 'Thylakoids are stacked like coins to form grana within the chloroplast.' },
                { type: 'multiple-choice', question: 'Mitochondria and chloroplasts share what feature with prokaryotes?', options: ['70S ribosomes', '80S ribosomes', 'Linear DNA', 'Cell wall'], correctAnswer: 0, explanation: 'Both organelles contain 70S ribosomes and circular DNA.' },
                { type: 'multiple-choice', question: 'The space enclosed by the inner membrane of the chloroplast is called the:', options: ['Matrix', 'Stroma', 'Lumen', 'Cytoplasm'], correctAnswer: 1, explanation: 'The inner space of the chloroplast is the stroma.' },
                { type: 'multiple-choice', question: 'The nucleus is enclosed by how many membranes?', options: ['None', 'One', 'Two', 'Three'], correctAnswer: 2, explanation: 'The nuclear envelope consists of two parallel membranes with a perinuclear space.' },
                { type: 'multiple-choice', question: 'Where does active ribosomal RNA (rRNA) synthesis take place?', options: ['Nucleolus', 'Nuclear pore', 'Nucleoplasm', 'SER'], correctAnswer: 0, explanation: 'The nucleolus is a non-membrane bound spherical structure in the nucleoplasm involved in rRNA synthesis.' },
                { type: 'multiple-choice', question: 'During cell division, chromatin condenses to form:', options: ['Nucleoli', 'Chromosomes', 'Centrioles', 'Spindle fibers'], correctAnswer: 1, explanation: 'Chromosomes are highly condensed structures of DNA and proteins seen during division.' },
                { type: 'multiple-choice', question: 'Every chromosome has a primary constriction called the:', options: ['Telomere', 'Centromere', 'Kinetochore', 'Satellite'], correctAnswer: 1, explanation: 'The centromere is the primary constriction holding sister chromatids together.' },
                { type: 'multiple-choice', question: 'Disc-shaped structures on the sides of the centromere are called:', options: ['Telomeres', 'Kinetochores', 'Centrosomes', 'Satellites'], correctAnswer: 1, explanation: 'Kinetochores serve as attachment points for spindle fibers.' },
                { type: 'multiple-choice', question: 'A chromosome with a centromere near the end (forming an extremely short arm and very long arm) is called:', options: ['Metacentric', 'Sub-metacentric', 'Acrocentric', 'Telocentric'], correctAnswer: 2, explanation: 'Acrocentric chromosomes have the centromere situated close to its end.' },
                { type: 'multiple-choice', question: 'Microbodies (like peroxisomes) are found in:', options: ['Only animal cells', 'Only plant cells', 'Both plant and animal cells', 'Prokaryotes'], correctAnswer: 2, explanation: 'Microbodies containing various enzymes are found in both plants and animals.' },
                { type: 'multiple-choice', question: 'Cilia and flagella have a core called the axoneme. What is its microtubular arrangement?', options: ['9 + 0', '9 + 2', '9 + 4', 'Center pair only'], correctAnswer: 1, explanation: 'Eukaryotic cilia and flagella have a 9+2 arrangement (9 peripheral doublets, 2 central singlets).' },
            ],
            assessment: [
                { type: 'multiple-choice', question: 'Which plastid contains fat-soluble carotenoid pigments (orange, yellow, red)?', options: ['Chloroplast', 'Chromoplast', 'Leucoplast', 'Amyloplast'], correctAnswer: 1, explanation: 'Chromoplasts give color to plant parts.' },
                { type: 'multiple-choice', question: 'Which organelle divides by fission?', options: ['Golgi apparatus', 'Lysosome', 'Mitochondria', 'Nucleus'], correctAnswer: 2, explanation: 'Mitochondria (and chloroplasts) replicate by fission, similar to bacteria.' },
                { type: 'multiple-choice', question: 'The space inside a thylakoid is called the:', options: ['Stroma', 'Matrix', 'Lumen', 'Cisterna'], correctAnswer: 2, explanation: 'The membrane of thylakoids encloses a space called the lumen.' },
                { type: 'multiple-choice', question: 'Aleuroplasts store which type of nutrient?', options: ['Starch', 'Oils and fats', 'Proteins', 'Water'], correctAnswer: 2, explanation: 'Aleuroplasts specifically store proteins.' },
                { type: 'multiple-choice', question: 'What is the function of the nuclear pores?', options: ['To let DNA out', 'For lipid synthesis', 'To allow passage of RNA and proteins', 'Energy transfer'], correctAnswer: 2, explanation: 'Nuclear pores allow RNA and proteins to move between the nucleus and the cytoplasm.' },
                { type: 'multiple-choice', question: 'In a metacentric chromosome, the centromere is located:', options: ['At the very end', 'Near the end', 'Slightly off-center', 'In the exact middle'], correctAnswer: 3, explanation: 'Metacentric means the centromere is in the middle, creating two equal arms.' },
                { type: 'multiple-choice', question: 'What is a satellite chromosome?', options: ['A chromosome with no centromere', 'A chromosome with a secondary constriction', 'A tiny chromosome', 'A chromosome outside the nucleus'], correctAnswer: 1, explanation: 'Secondary constrictions give the appearance of a small fragment called a satellite.' },
                { type: 'multiple-choice', question: 'Centrosomes usually contain two cylindrical structures called:', options: ['Centromeres', 'Centrioles', 'Kinetochores', 'Basal bodies'], correctAnswer: 1, explanation: 'A centrosome contains two mutually perpendicular centrioles.' },
                { type: 'multiple-choice', question: 'Centrioles have a microtubule organization of:', options: ['9 + 2', '9 + 0', '9 + 1', 'Variable'], correctAnswer: 1, explanation: 'Centrioles have 9 evenly spaced peripheral fibrils of tubulin and no central pair (9+0 arrangement).' },
                { type: 'multiple-choice', question: 'Which scientist first described chromatin?', options: ['Robert Brown', 'George Palade', 'Walther Flemming', 'Camillo Golgi'], correctAnswer: 2, explanation: 'Flemming gave the name chromatin to the material stained by basic dyes.' },
                { type: 'multiple-choice', question: 'Which cells lack a nucleus at maturity?', options: ['Human neurons', 'Mammalian RBCs and sieve tube cells', 'Human skin cells', 'Muscle cells'], correctAnswer: 1, explanation: 'Erythrocytes (RBCs) in many mammals and sieve tube cells of vascular plants lack a nucleus.' },
                { type: 'multiple-choice', question: 'Which part of the mitochondria is responsible for the formation of cristae?', options: ['Outer membrane', 'Inner membrane', 'Intermembrane space', 'Matrix'], correctAnswer: 1, explanation: 'The inner membrane forms infoldings called cristae.' },
                { type: 'multiple-choice', question: 'The central part of the proximal region of the centriole is proteinaceous and called the:', options: ['Axoneme', 'Hub', 'Spokes', 'Kinetochore'], correctAnswer: 1, explanation: 'The central part is called the hub, connected to the peripheral triplets by radial spokes.' },
                { type: 'multiple-choice', question: 'In chloroplasts, enzymes required for the synthesis of carbohydrates and proteins are found in the:', options: ['Thylakoid lumen', 'Grana', 'Stroma', 'Outer membrane'], correctAnswer: 2, explanation: 'The stroma contains the enzymes for the dark reaction of photosynthesis (Calvin cycle).' },
                { type: 'multiple-choice', question: 'A telocentric chromosome has its centromere:', options: ['In the middle', 'Slightly away from the middle', 'Close to the end', 'At the terminal end'], correctAnswer: 3, explanation: 'Telocentric chromosomes have a terminal centromere.' },
            ]
        }
    ];
};
