export const TERMS = [
    { word: 'Vector Equation of a Line', def: 'A line through point $\\vec{a}$ in the direction of $\\vec{b}$ is $\\vec{r} = \\vec{a} + \\lambda\\vec{b}$, where $\\lambda$ is a real parameter.', icon: '➡️', example: 'Line through $(1,2,3)$ with direction $(2,1,-1)$: $\\vec{r} = (1,2,3) + \\lambda(2,1,-1)$.', realLifeExample: 'A laser beam\'s path is described by a vector equation from its source in its firing direction.' },
    { word: 'Cartesian Form', def: 'The symmetric form $\\frac{x-x_1}{a} = \\frac{y-y_1}{b} = \\frac{z-z_1}{c}$, where $(a,b,c)$ are direction ratios.', icon: '📝', example: 'Line through $(1,2,3)$ with DRs $2:1:-1$: $\\frac{x-1}{2} = \\frac{y-2}{1} = \\frac{z-3}{-1}$.', realLifeExample: 'Architects use Cartesian line equations to define edges of 3D building models.' },
    { word: 'Skew Lines', def: 'Two lines in 3D that are neither parallel nor intersecting. They lie in different planes.', icon: '✖️', example: 'The lines $\\frac{x}{1} = \\frac{y}{0} = \\frac{z}{0}$ (x-axis) and $\\frac{x-1}{0} = \\frac{y}{1} = \\frac{z-1}{0}$ are skew.', realLifeExample: 'Two roads on different levels of a highway interchange are skew lines.' },
    { word: 'Angle Between Lines', def: 'The angle between two lines with direction vectors $\\vec{b_1}$ and $\\vec{b_2}$: $\\cos\\theta = \\frac{|\\vec{b_1} \\cdot \\vec{b_2}|}{|\\vec{b_1}||\\vec{b_2}|}$.', icon: '📐', example: 'Lines with directions $(1,0,0)$ and $(0,1,0)$: $\\cos\\theta = 0$, so $\\theta = 90°$.', realLifeExample: 'Engineers calculate pipe intersection angles to determine joint types needed.' },
    { word: 'Shortest Distance', def: 'The minimum distance between two skew lines, calculated using the cross product of their direction vectors and the vector joining their points.', icon: '📏', example: '$d = \\frac{|(\\vec{a_2}-\\vec{a_1}) \\cdot (\\vec{b_1} \\times \\vec{b_2})|}{|\\vec{b_1} \\times \\vec{b_2}|}$.', realLifeExample: 'Mining engineers calculate the clearance between tunnels using shortest distance formulas.' },
    { word: 'Coplanar Lines', def: 'Two lines are coplanar if they lie in the same plane. They are either parallel or intersecting. Non-coplanar lines are skew.', icon: '📋', example: 'Lines are coplanar iff $(\\vec{a_2}-\\vec{a_1}) \\cdot (\\vec{b_1} \\times \\vec{b_2}) = 0$.', realLifeExample: 'Checking if two structural beams lie in the same plane determines weld vs. bolt joint design.' },
    { word: 'Parametric Equations', def: 'Expressing each coordinate as a function of a single parameter: $x = x_1 + at$, $y = y_1 + bt$, $z = z_1 + ct$.', icon: '🔢', example: 'Line through $(1,2,3)$ with direction $(2,1,-1)$: $x = 1+2t$, $y = 2+t$, $z = 3-t$.', realLifeExample: 'Animation software uses parametric equations to smoothly move objects along 3D paths.' },
];
export const KEY_IDENTITIES = [
    { name: 'Vector Form of a Line', desc: 'The position vector of any point on the line is the sum of a fixed point and a scalar multiple of the direction vector.', formula: '\\vec{r} = \\vec{a} + \\lambda\\vec{b}' },
    { name: 'Angle Between Two Lines', desc: 'Uses the dot product of direction vectors. The absolute value ensures we get the acute angle.', formula: '\\cos\\theta = \\frac{|\\vec{b_1} \\cdot \\vec{b_2}|}{|\\vec{b_1}||\\vec{b_2}|}' },
    { name: 'Shortest Distance (Skew Lines)', desc: 'Uses the scalar triple product divided by the magnitude of the cross product of direction vectors.', formula: 'd = \\frac{|(\\vec{a_2}-\\vec{a_1}) \\cdot (\\vec{b_1} \\times \\vec{b_2})|}{|\\vec{b_1} \\times \\vec{b_2}|}' },
    { name: 'Coplanarity Condition', desc: 'Two lines are coplanar (lie in same plane) when the scalar triple product of the connecting vector and both direction vectors is zero.', formula: '(\\vec{a_2}-\\vec{a_1}) \\cdot (\\vec{b_1} \\times \\vec{b_2}) = 0' },
];
export const VOCAB_QUIZ = [
    { id: 1, q: 'Two lines that are neither parallel nor intersecting are called:', options: ['Concurrent', 'Skew', 'Coplanar', 'Perpendicular'], correct: 1 },
    { id: 2, q: 'In $\\vec{r} = \\vec{a} + \\lambda\\vec{b}$, what does $\\vec{b}$ represent?', options: ['A point on the line', 'The origin', 'Direction vector', 'Normal vector'], correct: 2 },
    { id: 3, q: 'The shortest distance between parallel lines is:', options: ['Always zero', 'Always infinite', 'Constant (non-zero)', 'Undefined'], correct: 2 },
    { id: 4, q: 'If $(\\vec{a_2}-\\vec{a_1}) \\cdot (\\vec{b_1} \\times \\vec{b_2}) = 0$, the lines are:', options: ['Skew', 'Perpendicular', 'Coplanar', 'Equal'], correct: 2 },
    { id: 5, q: 'How many parameters does a line in 3D need?', options: ['1', '2', '3', '6'], correct: 0 },
];
