import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import styles from '../../../../Trigonometry/trigonometry.module.css';
import MathRenderer from '../../../../../MathRenderer';
import { TERMS, KEY_IDENTITIES, VOCAB_QUIZ } from './LinesTerminologyData';

export default function LinesTerminology() {
    const navigate = useNavigate();
    const [activeTab, setActiveTab] = useState('terms');
    const [selectedIdx, setSelectedIdx] = useState(0);
    const [selectedIdentityIdx, setSelectedIdentityIdx] = useState(0);
    const [quizAnswers, setQuizAnswers] = useState({});
    const [showResults, setShowResults] = useState(false);
    useEffect(() => window.scrollTo(0, 0), []);
    const activeTerm = TERMS[selectedIdx]; const activeIdentity = KEY_IDENTITIES[selectedIdentityIdx];
    const accentColor = '#f43f5e'; const accentBg = 'rgba(244, 63, 94, 0.08)';
    const bp = '/coordinate-geometry/lines-in-space';

    return (
        <div className={styles.arithPage}>
            <nav className={styles.introNav}><button className={styles.arithBackBtn} onClick={() => navigate(bp)} style={{ marginBottom: 0 }}>← Back to Branch</button><div className={styles.arithIntroNavLinks}><button className={styles.arithIntroNavLink} onClick={() => navigate(`${bp}/introduction`)}>🌟 Introduction</button><button className={`${styles.arithIntroNavLink} ${styles.arithIntroNavLinkActive}`}>📖 Terminology</button><button className={styles.arithIntroNavLink} onClick={() => navigate(`${bp}/skills`)}>🎯 Skills</button></div></nav>
            <div className={styles.arithTermContainer}>
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', marginBottom: 20, paddingTop: 32 }}><h1 style={{ fontFamily: '"Outfit", sans-serif', fontSize: '2.8rem', fontWeight: 900, color: '#0f172a', margin: '0 0 8px' }}>Lines in Space{' '}<span style={{ background: 'linear-gradient(135deg, #f43f5e, #8b5cf6)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Vocabulary</span></h1><div style={{ fontSize: 16, fontWeight: 700, color: '#64748b' }}>{activeTab === 'quiz' ? 'Test your knowledge!' : `Select any ${activeTab === 'terms' ? 'term' : 'formula'} below.`}</div></div>
                <div className={styles.arithTabSwitcher}>{[['terms', '📚 Terms'], ['identities', '⚡ Key Formulas'], ['quiz', '🧪 Vocab Check']].map(([key, label]) => <button key={key} style={{ padding: '8px 16px', borderRadius: 100, border: 'none', background: activeTab === key ? accentColor : '#e2e8f0', color: activeTab === key ? '#fff' : '#475569', fontWeight: 700, cursor: 'pointer' }} onClick={() => setActiveTab(key)}>{label}</button>)}</div>
                {activeTab !== 'quiz' ? (
                    <div className={styles.arithTermLayout}>
                        <aside className={styles.arithTermPanel} style={{ background: 'rgba(255,255,255,0.7)', padding: '14px', borderRadius: 20, border: '1px solid rgba(0,0,0,0.05)', display: 'flex', flexDirection: 'column', gap: 10, backdropFilter: 'blur(10px)' }}>
                            {activeTab === 'terms' ? TERMS.map((term, i) => { const isA = selectedIdx === i; return <button key={i} onClick={() => setSelectedIdx(i)} style={{ background: isA ? `linear-gradient(135deg, ${accentColor}, ${accentColor}dd)` : `linear-gradient(135deg, ${accentBg}, rgba(244,63,94,0.02))`, borderColor: isA ? accentColor : 'rgba(244,63,94,0.15)', borderWidth: 1.5, borderStyle: 'solid', display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', borderRadius: 12, cursor: 'pointer', outline: 'none' }}><div style={{ width: 36, height: 36, borderRadius: 10, background: isA ? 'rgba(255,255,255,0.25)' : '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20 }}>{term.icon}</div><span style={{ fontWeight: 800, fontSize: 13, color: isA ? '#fff' : '#1e293b', textAlign: 'left' }}>{term.word.substring(0, 20)}{term.word.length > 20 ? '…' : ''}</span></button>; }) : KEY_IDENTITIES.map((id, i) => { const isA = selectedIdentityIdx === i; return <button key={i} onClick={() => setSelectedIdentityIdx(i)} style={{ background: isA ? `linear-gradient(135deg, ${accentColor}, ${accentColor}dd)` : `linear-gradient(135deg, ${accentBg}, rgba(244,63,94,0.02))`, borderColor: isA ? accentColor : 'rgba(244,63,94,0.15)', borderWidth: 1.5, borderStyle: 'solid', display: 'flex', alignItems: 'center', gap: 10, padding: '12px 16px', borderRadius: 12, cursor: 'pointer', outline: 'none' }}><div style={{ width: 36, height: 36, borderRadius: 10, background: isA ? 'rgba(255,255,255,0.25)' : '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, color: isA ? '#fff' : accentColor, fontWeight: 900 }}>{i + 1}</div><span style={{ fontWeight: 800, fontSize: 13, color: isA ? '#fff' : '#1e293b' }}>{id.name.substring(0, 20)}…</span></button>; })}
                        </aside>
                        <main className={styles.arithTermPanel} key={activeTab === 'terms' ? selectedIdx : `id${selectedIdentityIdx}`} style={{ background: '#ffffff', borderRadius: 20, padding: '30px 40px', boxShadow: '0 8px 24px rgba(0,0,0,0.03)', border: `2px solid ${accentBg}`, minHeight: 330 }}>
                            {activeTab === 'terms' ? (<><div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}><div style={{ width: 44, height: 44, borderRadius: 12, background: accentBg, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 24 }}>{activeTerm.icon}</div><h2 style={{ fontFamily: '"Outfit", sans-serif', fontSize: 24, fontWeight: 900, color: accentColor, margin: 0 }}>{activeTerm.word}</h2></div><div style={{ fontSize: 17, color: '#334155', lineHeight: 1.6, margin: '0 0 24px' }}><MathRenderer text={activeTerm.def} /></div><div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}><div><h4 style={{ textTransform: 'uppercase', fontSize: 11, letterSpacing: 1, color: accentColor, marginBottom: 8 }}>Mathematical Context</h4><div style={{ background: `${accentBg}`, padding: 14, borderRadius: 12, border: `1px solid rgba(244,63,94,0.1)` }}><div style={{ fontSize: 16, color: '#1e293b', fontWeight: 600 }}><MathRenderer text={activeTerm.example} /></div></div></div>{activeTerm.realLifeExample && <div><h4 style={{ textTransform: 'uppercase', fontSize: 11, letterSpacing: 1, color: '#10b981', marginBottom: 8 }}>Real World</h4><div style={{ background: 'rgba(16,185,129,0.04)', padding: 14, borderRadius: 12, border: '1px solid rgba(16,185,129,0.15)' }}><div style={{ fontSize: 15, color: '#065f46', fontWeight: 500, lineHeight: 1.5 }}>🌍 {activeTerm.realLifeExample}</div></div></div>}</div></>) : (<><div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}><div style={{ width: 44, height: 44, borderRadius: 12, background: accentBg, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 24, color: accentColor, fontWeight: 900 }}>⚡</div><h2 style={{ fontFamily: '"Outfit", sans-serif', fontSize: 22, fontWeight: 900, color: accentColor, margin: 0 }}>{activeIdentity.name}</h2></div><div style={{ fontSize: 17, color: '#334155', lineHeight: 1.6, margin: '0 0 24px' }}><MathRenderer text={activeIdentity.desc} /></div><div><h4 style={{ textTransform: 'uppercase', fontSize: 11, letterSpacing: 1, color: accentColor, marginBottom: 10 }}>Formula</h4><div style={{ background: accentBg, padding: 20, borderRadius: 16, border: `1px solid rgba(244,63,94,0.1)`, textAlign: 'center' }}><div style={{ fontSize: 18, fontWeight: 700, color: accentColor }}><MathRenderer text={`$$${activeIdentity.formula}$$`} /></div></div></div></>)}
                        </main>
                    </div>
                ) : (
                    <div className={styles.arithQuizPanel}><h2 style={{ textAlign: 'center', margin: '0 0 32px 0', color: '#0f172a' }}>Quick Knowledge Check</h2><div style={{ display: 'flex', flexDirection: 'column', gap: 32 }}>{VOCAB_QUIZ.map((q) => (<div key={q.id}><div style={{ fontWeight: 600, color: '#1e293b', fontSize: 16, marginBottom: 16 }}>{q.q}</div><div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>{q.options.map((opt, optIdx) => { const isS = quizAnswers[q.id] === optIdx; const isC = optIdx === q.correct; let bg = '#f8fafc', border = '1px solid #e2e8f0', color = '#475569'; if (showResults) { if (isC) { bg = '#dcfce7'; border = '1px solid #22c55e'; color = '#15803d'; } else if (isS && !isC) { bg = '#fee2e2'; border = '1px solid #ef4444'; color = '#b91c1c'; } } else if (isS) { bg = accentBg; border = `1px solid ${accentColor}`; color = accentColor; } return <button key={optIdx} onClick={() => { if (!showResults) setQuizAnswers(p => ({ ...p, [q.id]: optIdx })); }} style={{ padding: '16px 20px', borderRadius: 12, background: bg, border, color, textAlign: 'left', fontSize: 15, cursor: showResults ? 'default' : 'pointer', fontWeight: isS ? 600 : 400 }}>{opt}{showResults && isC && <span style={{ float: 'right' }}>✅</span>}{showResults && isS && !isC && <span style={{ float: 'right' }}>❌</span>}</button>; })}</div></div>))}</div>
                        <div style={{ marginTop: 40, textAlign: 'center', paddingTop: 32, borderTop: '1px solid #e2e8f0' }}>{!showResults ? <button onClick={() => { if (Object.keys(quizAnswers).length < VOCAB_QUIZ.length) { alert('Please answer all questions first!'); return; } setShowResults(true); }} style={{ padding: '14px 32px', background: accentColor, color: '#fff', border: 'none', borderRadius: 100, fontSize: 16, fontWeight: 700, cursor: 'pointer' }}>Check Answers</button> : <div><div style={{ fontSize: 24, fontWeight: 700, color: '#0f172a', marginBottom: 16 }}>You scored {Object.entries(quizAnswers).filter(([qId, ans]) => VOCAB_QUIZ.find(q => q.id === parseInt(qId)).correct === ans).length} / {VOCAB_QUIZ.length}! 🎉</div><div className={styles.arithActionRow}><button onClick={() => { setQuizAnswers({}); setShowResults(false); }} style={{ padding: '12px 24px', background: '#fff', color: '#475569', border: '1.5px solid #e2e8f0', borderRadius: 100, fontSize: 15, fontWeight: 600, cursor: 'pointer' }}>Try Again</button><button onClick={() => navigate(`${bp}/skills`)} style={{ padding: '12px 24px', background: accentColor, color: '#fff', border: 'none', borderRadius: 100, fontSize: 15, fontWeight: 700, cursor: 'pointer' }}>Skills →</button></div></div>}</div>
                    </div>
                )}
            </div>
        </div>
    );
}
