export const SKILLS = [
    {
        id: 'complex-basics',
        title: 'Understanding Complex Numbers',
        subtitle: 'FOUNDATION',
        desc: 'Define complex numbers, identify real and imaginary parts, and apply the equality rule.',
        icon: '🔮',
        color: '#6366f1',
        learn: {
            title: 'What is a Complex Number?',
            rules: [
                {
                    title: 'Definition: a + ib Form',
                    f: 'z = a + ib,\\quad a,b \\in \\mathbb{R},\\quad i = \\sqrt{-1}',
                    d: 'A complex number is any number of the form a + ib. The symbol i (iota) is defined so that i² = −1. Here a is the real part and b is the imaginary part.',
                    ex: 'z = 3 + 5i → Re(z) = 3, Im(z) = 5.\nz = −1 + i√3 → Re(z) = −1, Im(z) = √3.\nz = 7 = 7 + 0i → purely real.\nz = 4i = 0 + 4i → purely imaginary.',
                    tip: 'Im(z) = b, NOT ib. The imaginary part is the real coefficient of i.',
                },
                {
                    title: 'Equality of Complex Numbers',
                    f: 'a + ib = c + id \\iff a = c \\text{ and } b = d',
                    d: 'Two complex numbers are equal only when their real parts are equal AND their imaginary parts are equal. This gives a system of two real equations from one complex equation.',
                    ex: 'If 4x + i(3x − y) = 3 + i(−6), equate real parts: 4x = 3 → x = 3/4. Equate imaginary parts: 3x − y = −6 → y = 3(3/4) + 6 = 33/4.',
                    tip: 'One complex equation → two real equations. Always separate real and imaginary parts.',
                },
                {
                    title: 'Set of Complex Numbers ℂ',
                    f: '\\mathbb{C} = \\{ a + ib : a, b \\in \\mathbb{R} \\}',
                    d: 'ℂ contains all complex numbers. Real numbers ℝ ⊂ ℂ (set b = 0). The complex numbers cannot be ordered — you cannot say z₁ > z₂ for complex numbers.',
                    ex: 'ℝ ⊂ ℂ: every real number 5 = 5 + 0i is complex.\nℂ has no ordering: 3 + 2i > 1 + i is meaningless.',
                    tip: 'Never write z₁ > z₂ or z₁ < z₂. Complex numbers have no order relation.',
                },
            ],
        },
        practice: [
            {
                question: 'Level 1: For $z = -4 + 7i$, what is $\\text{Im}(z)$?',
                options: ['$-4$', '$7i$', '$7$', '$-4 + 7i$'],
                correct: 2,
                explanation: 'Im(z) = 7, not 7i. The imaginary part is always a real number.',
            },
            {
                question: 'Level 1: Which of the following is a purely imaginary number?',
                options: ['$3 + 0i$', '$0 + 5i$', '$2 + 3i$', '$0 + 0i$'],
                correct: 1,
                explanation: 'A purely imaginary number has Re(z) = 0 and Im(z) ≠ 0. That is 5i.',
            },
            {
                question: 'Level 2: If $a + ib = (3 + 2i)(1 - i)$, what is $a$?',
                options: ['$1$', '$5$', '$3$', '$-1$'],
                correct: 1,
                explanation: '(3+2i)(1−i) = 3 − 3i + 2i − 2i² = 3 − i + 2 = 5 − i. So a = 5.',
            },
            {
                question: 'Level 2: If $2x + i(3x - y) = 6 + i(-3)$, find $y$.',
                options: ['$12$', '$-12$', '$9$', '$3$'],
                correct: 0,
                explanation: 'Real: 2x = 6 → x = 3. Imaginary: 3x − y = −3 → 9 − y = −3 → y = 12.',
            },
            {
                question: 'Level 2: Which statement about complex numbers is TRUE?',
                options: ['$3 + 2i > 1 + 4i$', '$3 + 2i = 1 + 2i$ if real parts are equal', 'Complex numbers cannot be compared using $>$ or $<$', '$|3 + 2i| = 3$'],
                correct: 2,
                explanation: 'Complex numbers have no ordering relation. You cannot use > or < with them.',
            },
            {
                question: 'Level 3: If $z = 0 + 0i$, then $z$ is called:',
                options: ['Purely imaginary', 'Purely real', 'Zero complex number', 'Imaginary unit'],
                correct: 2,
                explanation: '0 + 0i is the zero complex number (additive identity).',
            },
            {
                question: 'Level 3: If $a + ib = \\frac{1}{1 - i}$, which is correct?',
                options: ['$a = 1/2, b = 1/2$', '$a = 1, b = 1$', '$a = -1/2, b = 1/2$', '$a = 1/2, b = -1/2$'],
                correct: 0,
                explanation: 'Multiply by conjugate: 1/(1−i) × (1+i)/(1+i) = (1+i)/2 = 1/2 + i/2. So a = b = 1/2.',
            },
            {
                question: 'Level 3: $\\text{Re}(z)$ and $\\text{Im}(z)$ for $z = \\frac{(1+i)^2}{1-i}$ are:',
                options: ['$-1$ and $1$', '$1$ and $1$', '$2$ and $0$', '$0$ and $-2$'],
                correct: 0,
                explanation: '$(1+i)^2 = 2i$. Then $z = \\frac{2i}{1-i} \\cdot \\frac{1+i}{1+i} = \\frac{2i(1+i)}{2} = i+i^2 = -1+i$. So $\\text{Re}(z) = -1$, $\\text{Im}(z) = 1$.',
            },
        ],
        assessment: [
            { type: 'mcq', question: 'Which of the following is a complex number but NOT a real number?', options: ['$\\sqrt{5}$', '$-7$', '$3 + 2i$', '$\\pi$'], correct: 2, explanation: '3+2i has a non-zero imaginary part, so it is not real.' },
            { type: 'text', question: 'Find Im(z) if $z = 5 - 3i$.', answer: '-3', explanation: 'Im(z) = −3 (the coefficient of i).' },
            { type: 'mcq', question: 'If $x + iy = (2 + 3i)^2$, find $x$.', options: ['$4$', '$-5$', '$13$', '$12$'], correct: 1, explanation: '(2+3i)² = 4+12i+9i² = 4+12i−9 = −5+12i. So x = −5.' },
            { type: 'text', question: 'If $(a - 1) + i(b + 3) = 0 + 0i$, find $a + b$.', answer: '-2', acceptedAnswers: ['-2'], explanation: 'a−1=0 → a=1. b+3=0 → b=−3. a+b = 1−3 = −2.' },
            { type: 'mcq', question: 'Which is purely real?', options: ['$i^2$', '$2 + i$', '$\\sqrt{-4}$', '$i^3$'], correct: 0, explanation: 'i² = −1, which is a real number (b = 0).' },
            { type: 'msq', question: 'Which are purely imaginary? Select all that apply.', options: ['$5i$', '$0 + i\\sqrt{3}$', '$0 + 0i$', '$-3i$'], correct: [0, 1, 3], explanation: '5i, i√3, and −3i all have Re = 0 and Im ≠ 0. 0+0i is the zero complex number, not purely imaginary.' },
            { type: 'mcq', question: 'If $3x + 2iy = 9 + 4i$, then $x + y$ equals:', options: ['$3$', '$5$', '$7$', '$13$'], correct: 1, explanation: '3x = 9 → x = 3. 2y = 4 → y = 2. x + y = 5.' },
            { type: 'text', question: 'Write $\\sqrt{-9}$ in the form $a + ib$.', answer: '0+3i', acceptedAnswers: ['3i', '0 + 3i'], explanation: '√(−9) = √9 · √(−1) = 3i = 0 + 3i.' },
            { type: 'mcq', question: 'For $z = a + ib$ and $\\bar{z} = a - ib$, which is true?', options: ['$z + \\bar{z} = 2ib$', '$z - \\bar{z} = 2a$', '$z + \\bar{z} = 2a$', '$z \\cdot \\bar{z} = a - b$'], correct: 2, explanation: 'z + z̄ = (a+ib) + (a−ib) = 2a (always real).' },
            { type: 'mcq', question: 'The number of complex numbers $z$ satisfying $z = \\bar{z}$ is:', options: ['0', 'Infinitely many', '1', '2'], correct: 1, explanation: 'z = z̄ iff a+ib = a−ib iff 2ib = 0 iff b = 0. All real numbers satisfy this — infinitely many.' },
            { type: 'mcq', question: 'If $4x + i(3x - y) = 3 - 6i$, find $y$.', options: ['$-33/4$', '$33/4$', '$-3$', '$3$'], correct: 1, explanation: 'x = 3/4. 3(3/4) − y = −6 → y = 9/4 + 6 = 33/4.' },
            { type: 'text', question: 'Express $\\frac{1}{i}$ in $a + ib$ form.', answer: '0-i', acceptedAnswers: ['-i', '0 - i'], explanation: '1/i = i/i² = i/(−1) = −i = 0 + (−1)i.' },
        ],
    },
    {
        id: 'addition-subtraction',
        title: 'Addition & Subtraction',
        subtitle: 'OPERATIONS',
        desc: 'Add and subtract complex numbers and master the five laws of complex addition.',
        icon: '➕',
        color: '#0d9488',
        learn: {
            title: 'Adding and Subtracting Complex Numbers',
            rules: [
                {
                    title: 'Addition Formula',
                    f: 'z_1 + z_2 = (a+c) + i(b+d)',
                    d: 'Add real parts together and imaginary parts together. Complex addition is closed (result is complex), commutative, associative, and has additive identity 0 + 0i.',
                    ex: '(2 + 3i) + (−6 + 5i) = (2−6) + i(3+5) = −4 + 8i.',
                    tip: 'Group real terms together and imaginary terms together. Treat i like a variable.',
                },
                {
                    title: 'Subtraction Formula',
                    f: 'z_1 - z_2 = (a-c) + i(b-d)',
                    d: 'Subtraction is defined as z₁ + (−z₂). The additive inverse of z = a + ib is −z = (−a) + i(−b).',
                    ex: '(6 + 3i) − (2 − i) = (6−2) + i(3−(−1)) = 4 + 4i.\n(2−i) − (6+3i) = −4 − 4i.',
                    tip: 'Be careful with signs: subtracting −i gives +i. Write out the negative explicitly.',
                },
                {
                    title: 'Properties of Addition',
                    f: 'z + 0 = z, \\quad z + (-z) = 0',
                    d: 'Closure: sum is complex. Commutative: z₁+z₂ = z₂+z₁. Associative: (z₁+z₂)+z₃ = z₁+(z₂+z₃). Additive identity: 0 = 0+0i. Additive inverse: −z = −a + i(−b).',
                    ex: 'Check: (3+2i)+(−3−2i) = 0+0i ✓\n(1+i) + (2+3i) = (2+3i) + (1+i) = 3+4i ✓',
                    tip: 'The additive identity is the zero complex number 0+0i, NOT just 0.',
                },
            ],
        },
        practice: [
            {
                question: 'Level 1: $(3 + 2i) + (1 - 5i) = ?$',
                options: ['$4 - 3i$', '$4 + 3i$', '$3 - 3i$', '$2 - 3i$'],
                correct: 0,
                explanation: 'Real: 3+1=4. Imaginary: 2+(−5) = −3. Answer: 4 − 3i.',
            },
            {
                question: 'Level 1: $(5 + 3i) - (2 + i) = ?$',
                options: ['$7 + 4i$', '$3 + 2i$', '$3 + 4i$', '$7 + 2i$'],
                correct: 1,
                explanation: 'Real: 5−2=3. Imaginary: 3−1=2. Answer: 3 + 2i.',
            },
            {
                question: 'Level 2: $3(7 + 7i) + i(7 + 7i) = ?$',
                options: ['$21 + 28i$', '$21 - 28i$', '$28 + 28i$', '$28 - 7i$'],
                correct: 0,
                explanation: '3(7+7i) = 21+21i. i(7+7i) = 7i+7i² = 7i−7 = −7+7i. Sum: (21−7)+(21+7)i = 14+28i... wait: 21+21i + (−7+7i) = 14+28i. Let me recheck the question: 3(7+i7)+i(7+i7) = (3+i)(7+7i) = 7(3+i)(1+i) = 7(3+3i+i+i²)=7(3+4i−1)=7(2+4i)=14+28i.',
            },
            {
                question: 'Level 2: $(1-i) - (-1+6i) = ?$',
                options: ['$2 - 7i$', '$-2 + 7i$', '$0 - 5i$', '$2 + 5i$'],
                correct: 0,
                explanation: '(1−i) − (−1+6i) = 1−i+1−6i = 2 − 7i.',
            },
            {
                question: 'Level 2: The additive inverse of $-3 + 4i$ is:',
                options: ['$3 - 4i$', '$-3 - 4i$', '$3 + 4i$', '$4 - 3i$'],
                correct: 0,
                explanation: 'Additive inverse of a + ib is −a + i(−b) = −(−3) + i(−4) = 3 − 4i.',
            },
            {
                question: 'Level 3: If $z_1 = 2 + 3i$ and $z_2 = 1 - i$, find $2z_1 - 3z_2$.',
                options: ['$1 + 9i$', '$7 + 9i$', '$7 + 3i$', '$1 + 3i$'],
                correct: 0,
                explanation: '2z₁ = 4+6i. 3z₂ = 3−3i. Difference: (4−3)+(6−(−3))i = 1+9i.',
            },
            {
                question: 'Level 3: The real part of $(z + \\bar{z})$ for $z = 5 - 3i$ is:',
                options: ['$0$', '$5$', '$10$', '$-6i$'],
                correct: 2,
                explanation: 'z + z̄ = (5−3i)+(5+3i) = 10. This is always 2·Re(z).',
            },
            {
                question: 'Level 3: $\\left(\\frac{1}{5} + \\frac{2}{5}i\\right) - \\left(4 + \\frac{5}{2}i\\right) = ?$',
                options: ['$-\\frac{19}{5} - \\frac{21}{10}i$', '$\\frac{19}{5} + \\frac{21}{10}i$', '$-\\frac{19}{5} + \\frac{21}{10}i$', '$\\frac{21}{5} - \\frac{19}{10}i$'],
                correct: 0,
                explanation: 'Real: 1/5−4 = −19/5. Imaginary: 2/5 − 5/2 = 4/10 − 25/10 = −21/10.',
            },
        ],
        assessment: [
            { type: 'mcq', question: '$(2 + 3i) + (-2 - 3i) = ?$', options: ['$4 + 6i$', '$0$', '$-4 - 6i$', '$0 + 0i$'], correct: 3, explanation: 'This is the additive inverse. Sum = 0 + 0i.' },
            { type: 'text', question: 'Find the real part of $(1+i)+(2-3i)$.', answer: '3', explanation: 'Real: 1+2=3.' },
            { type: 'mcq', question: '$(1-i) - (-1+i6) = ?$', options: ['$0-5i$', '$2-7i$', '$-2+7i$', '$0+7i$'], correct: 1, explanation: '(1−i)+(1−6i) = 2−7i.' },
            { type: 'msq', question: 'Which properties hold for complex addition? Select all.', options: ['Commutative', 'Associative', 'Closure', 'Distributive over itself'], correct: [0, 1, 2], explanation: 'Commutativity, associativity, and closure all hold. Distributive is a property of multiplication over addition, not addition alone.' },
            { type: 'text', question: 'Find the imaginary part of $(3+2i)-(1+5i)$.', answer: '-3', explanation: 'Imaginary: 2−5 = −3.' },
            { type: 'mcq', question: 'The additive identity for complex numbers is:', options: ['$1$', '$i$', '$0+0i$', '$1+0i$'], correct: 2, explanation: 'z + (0+0i) = z for all z. Additive identity = 0+0i.' },
            { type: 'mcq', question: 'If $z_1 + z_2 = 5 + 3i$ and $z_1 = 2 + i$, find $z_2$.', options: ['$3 + 2i$', '$3 - 2i$', '$7 + 4i$', '$-3 + 2i$'], correct: 0, explanation: 'z₂ = (5+3i)−(2+i) = 3+2i.' },
            { type: 'mcq', question: '$3(2 + i) - 2(1 - 2i) = ?$', options: ['$4 + 7i$', '$8 - i$', '$4 - i$', '$8 + 7i$'], correct: 0, explanation: '6+3i − 2+4i = 4+7i.' },
            { type: 'text', question: 'Simplify $(a+ib)+(a-ib)$.', answer: '2a', explanation: 'z + z̄ = 2a = 2·Re(z).' },
            { type: 'mcq', question: 'Which is the additive inverse of $2 - 5i$?', options: ['$-2 + 5i$', '$2 + 5i$', '$-2 - 5i$', '$5 - 2i$'], correct: 0, explanation: 'Additive inverse of a+ib is −a+i(−b) = −2+5i.' },
            { type: 'mcq', question: '$(a+ib) - (a+ib) = ?$', options: ['$2a$', '$0+0i$', '$2ib$', '$a$'], correct: 1, explanation: 'Any number minus itself = 0 = 0+0i.' },
            { type: 'text', question: 'Find $z$ if $z + (3-2i) = 5+i$.', answer: '2+3i', explanation: 'z = (5+i)−(3−2i) = 2+3i.' },
        ],
    },
    {
        id: 'multiplication',
        title: 'Multiplication of Complex Numbers',
        subtitle: 'OPERATIONS',
        desc: 'Apply the multiplication formula and six properties including distributive law.',
        icon: '✖️',
        color: '#7c3aed',
        learn: {
            title: 'Multiplying Complex Numbers',
            rules: [
                {
                    title: 'Multiplication Formula',
                    f: 'z_1 z_2 = (ac - bd) + i(ad + bc)',
                    d: 'Expand (a+ib)(c+id) using FOIL: ac + iad + ibc + i²bd. Since i² = −1, the i²bd term becomes −bd. Collect real and imaginary parts.',
                    ex: '(3 + 5i)(2 + 6i) = (3×2 − 5×6) + i(3×6 + 5×2) = (6−30) + i(18+10) = −24 + 28i.',
                    tip: 'FOIL works just like real algebra — just replace i² with −1 whenever it appears.',
                },
                {
                    title: 'Multiplicative Identity & Inverse',
                    f: 'z \\cdot 1 = z, \\qquad z^{-1} = \\frac{a}{a^2+b^2} - i\\frac{b}{a^2+b^2}',
                    d: 'The multiplicative identity is 1 = 1+0i. For non-zero z = a+ib, the inverse z⁻¹ = z̄/|z|². Use this to convert division into multiplication.',
                    ex: 'z = 2−3i: z⁻¹ = (2+3i)/(4+9) = 2/13 + 3i/13.',
                    tip: 'To find z⁻¹, always use z⁻¹ = z̄/|z|² rather than guessing.',
                },
                {
                    title: 'Algebraic Identities',
                    f: '(z_1 + z_2)^2 = z_1^2 + 2z_1 z_2 + z_2^2',
                    d: 'All standard identities hold for complex z because they follow from the field axioms (which ℂ satisfies). Also: (z₁−z₂)² = z₁²−2z₁z₂+z₂², (z₁+z₂)³ = z₁³+3z₁²z₂+3z₁z₂²+z₂³, and z₁²−z₂² = (z₁+z₂)(z₁−z₂).',
                    ex: '(5−3i)³ = 5³ − 3·5²·(3i) + 3·5·(3i)² − (3i)³\n= 125 − 225i − 135 + 27i = −10 − 198i.',
                    tip: 'Use the binomial expansion for cubes to avoid errors. Never guess; expand step by step.',
                },
            ],
        },
        practice: [
            {
                question: 'Level 1: $(2 + i)(3 - 2i) = ?$',
                options: ['$8 - i$', '$6 - 2i$', '$8 + i$', '$4 - i$'],
                correct: 0,
                explanation: 'FOIL: 6−4i+3i−2i² = 6−i+2 = 8−i.',
            },
            {
                question: 'Level 1: $i \\times i^3 = ?$',
                options: ['$1$', '$-1$', '$i$', '$-i$'],
                correct: 0,
                explanation: '$i \\times i^3 = i^4 = (i^2)^2 = (-1)^2 = 1$.',
            },
            {
                question: 'Level 2: $(3 + 5i)(2 + 6i) = ?$',
                options: ['$-24 + 28i$', '$24 + 28i$', '$-24 - 28i$', '$6 + 30i$'],
                correct: 0,
                explanation: '(6−30) + i(18+10) = −24 + 28i.',
            },
            {
                question: 'Level 2: $(-5i)(\\frac{1}{8}i) = ?$',
                options: ['$\\frac{5}{8}$', '$-\\frac{5}{8}$', '$\\frac{5}{8}i$', '$-\\frac{5}{8}i$'],
                correct: 0,
                explanation: '(−5i)(i/8) = −5i²/8 = −5(−1)/8 = 5/8.',
            },
            {
                question: 'Level 2: $(1+i)^2 = ?$',
                options: ['$2$', '$2i$', '$1 + 2i$', '$-2$'],
                correct: 1,
                explanation: '(1+i)² = 1 + 2i + i² = 1+2i−1 = 2i.',
            },
            {
                question: 'Level 3: $(5 - 3i)^3 = ?$',
                options: ['$-10 - 198i$', '$-10 + 198i$', '$10 - 198i$', '$125 - 27i$'],
                correct: 0,
                explanation: '5³−3·5²·(3i)+3·5·(3i)²−(3i)³ = 125−225i−135+27i = −10−198i.',
            },
            {
                question: 'Level 3: $(-\\sqrt{3} + \\sqrt{-2})(2\\sqrt{3} - i) = ?$',
                options: ['$(-6+\\sqrt{2}) + \\sqrt{3}(1+2\\sqrt{2})i$', '$-6 + i$', '$\\sqrt{6} - i$', '$-6\\sqrt{3}$'],
                correct: 0,
                explanation: '(−√3 + i√2)(2√3−i) = −6 + i√3 + 2i√6 − i²√2 = (−6+√2) + (√3+2√6)i = (−6+√2)+√3(1+2√2)i.',
            },
            {
                question: 'Level 3: The multiplicative inverse of $2 - 3i$ is:',
                options: ['$\\frac{2}{13} + \\frac{3}{13}i$', '$\\frac{2}{13} - \\frac{3}{13}i$', '$\\frac{-2}{13} + \\frac{3}{13}i$', '$2 + 3i$'],
                correct: 0,
                explanation: 'z⁻¹ = z̄/|z|² = (2+3i)/13 = 2/13 + 3i/13.',
            },
        ],
        assessment: [
            { type: 'mcq', question: '$(1+i)^4 = ?$', options: ['$4$', '$-4$', '$4i$', '$-4i$'], correct: 1, explanation: '(1+i)² = 2i. (2i)² = 4i² = −4.' },
            { type: 'text', question: 'Find the real part of $(2+3i)(1-i)$.', answer: '5', explanation: '(2+3i)(1−i) = 2−2i+3i−3i² = 2+i+3 = 5+i. Re = 5.' },
            { type: 'mcq', question: 'The multiplicative inverse of $1 + i$ is:', options: ['$1-i$', '$\\frac{1-i}{2}$', '$\\frac{1+i}{2}$', '$-(1+i)$'], correct: 1, explanation: '(1+i)⁻¹ = (1−i)/|1+i|² = (1−i)/2.' },
            { type: 'mcq', question: '$(2+i)^2 - (2-i)^2 = ?$', options: ['$0$', '$8i$', '$4i$', '$8$'], correct: 1, explanation: 'Using z₁²−z₂² = (z₁+z₂)(z₁−z₂): (4)(2i) = 8i.' },
            { type: 'msq', question: 'Which properties hold for multiplication of complex numbers? Select all.', options: ['Commutative', 'Associative', 'Closure', 'Distributive over addition'], correct: [0, 1, 2, 3], explanation: 'All four properties hold for complex multiplication.' },
            { type: 'mcq', question: '$(\\sqrt{3} + i)^2 = ?$', options: ['$2 + 2\\sqrt{3}i$', '$4 + 2\\sqrt{3}i$', '$2\\sqrt{3}i$', '$3 + 2i$'], correct: 0, explanation: '3 + 2i√3 + i² = 3+2i√3−1 = 2+2i√3.' },
            { type: 'text', question: 'Find $|z|^2$ if $z = 3 + 4i$.', answer: '25', explanation: '|z|² = 3² + 4² = 9 + 16 = 25.' },
            { type: 'mcq', question: 'The multiplicative identity for ℂ is:', options: ['$0+0i$', '$i$', '$1+0i$', '$1+i$'], correct: 2, explanation: 'z · (1+0i) = z for all z ∈ ℂ.' },
            { type: 'mcq', question: '$(a+ib)(a-ib) = ?$', options: ['$a^2 - b^2$', '$a^2 + b^2$', '$2ab$', '$a^2 + b^2 + 2abi$'], correct: 1, explanation: '(a+ib)(a−ib) = a² − (ib)² = a² + b² = |z|².' },
            { type: 'mcq', question: '$(3 + 2i)^2 = ?$', options: ['$5 + 12i$', '$13$', '$9 + 4i$', '$5 - 12i$'], correct: 0, explanation: '9 + 12i + 4i² = 9+12i−4 = 5+12i.' },
            { type: 'text', question: 'Simplify $i^{35}$.', answer: '-i', acceptedAnswers: ['0-i'], explanation: '35 = 4×8+3, so i³⁵ = i³ = −i.' },
            { type: 'mcq', question: 'If $z = 1 - i$, find $z^2 + \\bar{z}^2$.', options: ['$-4i$', '$4$', '$-4$', '$0$'], correct: 3, explanation: '$z^2 = (1-i)^2 = 1-2i+i^2 = -2i$. $\\bar{z} = 1+i$, so $\\bar{z}^2 = (1+i)^2 = 2i$. Sum: $-2i + 2i = 0$.' },
        ],
    },
    {
        id: 'division-inverse',
        title: 'Division & Multiplicative Inverse',
        subtitle: 'OPERATIONS',
        desc: 'Divide complex numbers by rationalising with the conjugate.',
        icon: '➗',
        color: '#f59e0b',
        learn: {
            title: 'Dividing Complex Numbers',
            rules: [
                {
                    title: 'Division via Multiplicative Inverse',
                    f: '\\frac{z_1}{z_2} = z_1 \\cdot z_2^{-1} = z_1 \\cdot \\frac{\\bar{z}_2}{|z_2|^2}',
                    d: 'To compute z₁/z₂, multiply numerator and denominator by the conjugate of the denominator. This removes i from the denominator.',
                    ex: 'z₁ = 6+3i, z₂ = 2−i.\nz₁/z₂ = (6+3i)/(2−i) × (2+i)/(2+i) = (12+6i+6i+3i²)/(4+1) = (12+12i−3)/5 = (9+12i)/5 = 9/5 + 12i/5.',
                    tip: 'Always multiply top and bottom by the conjugate of the denominator. The denominator becomes |z₂|², which is real.',
                },
                {
                    title: 'Expressing in a + ib Form',
                    f: '\\frac{5 + \\sqrt{2}\\,i}{1 - \\sqrt{2}\\,i} = 1 + 2\\sqrt{2}\\,i',
                    d: 'Multiply by (1+√2·i)/(1+√2·i): numerator becomes (5+√2·i)(1+√2·i) = 5+5√2·i+√2·i+2i² = 5+6√2·i−2 = 3+6√2·i. Denominator: 1+2 = 3. Result: (3+6√2·i)/3 = 1+2√2·i.',
                    ex: 'For i⁻³⁵: i⁻³⁵ = 1/i³⁵ = 1/i³ (since i³⁵ = i³) = 1/(−i) = (−i)/(−i·−i) = −i/(−1) = ... use i⁻¹ = −i directly: i⁻³⁵ = i^(−35) = i^(4×(−9)−35+36) = i^1 = i.',
                    tip: 'For i^(−n), first find i^n then take reciprocal: 1/i = −i, 1/i² = −1, 1/i³ = i, 1/i⁴ = 1.',
                },
                {
                    title: 'Key Results for Division',
                    f: '\\left|\\frac{z_1}{z_2}\\right| = \\frac{|z_1|}{|z_2|}, \\quad \\overline{\\left(\\frac{z_1}{z_2}\\right)} = \\frac{\\bar{z}_1}{\\bar{z}_2}',
                    d: 'Modulus of quotient = quotient of moduli. Conjugate of quotient = quotient of conjugates. These properties let you check answers quickly.',
                    ex: '|z₁/z₂| = |6+3i|/|2−i| = √45/√5 = √9 = 3.\nVerify: |9/5+12i/5| = √(81+144)/5 = √225/5 = 15/5 = 3 ✓',
                    tip: 'Use modulus properties to check: |answer| should equal |z₁|/|z₂|.',
                },
            ],
        },
        practice: [
            {
                question: 'Level 1: $\\frac{1}{i} = ?$',
                options: ['$i$', '$-i$', '$1$', '$-1$'],
                correct: 1,
                explanation: '1/i × i/i = i/i² = i/(−1) = −i.',
            },
            {
                question: 'Level 1: $\\frac{1}{2+i} = ?$',
                options: ['$\\frac{2-i}{5}$', '$\\frac{2+i}{5}$', '$\\frac{2-i}{3}$', '$\\frac{1}{2-i}$'],
                correct: 0,
                explanation: 'Multiply by (2−i)/(2−i): (2−i)/(4+1) = (2−i)/5.',
            },
            {
                question: 'Level 2: $\\frac{6 + 3i}{2 - i} = ?$',
                options: ['$\\frac{9}{5} + \\frac{12}{5}i$', '$3 + 3i$', '$3 - i$', '$\\frac{3}{5} + \\frac{12}{5}i$'],
                correct: 0,
                explanation: '(6+3i)(2+i)/((2−i)(2+i)) = (12+6i+6i+3i²)/5 = (12+12i−3)/5 = (9+12i)/5.',
            },
            {
                question: 'Level 2: $\\frac{5 + \\sqrt{2}\\,i}{1 - \\sqrt{2}\\,i} = ?$',
                options: ['$1 + 2\\sqrt{2}\\,i$', '$5 - 2i$', '$\\sqrt{2} + i$', '$3 + \\sqrt{2}\\,i$'],
                correct: 0,
                explanation: 'Multiply by (1+√2i)/(1+√2i): (5+√2i)(1+√2i)=5+5√2i+√2i+2i²=3+6√2i. Denominator: 1+2=3. Result: 1+2√2i.',
            },
            {
                question: 'Level 2: Multiplicative inverse of $4 - 3i$ is:',
                options: ['$\\frac{4}{25} + \\frac{3}{25}i$', '$4 + 3i$', '$\\frac{1}{25}$', '$\\frac{4}{7} + \\frac{3}{7}i$'],
                correct: 0,
                explanation: '(4−3i)⁻¹ = (4+3i)/(16+9) = (4+3i)/25 = 4/25 + 3i/25.',
            },
            {
                question: 'Level 3: $i^{-35} = ?$',
                options: ['$i$', '$-i$', '$1$', '$-1$'],
                correct: 0,
                explanation: 'i⁻³⁵ = 1/i³⁵. 35 = 4×8+3, so i³⁵ = i³ = −i. 1/(−i) = i/(i×(−i)) = i/1 = i.',
            },
            {
                question: 'Level 3: $\\frac{(3 - i\\sqrt{5})(3 + i\\sqrt{5})}{(\\sqrt{3} + \\sqrt{2}\\,i)(\\sqrt{3} - \\sqrt{2}\\,i)} = ?$',
                options: ['$\\frac{14}{5}$', '$\\frac{5}{14}$', '$14$', '$5$'],
                correct: 0,
                explanation: 'Numerator: 9+5=14. Denominator: 3+2=5. Quotient: 14/5.',
            },
            {
                question: 'Level 3: Express $\\frac{1+i}{1-i}$ in $a+ib$ form.',
                options: ['$0 + i$', '$1 + 0i$', '$0 - i$', '$\\frac{1}{2} + \\frac{1}{2}i$'],
                correct: 0,
                explanation: '(1+i)²/((1−i)(1+i)) = (1+2i−1)/2 = 2i/2 = i = 0+i.',
            },
        ],
        assessment: [
            { type: 'mcq', question: '$\\frac{3 + 4i}{2 - i} = ?$', options: ['$\\frac{2}{5} + \\frac{11}{5}i$', '$\\frac{2+11i}{5}$', '$\\frac{10+11i}{5}$', 'A and B are equal'], correct: 3, explanation: '(3+4i)(2+i)/5 = (6+3i+8i+4i²)/5 = (6+11i−4)/5 = (2+11i)/5 = 2/5+11i/5. A and B are the same.' },
            { type: 'text', question: 'Find the multiplicative inverse of $-i$.', answer: 'i', acceptedAnswers: ['0+i'], explanation: '(−i)⁻¹ = (−i)/(i·(−i)) = (−i)/1 = ... use: 1/(−i) × (i)/(i) = i/(−i²) = i/1 = i.' },
            { type: 'mcq', question: '$i^{-1} = ?$', options: ['$i$', '$-i$', '$-1$', '$1$'], correct: 1, explanation: '1/i = i/i² = i/(−1) = −i.' },
            { type: 'mcq', question: 'Multiplicative inverse of $\\sqrt{5} + 3i$ is:', options: ['$\\frac{\\sqrt{5}}{14} - \\frac{3}{14}i$', '$\\frac{\\sqrt{5}}{14} + \\frac{3}{14}i$', '$\\sqrt{5} - 3i$', '$\\frac{1}{14}$'], correct: 0, explanation: '|z|² = 5+9=14. z⁻¹ = (√5−3i)/14.' },
            { type: 'msq', question: 'Which equal $\\frac{1}{i^2}$? Select all.', options: ['$i^{-2}$', '$-1$', '$\\frac{1}{-1}$', '$i^2$'], correct: [0, 1, 2], explanation: '1/i² = 1/(−1) = −1 = i⁻². All three options A, B, C are equivalent.' },
            { type: 'mcq', question: '$\\frac{2 + 3i}{1 + i} = ?$', options: ['$\\frac{5}{2} + \\frac{1}{2}i$', '$\\frac{5 - i}{2}$', '$\\frac{5+i}{2}$', 'A and B are equal'], correct: 3, explanation: '(2+3i)(1−i)/2=(2−2i+3i−3i²)/2=(2+i+3)/2=(5+i)/2. A and B are equal.' },
            { type: 'text', question: 'Compute the real part of $\\frac{4+i}{2-i}$.', answer: '7/5', acceptedAnswers: ['1.4'], explanation: '(4+i)(2+i)/5=(8+4i+2i+i²)/5=(8+6i−1)/5=(7+6i)/5. Re = 7/5.' },
            { type: 'mcq', question: 'For non-zero $z$, $z \\cdot z^{-1} = ?$', options: ['$0$', '$z^2$', '$1 + 0i$', '$|z|$'], correct: 2, explanation: 'By definition of multiplicative inverse, z · z⁻¹ = 1 = 1+0i.' },
            { type: 'mcq', question: '$\\frac{2+i}{1-2i} = ?$', options: ['$1$', '$i$', '$-i$', '$-1$'], correct: 1, explanation: 'Multiply by $(1+2i)/(1+2i)$: $(2+i)(1+2i)/(1+4) = (2+4i+i+2i^2)/5 = (2+5i-2)/5 = 5i/5 = i$.' },
            { type: 'mcq', question: 'Express $\\frac{1}{1+i}$ in $a+ib$ form.', options: ['$\\frac{1}{2} - \\frac{1}{2}i$', '$\\frac{1}{2} + \\frac{1}{2}i$', '$1 - i$', '$\\frac{1+i}{2}$'], correct: 0, explanation: '(1−i)/((1+i)(1−i)) = (1−i)/2.' },
            { type: 'text', question: 'Find the imaginary part of $\\frac{6+3i}{2-i}$.', answer: '12/5', acceptedAnswers: ['2.4'], explanation: '$(6+3i)(2+i)/5 = (12+6i+6i+3i^2)/5 = (9+12i)/5$. Im $= 12/5$.' },
            { type: 'mcq', question: '$\\frac{1-i}{1+i} = ?$', options: ['$-i$', '$i$', '$0-i$', 'A and C are equal'], correct: 3, explanation: '(1−i)²/(1+1) = (1−2i−1)/2 = −2i/2 = −i = 0−i. A and C are equal.' },
        ],
    },
    {
        id: 'powers-of-i',
        title: 'Powers of i & Square Roots of Negatives',
        subtitle: 'PATTERNS',
        desc: 'Evaluate any power of i using the 4-cycle and compute square roots of negative numbers.',
        icon: '⚡',
        color: '#ec4899',
        learn: {
            title: 'The i-Cycle and Square Roots',
            rules: [
                {
                    title: 'The 4-Cycle of Powers of i',
                    f: 'i^{4k}=1,\\; i^{4k+1}=i,\\; i^{4k+2}=-1,\\; i^{4k+3}=-i',
                    d: 'i¹=i, i²=−1, i³=−i, i⁴=1, then the cycle repeats. For any integer n, divide n by 4 and use the remainder (0→1, 1→i, 2→−1, 3→−i). For negative powers: i⁻¹=−i, i⁻²=−1, i⁻³=i, i⁻⁴=1.',
                    ex: 'i⁹ = i^(4×2+1) = i. \ni¹⁰⁰ = i^(4×25) = 1.\ni⁻³⁵ = i^(4×(−9)+1) = i.',
                    tip: 'Remainder trick: n mod 4. Write n = 4q + r where r ∈ {0,1,2,3}, then iⁿ = iʳ.',
                },
                {
                    title: 'Square Roots of Negative Numbers',
                    f: '\\sqrt{-a} = \\sqrt{a}\\, i \\quad (a > 0)',
                    d: 'For positive a, √(−a) = i√a. The symbol √(−a) represents i√a (the positive imaginary root). CAUTION: √(−a)×√(−b) ≠ √(ab) when both a,b > 0. Correct: √(−a)×√(−b) = (i√a)(i√b) = i²√(ab) = −√(ab).',
                    ex: '√(−3) = i√3.\n√(−3) × √(−3) = i√3 × i√3 = i²·3 = −3 ✓\nDo NOT write √(−3)×√(−3) = √(9) = 3 ✗',
                    tip: 'Convert to i-form FIRST, then multiply. Never multiply under the square root when both numbers are negative.',
                },
                {
                    title: 'Sums of Powers of i',
                    f: 'i + i^2 + i^3 + i^4 = 0',
                    d: 'i + (−1) + (−i) + 1 = 0. Any sum of 4 consecutive powers of i is 0. Use this shortcut for long sums.',
                    ex: 'i¹ + i² + i³ + ... + i¹⁰⁰ = 25 × (i+i²+i³+i⁴) = 25 × 0 = 0.\ni⁹ + i¹⁹ = i + i³ = i + (−i) = 0.',
                    tip: 'Group terms in sets of 4 consecutive powers: each group sums to 0. Handle any leftover terms separately.',
                },
            ],
        },
        practice: [
            {
                question: 'Level 1: $i^{100} = ?$',
                options: ['$1$', '$i$', '$-1$', '$-i$'],
                correct: 0,
                explanation: '100 = 4×25+0. i^(4k) = 1.',
            },
            {
                question: 'Level 1: $\\sqrt{-16} = ?$',
                options: ['$4$', '$-4$', '$4i$', '$-4i$'],
                correct: 2,
                explanation: '√(−16) = √16 × √(−1) = 4i.',
            },
            {
                question: 'Level 2: $i^{39} = ?$',
                options: ['$1$', '$i$', '$-1$', '$-i$'],
                correct: 3,
                explanation: '39 = 4×9+3. i³ = −i.',
            },
            {
                question: 'Level 2: $\\sqrt{-3} \\times \\sqrt{-3} = ?$',
                options: ['$3$', '$-3$', '$\\sqrt{3}$', '$3i$'],
                correct: 1,
                explanation: '(i√3)(i√3) = i²·3 = −3. Never use √(−3)×√(−3)=√9=3.',
            },
            {
                question: 'Level 2: $i + i^2 + i^3 + i^4 + i^5 = ?$',
                options: ['$0$', '$1$', '$i$', '$1 + i$'],
                correct: 2,
                explanation: 'i + i² + i³ + i⁴ = 0. Remaining: i⁵ = i. Total = i.',
            },
            {
                question: 'Level 3: $i^{-39} = ?$',
                options: ['$i$', '$-i$', '$1$', '$-1$'],
                correct: 0,
                explanation: 'i⁻³⁹ = 1/i³⁹ = 1/(−i) = i/(i·(−i)) = i/1 = i. Or: −39 ≡ 1 (mod 4) since −39+40=1. So i⁻³⁹=i.',
            },
            {
                question: 'Level 3: $\\sum_{k=1}^{48} i^k = ?$',
                options: ['$0$', '$1$', '$-1$', '$i$'],
                correct: 0,
                explanation: '48 = 4×12. Sum = 12×(i+i²+i³+i⁴) = 12×0 = 0.',
            },
            {
                question: 'Level 3: Which is NOT correct?',
                options: ['$\\sqrt{-4} = 2i$', '$\\sqrt{-1}\\cdot\\sqrt{-1} = -1$', '$\\sqrt{-4}\\cdot\\sqrt{-9} = 6$', '$i^{4n} = 1$ for all integers $n$'],
                correct: 2,
                explanation: '√(−4)·√(−9) = 2i·3i = 6i² = −6, NOT 6. The other three statements are correct.',
            },
        ],
        assessment: [
            { type: 'mcq', question: '$i^{55} = ?$', options: ['$i$', '$-i$', '$1$', '$-1$'], correct: 1, explanation: '55 = 4×13+3. i³ = −i.' },
            { type: 'text', question: 'Find $i^{200}$.', answer: '1', explanation: '200 = 4×50. i^(4k) = 1.' },
            { type: 'mcq', question: '$\\sqrt{-25} = ?$', options: ['$-5$', '$5$', '$5i$', '$-5i$'], correct: 2, explanation: '√(−25) = i√25 = 5i.' },
            { type: 'mcq', question: '$\\sqrt{-2} \\times \\sqrt{-8} = ?$', options: ['$4$', '$-4$', '$4i$', '$2i$'], correct: 1, explanation: '(i√2)(i√8) = i²√16 = −4.' },
            { type: 'msq', question: 'Which equal $-1$? Select all that apply.', options: ['$i^2$', '$i^6$', '$i^{10}$', '$i^{4}$'], correct: [0, 1, 2], explanation: 'i² = i^(4k+2) = −1 for k=0,1,2. i⁴ = 1, not −1.' },
            { type: 'mcq', question: '$i^{-1} + i^{-2} + i^{-3} + i^{-4} = ?$', options: ['$0$', '$1$', '$-1$', '$-i$'], correct: 0, explanation: 'i⁻¹=−i, i⁻²=−1, i⁻³=i, i⁻⁴=1. Sum: −i+(−1)+i+1 = 0.' },
            { type: 'text', question: 'Evaluate $i^{4k+3}$ for any integer $k$.', answer: '-i', explanation: 'By the 4-cycle rule, i^(4k+3) = i³ = −i.' },
            { type: 'mcq', question: 'The value of $1 + i^2 + i^4 + i^6 + i^8$ is:', options: ['$0$', '$1$', '$5$', '$-1$'], correct: 1, explanation: '1+(−1)+1+(−1)+1 = 1.' },
            { type: 'mcq', question: '$(-i)(2i)(-\\frac{1}{8}i)^3 = ?$', options: ['$\\frac{1}{256}i$', '$\\frac{-1}{256}i$', '$\\frac{1}{256}$', '$\\frac{-1}{256}$'], correct: 0, explanation: '(−i)(2i)(−i/8)³ = 2×(1/512)×i⁵ = (2/512)i = i/256.' },
            { type: 'mcq', question: '$i^{1} + i^{2} + \\ldots + i^{20} = ?$', options: ['$0$', '$1$', '$-1$', '$20i$'], correct: 0, explanation: '20 = 4×5. Groups of 4 each sum to 0. Total = 0.' },
            { type: 'text', question: 'Express $\\sqrt{-4} + \\sqrt{-9}$ in $a+ib$ form.', answer: '0+5i', acceptedAnswers: ['5i'], explanation: '2i + 3i = 5i = 0+5i.' },
            { type: 'mcq', question: 'For which value of $n$ is $i^n = -1$?', options: ['$n=1$', '$n=3$', '$n=6$', '$n=4$'], correct: 2, explanation: '6 = 4×1+2. i^(4k+2) = −1. So i⁶ = −1.' },
        ],
    },
    {
        id: 'modulus-conjugate',
        title: 'Modulus & Conjugate',
        subtitle: 'KEY PROPERTIES',
        desc: 'Compute |z| and z̄ and apply their properties including z·z̄ = |z|².',
        icon: '📏',
        color: '#3b82f6',
        learn: {
            title: 'Modulus and Conjugate of a Complex Number',
            rules: [
                {
                    title: 'Modulus of a Complex Number',
                    f: '|z| = \\sqrt{a^2 + b^2} \\quad \\text{for } z = a + ib',
                    d: 'The modulus |z| is a non-negative real number equal to the distance from the origin to the point (a,b) in the Argand plane. Key properties: |z₁z₂| = |z₁||z₂|, |z₁/z₂| = |z₁|/|z₂|, |z| = |z̄|, |z|² = z·z̄.',
                    ex: '|3 + i| = √(9+1) = √10.\n|2 − 5i| = √(4+25) = √29.\n|z| = 0 iff z = 0.',
                    tip: '|z| is always ≥ 0 and is a real number. |z|² = a² + b² = z·z̄.',
                },
                {
                    title: 'Conjugate of a Complex Number',
                    f: '\\bar{z} = a - ib \\quad \\text{for } z = a + ib',
                    d: 'The conjugate z̄ negates the imaginary part. In the Argand plane, z̄ is the reflection of z in the real axis. Properties: z+z̄ = 2a (real), z−z̄ = 2ib (imaginary), z·z̄ = |z|², z̄₁z̄₂ = z̄₁z̄₂, conjugate of z̄ = z.',
                    ex: 'z = 3+i → z̄ = 3−i.\nz = 2−5i → z̄ = 2+5i.\nz+z̄ = 6 = 2·Re(z) ✓',
                    tip: 'Use z·z̄ = |z|² to find moduli quickly: (3+4i)(3−4i) = 9+16 = 25, so |3+4i| = 5.',
                },
                {
                    title: 'Multiplicative Inverse via Conjugate',
                    f: 'z^{-1} = \\frac{\\bar{z}}{|z|^2}',
                    d: 'The multiplicative inverse of z is z̄/|z|². This follows from z·z̄ = |z|², so z·(z̄/|z|²) = |z|²/|z|² = 1. Useful properties: z⁻¹ = z̄/|z|², and |z⁻¹| = 1/|z|.',
                    ex: 'z = 2−3i. z̄ = 2+3i, |z|² = 4+9 = 13.\nz⁻¹ = (2+3i)/13 = 2/13 + 3i/13.',
                    tip: 'Memorise: z · z⁻¹ = 1, and z⁻¹ = z̄/|z|². This avoids expanding (a+ib)⁻¹ by brute force.',
                },
            ],
        },
        practice: [
            {
                question: 'Level 1: $|3 + 4i| = ?$',
                options: ['$3$', '$4$', '$5$', '$7$'],
                correct: 2,
                explanation: '√(9+16) = √25 = 5.',
            },
            {
                question: 'Level 1: If $z = 5 - 2i$, then $\\bar{z} = ?$',
                options: ['$-5 + 2i$', '$5 + 2i$', '$-5 - 2i$', '$2 + 5i$'],
                correct: 1,
                explanation: 'Conjugate negates the imaginary part: 5−2i → 5+2i.',
            },
            {
                question: 'Level 2: $z \\cdot \\bar{z}$ for $z = 3 + 4i$ equals:',
                options: ['$7$', '$1$', '$25$', '$12i$'],
                correct: 2,
                explanation: 'z·z̄ = |z|² = 9+16 = 25.',
            },
            {
                question: 'Level 2: If $|z| = 5$ and $z = 3 + bi$, find $b$.',
                options: ['$4$', '$-4$', '$\\pm 4$', '$2$'],
                correct: 2,
                explanation: '9+b²=25 → b²=16 → b = ±4.',
            },
            {
                question: 'Level 2: The conjugate of $\\frac{3-2i}{(1+2i)(2-i)}$ lies in the form:',
                options: ['$\\frac{3+2i}{(1-2i)(2+i)}$', '$\\frac{3+2i}{(1+2i)(2-i)}$', '$\\frac{3-2i}{(1-2i)(2+i)}$', '$-\\frac{3+2i}{5}$'],
                correct: 0,
                explanation: 'Conjugate of a quotient = quotient of conjugates: (3̄−2i)/(product̄) = (3+2i)/((1−2i)(2+i)).',
            },
            {
                question: 'Level 3: If $z = x + iy$ and $|z| = 1$, then $x^2 + y^2 = ?$',
                options: ['$0$', '$2$', '$1$', '$\\sqrt{2}$'],
                correct: 2,
                explanation: '|z|² = x²+y². |z| = 1 → |z|² = 1 → x²+y² = 1.',
            },
            {
                question: 'Level 3: Find $|z_1 z_2|$ where $z_1 = 3+4i$ and $z_2 = 5-12i$.',
                options: ['$65$', '$13$', '$5$', '$85$'],
                correct: 0,
                explanation: '|z₁| = 5, |z₂| = √(25+144) = 13. |z₁z₂| = 5×13 = 65.',
            },
            {
                question: 'Level 3: Multiplicative inverse of $2-3i$ is:',
                options: ['$\\frac{2}{13} + \\frac{3}{13}i$', '$\\frac{2}{13} - \\frac{3}{13}i$', '$2+3i$', '$\\frac{1}{13}$'],
                correct: 0,
                explanation: 'z⁻¹ = z̄/|z|² = (2+3i)/13 = 2/13 + 3/13·i.',
            },
        ],
        assessment: [
            { type: 'mcq', question: '$|2 - 5i| = ?$', options: ['$3$', '$7$', '$\\sqrt{29}$', '$\\sqrt{21}$'], correct: 2, explanation: '√(4+25) = √29.' },
            { type: 'text', question: 'Find $z \\cdot \\bar{z}$ for $z = 1 + i$.', answer: '2', explanation: '(1+i)(1−i) = 1+1 = 2 = |z|².' },
            { type: 'mcq', question: 'If $z = 3 + i$, then $|z|^2 = ?$', options: ['$9$', '$10$', '$4$', '$\\sqrt{10}$'], correct: 1, explanation: '|z|² = 9+1 = 10.' },
            { type: 'mcq', question: 'The conjugate of $-3i - 5$ is:', options: ['$3i - 5$', '$-3i + 5$', '$3i + 5$', '$5 + 3i$'], correct: 0, explanation: 'z = −5 − 3i. z̄ = −5+3i = 3i−5.' },
            { type: 'msq', question: 'For $z = a+ib$ and $\\bar{z} = a-ib$, which are TRUE? Select all.', options: ['$z + \\bar{z} = 2a$', '$z - \\bar{z} = 2ib$', '$|z| = |\\bar{z}|$', '$z \\cdot \\bar{z} = a^2 - b^2$'], correct: [0, 1, 2], explanation: 'z+z̄=2a ✓, z−z̄=2ib ✓, |z|=|z̄| ✓. But z·z̄ = a²+b² (not a²−b²), so D is false.' },
            { type: 'mcq', question: 'Find the multiplicative inverse of $4 - 3i$.', options: ['$\\frac{4+3i}{25}$', '$\\frac{4-3i}{25}$', '$4+3i$', '$\\frac{1}{7}$'], correct: 0, explanation: 'z⁻¹ = (4+3i)/(16+9) = (4+3i)/25.' },
            { type: 'text', question: 'If $z = 1 - i$, compute $|z|$.', answer: '√2', acceptedAnswers: ['sqrt(2)', '1.414'], explanation: '|z| = √(1+1) = √2.' },
            { type: 'mcq', question: 'Which is TRUE for any non-zero complex $z$?', options: ['$z + \\bar{z}$ is imaginary', '$z \\cdot \\bar{z}$ is real', '$|z|$ can be negative', '$\\bar{z} = -z$'], correct: 1, explanation: 'z·z̄ = a²+b² ∈ ℝ (always real and non-negative).' },
            { type: 'mcq', question: 'If $x + iy = \\frac{a+ib}{a-ib}$, then $x^2 + y^2 = ?$', options: ['$\\frac{a^2+b^2}{a^2-b^2}$', '$1$', '$2$', '$a^2+b^2$'], correct: 1, explanation: '|x+iy|² = |a+ib|²/|a−ib|² = (a²+b²)/(a²+b²) = 1.' },
            { type: 'mcq', question: '$\\overline{z_1 z_2} = ?$', options: ['$z_1 z_2$', '$\\bar{z}_1 \\bar{z}_2$', '$\\bar{z}_1 z_2$', '$z_1 \\bar{z}_2$'], correct: 1, explanation: 'Conjugate of a product = product of conjugates.' },
            { type: 'text', question: 'Find the real part of $z \\cdot \\bar{z}$ for $z = 2+3i$.', answer: '13', explanation: 'z·z̄ = |z|² = 4+9 = 13 (purely real).' },
            { type: 'mcq', question: 'Find the modulus of $\\frac{1+i}{1-i}$.', options: ['$0$', '$1$', '$\\sqrt{2}$', '$2$'], correct: 1, explanation: '|(1+i)/(1−i)| = |1+i|/|1−i| = √2/√2 = 1.' },
        ],
    },
    {
        id: 'argand-plane',
        title: 'Argand Plane & Geometric Representation',
        subtitle: 'GEOMETRY',
        desc: 'Plot complex numbers in the Argand plane and interpret modulus and conjugate geometrically.',
        icon: '🗺️',
        color: '#10b981',
        learn: {
            title: 'The Argand Plane',
            rules: [
                {
                    title: 'The Complex Plane',
                    f: 'z = a + ib \\longleftrightarrow P(a,\\, b)',
                    d: 'The Argand (complex) plane is the XY-plane where the x-axis is the real axis and the y-axis is the imaginary axis. Complex number z = a+ib maps to point P(a, b). The real axis contains all purely real numbers (b=0) and the imaginary axis contains purely imaginary numbers (a=0).',
                    ex: '2+4i → A(2,4). −2+3i → B(−2,3). 0+i → C(0,1). 2+0i → D(2,0).\n−5−2i → E(−5,−2). 1−2i → F(1,−2).',
                    tip: 'The real part gives the x-coordinate and the imaginary part gives the y-coordinate.',
                },
                {
                    title: 'Modulus as Distance from Origin',
                    f: '|z| = \\sqrt{a^2+b^2} = OP',
                    d: 'The modulus |z| is the Euclidean distance from the origin O(0,0) to the point P(a,b). This is the magnitude or absolute value of the complex number. A circle of radius r centred at origin = set of z with |z| = r.',
                    ex: '|3+4i| = √(9+16) = 5 = distance from O to (3,4).\nAll z with |z| = 1 form the unit circle in the Argand plane.',
                    tip: '|z| is always non-negative. |z| = 0 iff z = 0 (the origin).',
                },
                {
                    title: 'Conjugate as Reflection',
                    f: '\\bar{z} = a - ib \\longleftrightarrow Q(a,\\, -b)',
                    d: 'The conjugate z̄ corresponds to the point Q(a, −b), which is the reflection of P(a, b) in the real axis (x-axis). So z and z̄ are symmetric about the real axis in the Argand plane.',
                    ex: 'z = 3+4i → P(3,4). z̄ = 3−4i → Q(3,−4). Q is the mirror image of P across the x-axis.',
                    tip: 'To plot z̄: keep the real part the same, flip the sign of the imaginary part — same x, opposite y.',
                },
            ],
        },
        practice: [
            {
                question: 'Level 1: Which point represents $-3 + 2i$ in the Argand plane?',
                options: ['$(2, -3)$', '$(-3, 2)$', '$(-3, -2)$', '$(3, 2)$'],
                correct: 1,
                explanation: 'a+ib → point (a,b). −3+2i → (−3, 2).',
            },
            {
                question: 'Level 1: The modulus of $5 + 12i$ is:',
                options: ['$7$', '$17$', '$13$', '$\\sqrt{119}$'],
                correct: 2,
                explanation: '√(25+144) = √169 = 13.',
            },
            {
                question: 'Level 2: In the Argand plane, $z = a+ib$ and $\\bar{z}$ are related by:',
                options: ['Reflection in the imaginary axis', 'Reflection in the real axis', 'Rotation by 90°', 'Reflection in the origin'],
                correct: 1,
                explanation: 'z̄ = a−ib corresponds to (a,−b), the mirror image of (a,b) across the x-axis (real axis).',
            },
            {
                question: 'Level 2: Which complex number lies on the imaginary axis?',
                options: ['$3 + i$', '$0 + 5i$', '$2 + 0i$', '$1 - i$'],
                correct: 1,
                explanation: 'Imaginary axis = y-axis → real part = 0. 0+5i has Re = 0.',
            },
            {
                question: 'Level 2: Distance between $z_1 = 3+4i$ and $z_2 = 0+0i$ is:',
                options: ['$5$', '$7$', '$1$', '$\\sqrt{7}$'],
                correct: 0,
                explanation: '|z₁ − z₂| = |3+4i| = √(9+16) = 5.',
            },
            {
                question: 'Level 3: All complex numbers $z$ with $|z| = 2$ lie on:',
                options: ['A line parallel to x-axis', 'A circle of radius 2 centred at origin', 'The real axis', 'A parabola'],
                correct: 1,
                explanation: '|z| = 2 means √(a²+b²) = 2, i.e. a²+b² = 4 — a circle of radius 2 centred at O.',
            },
            {
                question: 'Level 3: If $z = x + iy$ and $|z + \\bar{z}| = 4$, then $x$ equals:',
                options: ['$2$', '$\\pm 2$', '$4$', '$\\pm 4$'],
                correct: 1,
                explanation: 'z+z̄ = 2x. |2x| = 4 → |x| = 2 → x = ±2.',
            },
            {
                question: 'Level 3: The point $P$ representing $z = 2+3i$ and $Q$ representing $\\bar{z}$ are:',
                options: ['Symmetric about the imaginary axis', 'Symmetric about the real axis', 'At the same point', 'Symmetric about the origin'],
                correct: 1,
                explanation: 'z̄ = 2−3i → Q(2,−3). P(2,3) and Q(2,−3) are symmetric about the real (x-) axis.',
            },
        ],
        assessment: [
            { type: 'mcq', question: 'The complex number $5 + 0i$ lies on:', options: ['Imaginary axis', 'Real axis', 'First quadrant', 'Origin'], correct: 1, explanation: 'b = 0 → the point (5,0) lies on the x-axis = real axis.' },
            { type: 'text', question: 'Find the modulus of $z = -3 - 4i$.', answer: '5', explanation: '√(9+16) = √25 = 5.' },
            { type: 'mcq', question: 'Which quadrant contains $-2 + 3i$?', options: ['I', 'II', 'III', 'IV'], correct: 1, explanation: 'a = −2 < 0, b = 3 > 0 → Second quadrant.' },
            { type: 'mcq', question: 'In the Argand plane, $|z|$ represents:', options: ['The imaginary part', 'The real part', 'The distance from origin to point P(a,b)', 'The angle from x-axis'], correct: 2, explanation: '|z| = √(a²+b²) = distance OP.' },
            { type: 'msq', question: 'Which lie on the real axis in the Argand plane? Select all.', options: ['$5 + 0i$', '$0 - 3i$', '$\\pi + 0i$', '$-\\sqrt{2} + 0i$'], correct: [0, 2, 3], explanation: 'Real axis = Im(z) = 0. Options A (5), C (π), D (−√2) all have Im = 0.' },
            { type: 'mcq', question: 'If $P(3,4)$ represents $z$ and $Q$ represents $\\bar{z}$, then Q is:', options: ['$(3, 4)$', '$(-3, 4)$', '$(3, -4)$', '$(-3, -4)$'], correct: 2, explanation: 'Conjugate negates imaginary part: z̄ → (3, −4).' },
            { type: 'text', question: 'Compute $|z|$ for $z = 0 + 7i$.', answer: '7', explanation: '|0+7i| = √(0+49) = 7.' },
            { type: 'mcq', question: 'The modulus of $z = a + ib$ satisfies:', options: ['$|z| \\ge 0$ always', '$|z| > 0$ always', '$|z| \\le 1$ always', '$|z| = a + b$'], correct: 0, explanation: '|z| = √(a²+b²) ≥ 0 (equals 0 only when z = 0).' },
            { type: 'mcq', question: 'All $z$ with $|z| = 1$ form:', options: ['The real axis', 'A line', 'The unit circle centred at origin', 'The imaginary axis'], correct: 2, explanation: 'a²+b² = 1 is a circle of radius 1 centred at origin.' },
            { type: 'mcq', question: 'The point representing $z$ in the Argand plane has coordinates:', options: ['$(|z|, \\text{arg}(z))$', '$(\\text{Re}(z), \\text{Im}(z))$', '$(\\text{Im}(z), \\text{Re}(z))$', '$(|z|, |\\bar{z}|)$'], correct: 1, explanation: 'z = a+ib → point (a, b) = (Re(z), Im(z)).' },
            { type: 'text', question: 'If $z_1 = 1+i$ and $z_2 = 1-i$, find $|z_1 - z_2|$.', answer: '2', explanation: 'z₁−z₂ = 2i. |2i| = 2.' },
            { type: 'mcq', question: 'In the Argand plane, the y-axis is called:', options: ['Real axis', 'Imaginary axis', 'Modulus axis', 'Argument axis'], correct: 1, explanation: 'The y-axis of the Argand plane corresponds to purely imaginary numbers — it is the imaginary axis.' },
        ],
    },
];
