export const cards5W1H = [
    {
        q: 'WHAT',
        label: 'What are Lines and Angles?',
        icon: '📏',
        gradFrom: '#10b981',
        gradTo: '#34d399',
        shadow: 'rgba(16,185,129,0.35)',
        content: `A line is a straight path that extends infinitely in both directions, while an angle is formed when two rays or lines meet at a common point called the vertex. Together, lines and angles form the fundamental framework for all geometric shapes and spatial reasoning.`,
        fact: '💡 A straight line technically forms an angle of exactly 180°, known as a straight angle.',
    },
    {
        q: 'WHY',
        label: 'Why do we study them?',
        icon: '🎯',
        gradFrom: '#f59e0b',
        gradTo: '#fbbf24',
        shadow: 'rgba(245,158,11,0.35)',
        content: `Understanding lines and angles is crucial for building sturdy structures, designing everyday objects, and navigating the physical world. It helps us calculate distances, determine positions, and understand the relationships between different parts of a structure.`,
        fact: '💡 Without precise calculation of angles, simple tasks like building a sloping roof or adjusting a telescope would be impossible!',
    },
    {
        q: 'WHO',
        label: 'Who uses them?',
        icon: '👷',
        gradFrom: '#f43f5e',
        gradTo: '#fb7185',
        shadow: 'rgba(244,63,94,0.35)',
        content: `Architects use angles to design stable and aesthetically pleasing buildings. Civil engineers use transversals and parallel lines to lay out roads and bridges. Carpenters, astronomers, and even video game developers constantly rely on angles to position objects perfectly.`,
        fact: '💡 Surveyors measure angles using a specialized tool called a theodolite to map landscapes accurately.',
    },
    {
        q: 'WHERE',
        label: 'Where do we find them?',
        icon: '🌍',
        gradFrom: '#6366f1',
        gradTo: '#818cf8',
        shadow: 'rgba(99,102,241,0.35)',
        content: `Lines and angles are everywhere! You can spot parallel lines in railway tracks and the opposite edges of a book. Intersecting lines form the cross on a windowpane. The hands of a clock constantly form different angles as time passes.`,
        fact: '💡 Look closely at a scissor\'s blades—they form a pair of vertically opposite angles that are always equal!',
    },
    {
        q: 'WHEN',
        label: 'When do angles form?',
        icon: '⏱️',
        gradFrom: '#8b5cf6',
        gradTo: '#a78bfa',
        shadow: 'rgba(139,92,246,0.35)',
        content: `An angle is formed immediately whenever two line segments or rays intersect at a single point. If a transversal straight line crosses two or more parallel lines, it instantly creates a set of matching corresponding and alternate angles.`,
        fact: '💡 When you bend your elbow or knee, your bones act as line segments meeting at a vertex, creating a measurable angle!',
    },
    {
        q: 'HOW',
        label: 'How do we classify them?',
        icon: '⚙️',
        gradFrom: '#0ea5e9',
        gradTo: '#38bdf8',
        shadow: 'rgba(14,165,233,0.35)',
        content: `Angles are classified by size: Acute (<90°), Right (=90°), Obtuse (>90° and <180°), Straight (=180°), and Reflex (>180°). Pairs of lines can be Intersecting, Parallel, or Perpendicular. When pairs of angles sum to 90° they are Complementary; if they sum to 180° they are Supplementary.`,
        fact: '💡 The term "acute" means sharp, which makes sense since acute angles look like sharp points!',
    }
];
