// ECFTerminologyData.js — 16 key terms + formulas for Electric Charges and Fields

export const ECFTerminologyData = [
    {
        id: 'electric-charge',
        icon: '⚡',
        term: 'Electric Charge (q)',
        color: '#4a2c8a',
        type: 'Fundamental Property',
        definition: 'An intrinsic property of matter that causes it to experience force in an electromagnetic field. Exists as positive (+) or negative (−). SI unit: Coulomb (C).',
        formula: 'q = ne',
        formulaNote: 'n = integer, e = 1.6 × 10⁻¹⁹ C',
        example: 'A proton has charge +e = +1.6 × 10⁻¹⁹ C. An electron has −e. A body with 3 excess electrons has q = −3e = −4.8 × 10⁻¹⁹ C.',
        neetTip: 'Charge is always conserved in any process. The algebraic sum of charges in an isolated system is constant.'
    },
    {
        id: 'quantisation',
        icon: '🔢',
        term: 'Quantisation of Charge',
        color: '#be123c',
        type: 'Fundamental Law',
        definition: 'Electric charge exists only in discrete multiples of the elementary charge e. You cannot have half an electron\'s charge. q = ±1e, ±2e, ±3e… never a fraction.',
        formula: 'q = ne, n ∈ ℤ',
        formulaNote: 'e = 1.6 × 10⁻¹⁹ C (elementary charge)',
        example: 'A glass rod rubbed with silk loses 10⁹ electrons. Its charge = +10⁹ × 1.6 × 10⁻¹⁹ = +1.6 × 10⁻¹⁰ C.',
        neetTip: 'NEET trap: At macroscopic scale, we treat charge as continuous (ρ, σ, λ) even though it\'s quantised — this approximation is valid when n is huge.'
    },
    {
        id: 'conservation',
        icon: '♻️',
        term: 'Conservation of Charge',
        color: '#0369a1',
        type: 'Fundamental Law',
        definition: 'The total electric charge of an isolated system remains constant over time. Charge can be transferred but never created or destroyed.',
        formula: 'Σq_initial = Σq_final',
        formulaNote: 'Valid for any isolated system',
        example: 'Pair production: γ → e⁻ + e⁺. Net charge before = 0 (photon), after = −e + e = 0. ✓ Conservation holds.',
        neetTip: 'When two identical conducting spheres are touched and separated, each gets half the total charge: q_each = (q₁ + q₂)/2.'
    },
    {
        id: 'coulombs-force',
        icon: '⚖️',
        term: "Coulomb's Law",
        color: '#d97706',
        type: 'Core Law',
        definition: 'The electrostatic force between two point charges is directly proportional to the product of charges and inversely proportional to the square of the distance between them.',
        formula: 'F = kq₁q₂/r²',
        formulaNote: 'k = 9 × 10⁹ N·m²/C² = 1/(4πε₀)',
        example: 'Two charges 2 μC and 3 μC are 30 cm apart. F = 9×10⁹ × (2×10⁻⁶)(3×10⁻⁶) / (0.3)² = 0.6 N.',
        neetTip: 'Force direction: along the line joining the charges. Positive F = repulsion; Negative F = attraction. Always use magnitude in numeric problems.'
    },
    {
        id: 'permittivity',
        icon: 'ε',
        term: 'Permittivity of Free Space (ε₀)',
        color: '#0f7b6c',
        type: 'Constant',
        definition: 'A fundamental physical constant that quantifies how much electric flux a unit charge generates in a vacuum. It appears in Coulomb\'s Law and Gauss\'s Law.',
        formula: 'ε₀ = 8.854 × 10⁻¹² C²/(N·m²)',
        formulaNote: 'k = 1/(4πε₀) = 9 × 10⁹ N·m²·C⁻²',
        example: 'In Gauss\'s Law: Φ = q_enc/ε₀. If q_enc = 1 μC, then Φ = 10⁻⁶/(8.85×10⁻¹²) ≈ 1.13 × 10⁵ N·m²/C.',
        neetTip: 'You never need to memorise ε₀ numerically — just remember ε₀ = 1/(4πk) and k = 9 × 10⁹.'
    },
    {
        id: 'electric-field',
        icon: '🌐',
        term: 'Electric Field (E)',
        color: '#1d4ed8',
        type: 'Field Concept',
        definition: 'The force experienced by a positive unit test charge placed at a point. It is a vector quantity pointing in the direction of force on a positive charge. SI unit: N/C or V/m.',
        formula: 'E = F/q₀ = kq/r²',
        formulaNote: 'q₀ is the test charge (assumed infinitesimally small)',
        example: 'A charge of 5 μC creates a field at 1 m distance: E = 9×10⁹ × 5×10⁻⁶ / 1² = 4.5 × 10⁴ N/C.',
        neetTip: 'Electric field lines are NOT the path of the charge — they show the direction of force on a +ve test charge at every point.'
    },
    {
        id: 'superposition',
        icon: '➕',
        term: 'Superposition Principle',
        color: '#7c3aed',
        type: 'Principle',
        definition: 'The total force (or electric field) at a point due to multiple charges is the vector sum of the individual forces (or fields) due to each charge independently.',
        formula: 'F = F₁ + F₂ + … + Fₙ',
        formulaNote: 'Vector addition — direction and magnitude must both be considered',
        example: 'Three charges at corners of an equilateral triangle: find field at centre by computing E₁, E₂, E₃ due to each, then add as vectors.',
        neetTip: 'For symmetric arrangements (equilateral triangle, square), look for cancellation before computing. Check for symmetry first — it saves 80% of the algebra.'
    },
    {
        id: 'field-lines',
        icon: '〰️',
        term: 'Electric Field Lines',
        color: '#be123c',
        type: 'Visualisation Tool',
        definition: 'Imaginary curves whose tangent at any point gives the direction of the electric field at that point. They represent the field\'s invisible structure in 2D/3D space.',
        formula: 'Density of lines ∝ |E|',
        formulaNote: 'Closer lines → stronger field',
        example: 'Near the surface of a charged sphere, field lines are densely packed (strong field); far away they diverge (weaker field).',
        neetTip: `Key rules: (1) Start at +ve, end at −ve. (2) Never cross or close on themselves. (3) Perpendicular to conducting surface. (4) No field lines inside conductor in electrostatics.`
    },
    {
        id: 'electric-flux',
        icon: 'Φ',
        term: 'Electric Flux (Φ)',
        color: '#0369a1',
        type: 'Flux Concept',
        definition: 'The total number of electric field lines passing through a surface. Measures how much of the electric field "flows through" a given area. It\'s a scalar quantity.',
        formula: 'Φ = E·A·cosθ = ∮E·dA',
        formulaNote: 'θ is angle between E and area normal (n̂)',
        example: 'E = 500 N/C passes through a 0.02 m² surface at 60° to the normal. Φ = 500 × 0.02 × cos60° = 5 N·m²/C.',
        neetTip: 'Flux through a closed surface: positive if net field exits, negative if it enters. Flux through a side face of a cube with field along its axis = 0 (cosθ = cos90° = 0).'
    },
    {
        id: 'gauss-law',
        icon: '🔵',
        term: "Gauss's Law",
        color: '#15803d',
        type: 'Fundamental Law',
        definition: 'The total electric flux through any closed surface (Gaussian surface) equals the net charge enclosed divided by ε₀. One of Maxwell\'s four equations.',
        formula: 'Φ_closed = q_enc/ε₀',
        formulaNote: 'q_enc = net charge inside the Gaussian surface',
        example: 'A spherical Gaussian surface of radius r around a +q charge: E × 4πr² = q/ε₀ → E = q/(4πε₀r²) = kq/r² ✓ (Coulomb\'s Law recovered).',
        neetTip: 'Gauss\'s Law is most useful when the charge distribution has SYMMETRY (spherical, cylindrical, or planar). Then you can pull E outside the integral.'
    },
    {
        id: 'gaussian-surface',
        icon: '🟣',
        term: 'Gaussian Surface',
        color: '#6d28d9',
        type: 'Mathematical Tool',
        definition: 'An imaginary closed surface chosen to simplify the application of Gauss\'s Law. Shape is chosen to exploit the symmetry of the charge distribution.',
        formula: 'Choose so that E is constant and ⊥ to surface (or E = 0 on surface)',
        formulaNote: 'Not a physical surface — a mathematical tool',
        example: '• Spherical for point charge / sphere of charge\n• Cylindrical for infinite line charge or cylinder\n• Pillbox (short cylinder) for infinite plane charge',
        neetTip: 'Three canonical Gaussian surfaces in NEET: sphere (for point/spherical charges), cylinder (for wire/cylindrical charges), rectangular pillbox (for planar charges).'
    },
    {
        id: 'electric-dipole',
        icon: '↔️',
        term: 'Electric Dipole',
        color: '#b45309',
        type: 'Charge Configuration',
        definition: 'A system of two equal and opposite charges (+q and −q) separated by a small distance 2l. Characterised by the dipole moment p.',
        formula: 'p = q × 2l',
        formulaNote: 'Vector; points from −q to +q. Unit: C·m',
        example: 'Charges ±1 μC separated by 2 cm: p = 10⁻⁶ × 0.02 = 2 × 10⁻⁸ C·m. Field on axis: E = 2kp/r³; on equatorial plane: E = kp/r³.',
        neetTip: 'NEET commonly asks for field at (1) axial point: E_axis = 2kp/r³ and (2) equatorial point: E_eq = kp/r³. The ratio is 2:1 at the same distance r.'
    },
    {
        id: 'torque-dipole',
        icon: '🔄',
        term: 'Torque on Dipole in Uniform Field',
        color: '#0f766e',
        type: 'Dipole Mechanics',
        definition: 'When an electric dipole is placed in a uniform electric field, it experiences a torque that tends to align the dipole moment with the field.',
        formula: 'τ = pE sinθ = p × E',
        formulaNote: 'θ = angle between p and E',
        example: 'p = 3 × 10⁻⁸ C·m, E = 10⁵ N/C, θ = 30°. τ = 3×10⁻⁸ × 10⁵ × sin30° = 3×10⁻³ × 0.5 = 1.5 × 10⁻³ N·m.',
        neetTip: 'Stable equilibrium: θ = 0° (p parallel to E, τ = 0, U = −pE minimum). Unstable equilibrium: θ = 180° (p antiparallel, U = +pE maximum).'
    },
    {
        id: 'linear-charge',
        icon: 'λ',
        term: 'Linear Charge Density (λ)',
        color: '#4a2c8a',
        type: 'Charge Distribution',
        definition: 'Charge per unit length for a line distribution. Used when charge is spread along a 1D curve (wire, rod). SI unit: C/m.',
        formula: 'λ = dq/dl',
        formulaNote: 'E at distance r from infinite wire: E = λ/(2πε₀r)',
        example: 'A wire of length L = 0.5 m carries charge Q = 10 μC. λ = 10×10⁻⁶ / 0.5 = 2 × 10⁻⁵ C/m.',
        neetTip: 'Field of an infinite line charge: E = λ/(2πε₀r). This is derived using a co-axial cylindrical Gaussian surface of radius r and length L.'
    },
    {
        id: 'surface-charge',
        icon: 'σ',
        term: 'Surface Charge Density (σ)',
        color: '#be123c',
        type: 'Charge Distribution',
        definition: 'Charge per unit area for a surface distribution. Used when charge is spread over a 2D surface (conducting plate, sphere). SI unit: C/m².',
        formula: 'σ = dq/dA',
        formulaNote: 'E near an infinite plane: E = σ/(2ε₀) from one side; σ/ε₀ between two plates',
        example: 'A 0.01 m² plate has 5 μC. σ = 5×10⁻⁶/0.01 = 5 × 10⁻⁴ C/m². Field just outside = σ/ε₀ = 5.6 × 10⁷ N/C.',
        neetTip: 'Outside a conductor: E = σ/ε₀ (⊥ to surface). For an infinite non-conducting sheet: E = σ/(2ε₀) on each side.'
    },
    {
        id: 'volume-charge',
        icon: 'ρ',
        term: 'Volume Charge Density (ρ)',
        color: '#0369a1',
        type: 'Charge Distribution',
        definition: 'Charge per unit volume for a 3D distributed charge. Used for uniformly charged solids (sphere, cylinder). SI unit: C/m³.',
        formula: 'ρ = dq/dV',
        formulaNote: 'For uniform sphere: E_inside = ρr/(3ε₀) = qr/(4πε₀R³)',
        example: 'A uniformly charged sphere (R = 0.1 m, Q = 8 μC). ρ = Q/(4πR³/3) = 8×10⁻⁶ / (4π×10⁻³/3) ≈ 1.9 × 10⁻³ C/m³.',
        neetTip: 'Inside a uniformly charged sphere: E ∝ r (increases linearly). Outside: E ∝ 1/r² (like a point charge). At surface: both expressions give the same value.'
    },
];

export const ECFFormulas = [
    { name: "Coulomb's Force",        formula: "F = kq₁q₂/r²",          note: "k = 9×10⁹ N·m²/C²"         },
    { name: "Electric Field",          formula: "E = kq/r² = F/q₀",       note: "Due to point charge"          },
    { name: "Field on Dipole Axis",    formula: "E_axis = 2kp/r³",         note: "r >> 2l; p = q·2l"           },
    { name: "Dipole Equatorial Field", formula: "E_eq = kp/r³",            note: "Points antiparallel to p"    },
    { name: "Torque on Dipole",        formula: "τ = pE sinθ",             note: "θ between p and E"           },
    { name: "Dipole PE in Field",      formula: "U = −pE cosθ",            note: "U = 0 when θ = 90°"          },
    { name: "Electric Flux",           formula: "Φ = E·A·cosθ",            note: "θ between E and area normal" },
    { name: "Gauss's Law",             formula: "Φ = q_enc/ε₀",            note: "For any closed surface"      },
    { name: "Field: Infinite Wire",    formula: "E = λ/(2πε₀r)",           note: "Cylindrical symmetry"        },
    { name: "Field: Infinite Plane",   formula: "E = σ/(2ε₀)",             note: "Non-conducting sheet"        },
    { name: "Field: Conducting Plate", formula: "E = σ/ε₀",                note: "Just outside conductor"      },
    { name: "Field Inside Solid Sphere",formula: "E = ρr/(3ε₀)",           note: "Uniformly charged; r < R"    },
];

export const ECF_RULES = [
    {
        num: 1,
        title: 'Signs and Directions First',
        rule: 'Before solving, fix direction conventions for vectors (force, field, dipole moment) and stick to them.',
        emoji: '🧭',
        color: '#4a2c8a',
        detail: 'Most electrostatics errors come from dropping direction in vector addition. Define +x/+y axes, mark vector arrows, then resolve components. This is essential in superposition and dipole-field questions.',
        examples: [
            'At a point between +q and +q, fields oppose each other. At midpoint, net E = 0 by symmetry.',
            'At a point between +q and −q, fields are in same direction (towards −q), so magnitudes add.',
        ],
        tip: 'Draw field arrows first. Write formulas second.',
    },
    {
        num: 2,
        title: 'Use Symmetry Before Algebra',
        rule: 'In Gauss/superposition problems, check cancellation and symmetry before calculation.',
        emoji: '🪞',
        color: '#0f7b6c',
        detail: 'Symmetry can instantly reduce long expressions to zero or a simple multiple. For ring, sphere, square, and equidistant arrangements, equal magnitudes often cancel component-wise.',
        examples: [
            'Field at center of a uniformly charged ring = 0 by symmetry.',
            'Flux through cube faces with charge at center: each face gets equal share Q/(6ε₀).',
        ],
        tip: 'Ask: “What cancels?” before asking “What is the formula?”',
    },
    {
        num: 3,
        title: 'Gauss Works Only with Symmetry',
        rule: 'Apply Gauss’s Law for field magnitude only when spherical/cylindrical/planar symmetry exists.',
        emoji: '🔵',
        color: '#1d4ed8',
        detail: 'Gauss’s Law is always true, but useful evaluation needs E to be constant on chosen Gaussian surface or zero on parts. Otherwise, use Coulomb integration or numerical methods.',
        examples: [
            'Infinite line charge: choose co-axial cylinder → E = λ/(2π ε₀ r).',
            'Infinite plane sheet: choose pillbox → E = σ/(2ε₀).',
        ],
        tip: 'No symmetry, no shortcut.',
    },
    {
        num: 4,
        title: 'Know Scaling Laws',
        rule: 'Memorize how field scales with distance: point charge 1/r², dipole 1/r³ (far field).',
        emoji: '📉',
        color: '#b45309',
        detail: 'Distance-scaling appears repeatedly in conceptual MCQs. Mixing up 1/r² and 1/r³ leads to wrong option elimination and magnitude comparisons.',
        examples: [
            'If distance doubles, point-charge field becomes 1/4.',
            'If distance doubles, dipole far-field becomes 1/8.',
        ],
        tip: 'Point source: square law. Dipole source: cube law.',
    },
    {
        num: 5,
        title: 'Dimensional and Unit Check',
        rule: 'Always verify units at final step: N, N/C, C·m, N·m²/C, etc.',
        emoji: '✅',
        color: '#be123c',
        detail: 'Unit checks catch silent algebra slips and wrong substitutions of constants. In objective exams, unit mismatch can help eliminate options quickly.',
        examples: [
            'Torque on dipole must end in N·m, not N/C.',
            'Electric flux must be N·m²/C, never just N/C.',
        ],
        tip: 'If units fail, the answer fails.',
    },
];

export const ECF_VOCAB_QUIZ = [
    {
        question: 'Electric field at distance r from a point charge q varies as:',
        options: ['1/r', '1/r²', '1/r³', 'constant'],
        correct: 1,
        explanation: 'For a point charge, $E = kq/r^2$. So the dependence is inverse-square.',
    },
    {
        question: 'Charge enclosed by a closed surface is zero. Net flux through it is:',
        options: ['Positive', 'Negative', 'Zero', 'Cannot be predicted'],
        correct: 2,
        explanation: 'By Gauss’s Law, $\\Phi = q_{enc}/\\epsilon_0$. If $q_{enc}=0$, net flux is zero.',
    },
    {
        question: 'Direction of electric dipole moment p is:',
        options: ['From +q to −q', 'From −q to +q', 'Perpendicular to axis', 'Depends on field'],
        correct: 1,
        explanation: 'By definition, dipole moment points from negative charge to positive charge.',
    },
    {
        question: 'For equal distances (far field), dipole axial field compared to equatorial field is:',
        options: ['Equal', 'Half', 'Twice', 'Four times'],
        correct: 2,
        explanation: 'For $r \\gg 2l$: $E_{axial}=2kp/r^3$ and $E_{eq}=kp/r^3$, so ratio is 2.',
    },
    {
        question: 'Inside a conductor at electrostatic equilibrium, electric field is:',
        options: ['Maximum', 'Uniform non-zero', 'Zero', 'Depends on shape only'],
        correct: 2,
        explanation: 'Free charges redistribute until internal field cancels out, making $E=0$ inside.',
    },
    {
        question: 'Which expression correctly gives electric flux through a flat surface in uniform field?',
        options: ['E/A', 'EA sinθ', 'EA cosθ', 'E²A'],
        correct: 2,
        explanation: 'Flux is dot product: $\\Phi = \\vec{E}\\cdot\\vec{A} = EA\\cos\\theta$.',
    },
];
