export const complexConnectomicsData = {
    connections: [
        {
            icon: '⚡',
            type: 'PHYSICS',
            color: '#f59e0b',
            from: 'Complex Numbers',
            to: 'AC Circuit Analysis',
            how: 'Impedance Z = R + iX combines resistance (R) and reactance (X) in a single complex number. Multiplying phasors in polar form simplifies AC circuit calculations drastically.',
            formula: 'Z = R + i(X_L - X_C)',
        },
        {
            icon: '🎵',
            type: 'ENGINEERING',
            color: '#6366f1',
            from: 'Complex Numbers',
            to: 'Signal Processing (Fourier)',
            how: 'The Fourier transform decomposes any signal into frequencies using e^(iωt) = cos(ωt) + i·sin(ωt). Audio compression (MP3), image processing (JPEG), and 5G all use this.',
            formula: 'F(\\omega) = \\int f(t)\\,e^{-i\\omega t}\\,dt',
        },
        {
            icon: '⚛️',
            type: 'QUANTUM MECHANICS',
            color: '#7c3aed',
            from: 'Complex Numbers',
            to: 'Wave Functions',
            how: 'Quantum states are described by complex-valued wave functions ψ(x,t). The probability density |ψ|² uses the modulus. Complex amplitudes are fundamental — not optional.',
            formula: '|\\psi|^2 = \\psi \\cdot \\bar{\\psi}',
        },
        {
            icon: '🌀',
            type: 'MATHEMATICS',
            color: '#ec4899',
            from: 'Complex Numbers',
            to: 'Fractals (Mandelbrot Set)',
            how: 'The Mandelbrot set is defined by iterating z_{n+1} = z_n² + c in the complex plane. Points where the iteration stays bounded form one of the most intricate structures in mathematics.',
            formula: 'z_{n+1} = z_n^2 + c,\\; c \\in \\mathbb{C}',
        },
        {
            icon: '🔄',
            type: 'GEOMETRY',
            color: '#0d9488',
            from: 'Complex Numbers',
            to: '2D Rotations & Transformations',
            how: 'Multiplying a complex number z by e^(iθ) rotates it by angle θ in the Argand plane. Computer graphics uses this for efficient 2D rotations without trigonometric functions.',
            formula: 'z \\cdot e^{i\\theta} \\text{ rotates } z \\text{ by } \\theta',
        },
        {
            icon: '📈',
            type: 'ALGEBRA',
            color: '#3b82f6',
            from: 'Complex Numbers',
            to: 'Fundamental Theorem of Algebra',
            how: 'Every polynomial of degree n has exactly n roots in ℂ (counting multiplicity). Without complex numbers, x²+1 = 0 would have "no solution." With ℂ, it has two: ±i.',
            formula: 'a_n z^n + \\ldots + a_0 = 0 \\text{ has } n \\text{ roots in } \\mathbb{C}',
        },
        {
            icon: '📡',
            type: 'COMMUNICATIONS',
            color: '#10b981',
            from: 'Complex Numbers',
            to: 'Wireless Communication',
            how: 'QAM (Quadrature Amplitude Modulation) encodes data in the amplitude and phase of a carrier wave — directly corresponding to the real and imaginary parts of a complex signal.',
            formula: 's(t) = \\text{Re}(z \\cdot e^{i\\omega_c t})',
        },
    ],
};
