/**
 * AlgebraicExpressionsSkillsData.js
 * NCERT Class 8 Mathematics — Chapter 9: Algebraic Expressions and Identities
 *
 * Each skill has:
 * - practice: 20 unique questions (includes MCQ, T/F, Fill)
 * - assess: 10 unique MCQ/TF questions (no overlap with practice)
 */

export const expressionsBasics = {
    practice: [
        { type: 'mcq', question: 'Which of the following is an algebraic expression?', options: ['$3+5=8$', '$2x+7$', '$7<9$', '$12 \\div 4 = 3$'], correct: 1, explanation: '$2x+7$ is a mathematical phrase with a variable and no equality sign.' },
        { type: 'fill', question: 'The number of terms in $4x^2 - 3x + 9$ is ____.', correctValue: 3, explanation: 'The terms are $4x^2$, $-3x$, and $9$.' },
        { type: 'truefalse', question: 'In the term $-8ab$, the coefficient is $-8$.', options: ['True', 'False'], correct: 0, explanation: 'The numerical factor of $-8ab$ is $-8$.' },
        { type: 'mcq', question: 'Which of the following is a monomial?', options: ['$x+3$', '$5ab^2$', '$p-q$', '$a+b+c$'], correct: 1, explanation: '$5ab^2$ has only one term.' },
        { type: 'mcq', question: 'What is the constant term in $x^2 + 5x - 11$?', options: ['$x^2$', '$5$', '$-11$', '$1$'], correct: 2, explanation: 'The term without a variable is the constant term.' },
        { type: 'fill', question: 'Evaluate $3x + 4$ for $x=5$. Answer = ____.', correctValue: 19, explanation: '$3(5)+4=15+4=19$.' },
        { type: 'mcq', question: 'Which expression is a binomial?', options: ['$7x$', '$x+y$', '$a+b+c$', '$9$'], correct: 1, explanation: 'A binomial has exactly two terms.' },
        { type: 'truefalse', question: 'The expression $6$ is a monomial.', options: ['True', 'False'], correct: 0, explanation: 'A constant alone is treated as a one-term expression.' },
        { type: 'mcq', question: 'The factors of $-3x^2y$ are:', options: ['$-3, x, x, y$', '$-3x, 2, y$', '$-3, x+y$', '$-3x^2, y^2$'], correct: 0, explanation: '$-3x^2y = (-3) \\times x \\times x \\times y$.' },
        { type: 'fill', question: 'If $a=2$, then $a^2 + 3a = $ ____.', correctValue: 10, explanation: '$2^2 + 3(2) = 4 + 6 = 10$.' },
        { type: 'mcq', question: 'Which of the following is a polynomial?', options: ['$\\frac{1}{x}+2$', '$3x^2 - x + 7$', '$x^{-1}+1$', '$2/x$'], correct: 1, explanation: 'A polynomial has variables with non-negative integral exponents.' },
        { type: 'mcq', question: 'How many variables are there in $5ab^2c$?', options: ['$1$', '$2$', '$3$', '$4$'], correct: 2, explanation: 'The variables are $a$, $b$, and $c$.' },
        { type: 'truefalse', question: 'The term $x$ has coefficient $1$.', options: ['True', 'False'], correct: 0, explanation: '$x = 1x$.' },
        { type: 'mcq', question: 'Which expression represents "5 more than twice a number $x$"?', options: ['$5x+2$', '$2x+5$', '$2(x+5)$', '$x+7$'], correct: 1, explanation: 'Twice the number is $2x$, then add 5.' },
        { type: 'fill', question: 'The coefficient of $y^2$ in $7x - 4y^2 + 3$ is ____.', correctValue: -4, explanation: 'The numerical factor of $y^2$ is $-4$.' },
        { type: 'mcq', question: 'Which of the following is a trinomial?', options: ['$p+q+r$', '$8m$', '$x-y$', '$12$'], correct: 0, explanation: '$p+q+r$ has 3 terms.' },
        { type: 'mcq', question: 'Evaluate $2m-1$ when $m=-3$.', options: ['$-7$', '$7$', '$-5$', '$5$'], correct: 0, explanation: '$2(-3)-1=-6-1=-7$.' },
        { type: 'truefalse', question: 'An algebraic expression always contains an equal sign.', options: ['True', 'False'], correct: 1, explanation: 'Expressions do not contain an equality sign.' },
        { type: 'fill', question: 'In the expression $9p^3$, the power of $p$ is ____.', correctValue: 3, explanation: '$p$ is raised to the exponent 3.' },
        { type: 'mcq', question: 'Which of these is not a polynomial?', options: ['$x^2+1$', '$5a-3$', '$3/y$', '$7$'], correct: 2, explanation: '$3/y$ has a variable in the denominator, so it is not a polynomial.' },
    ],
    assess: [
        { type: 'mcq', question: 'Which is a monomial?', options: ['$x+1$', '$4xy$', '$a-b$', '$p+q+r$'], correct: 1, explanation: '$4xy$ is a single term.' },
        { type: 'mcq', question: 'The coefficient of $ab$ in $-9ab$ is:', options: ['$9$', '$-9$', '$ab$', '$-ab$'], correct: 1, explanation: 'The numerical factor is $-9$.' },
        { type: 'mcq', question: 'How many terms are in $x^2 + 2x + 1$?', options: ['$1$', '$2$', '$3$', '$4$'], correct: 2, explanation: 'There are 3 terms.' },
        { type: 'truefalse', question: '$5$ is an algebraic expression.', options: ['True', 'False'], correct: 0, explanation: 'A constant alone is also an expression.' },
        { type: 'mcq', question: 'Evaluate $4x-3$ when $x=2$.', options: ['$5$', '$8$', '$11$', '$1$'], correct: 0, explanation: '$4(2)-3=8-3=5$.' },
        { type: 'mcq', question: 'Which is a binomial?', options: ['$3a$', '$p+q$', '$x+y+z$', '$8$'], correct: 1, explanation: '$p+q$ has two terms.' },
        { type: 'mcq', question: 'The constant term in $6x^2 - x + 4$ is:', options: ['$6$', '$-1$', '$4$', '$x$'], correct: 2, explanation: '$4$ does not contain a variable.' },
        { type: 'truefalse', question: 'The expression $1/x + 2$ is a polynomial.', options: ['True', 'False'], correct: 1, explanation: 'Variables with negative powers are not allowed in polynomials.' },
        { type: 'mcq', question: 'The factors of $7mn$ are:', options: ['$7, m, n$', '$7m, n^2$', '$7+m+n$', '$7mn, 1$'], correct: 0, explanation: 'The multiplied parts are $7$, $m$, and $n$.' },
        { type: 'mcq', question: 'Which expression represents "three less than $x$"?', options: ['$3-x$', '$x-3$', '$3x$', '$x+3$'], correct: 1, explanation: 'Three less than $x$ means subtract 3 from $x$.' },
    ],
};

export const likeTermsAndOperations = {
    practice: [
        { type: 'mcq', question: 'Which pair consists of like terms?', options: ['$3x$ and $3y$', '$5ab$ and $-2ba$', '$x^2$ and $x$', '$2m$ and $2n$'], correct: 1, explanation: '$ab$ and $ba$ represent the same variable part.' },
        { type: 'fill', question: 'Simplify $7x + 2x - 5x = $ ____ $x$.', correctValue: 4, explanation: '$7+2-5=4$.' },
        { type: 'truefalse', question: '$4x^2$ and $9x^2$ are like terms.', options: ['True', 'False'], correct: 0, explanation: 'They have the same variable and the same power.' },
        { type: 'mcq', question: 'Which term is unlike the others?', options: ['$5xy$', '$-2yx$', '$3x^2y$', '$xy$'], correct: 2, explanation: '$3x^2y$ has $x^2y$, not $xy$.' },
        { type: 'mcq', question: 'Simplify $2a + 5a - 3a$.', options: ['$4a$', '$10a$', '$6a$', '$4a^2$'], correct: 0, explanation: '$2+5-3=4$.' },
        { type: 'fill', question: 'Add $(3x+4)$ and $(2x-1)$. The coefficient of $x$ in the result is ____.', correctValue: 5, explanation: '$3x+4+2x-1 = 5x+3$, so the coefficient of $x$ is $5$.' },
        { type: 'mcq', question: 'Subtract $(x+2)$ from $(4x-3)$.', options: ['$3x-5$', '$5x-1$', '$3x+5$', '$4x-5$'], correct: 0, explanation: '$(4x-3)-(x+2)=4x-3-x-2=3x-5$.' },
        { type: 'truefalse', question: '$3x + 2y = 5xy$', options: ['True', 'False'], correct: 1, explanation: 'Unlike terms cannot be combined into one term like that.' },
        { type: 'mcq', question: 'What must be added to $2x-3$ to get $5x+1$?', options: ['$3x+4$', '$3x-4$', '$-3x+4$', '$7x-2$'], correct: 0, explanation: 'Subtract: $(5x+1)-(2x-3)=3x+4$.' },
        { type: 'fill', question: 'Simplify $10xy - 3xy + 2xy$. Coefficient of $xy$ is ____.', correctValue: 9, explanation: '$10-3+2=9$.' },
        { type: 'mcq', question: 'Add $(x^2+3x)$ and $(2x^2-x+4)$.', options: ['$3x^2+2x+4$', '$3x^2+4x+4$', '$2x^2+2x+4$', '$3x^4+2x+4$'], correct: 0, explanation: '$x^2+2x^2=3x^2$ and $3x-x=2x$.' },
        { type: 'mcq', question: 'Simplify $(5p-q) - (2p+3q)$.', options: ['$3p-4q$', '$7p+2q$', '$3p+2q$', '$7p-4q$'], correct: 0, explanation: '$5p-q-2p-3q=3p-4q$.' },
        { type: 'truefalse', question: '$ab$ and $ba$ are like terms.', options: ['True', 'False'], correct: 0, explanation: 'The order of multiplication does not matter.' },
        { type: 'fill', question: 'Subtract $3m$ from $-2m$. Result coefficient of $m$ is ____.', correctValue: -5, explanation: '$-2m-3m=-5m$.' },
        { type: 'mcq', question: 'Simplify $7 + 2x - 3 + x$.', options: ['$3x+4$', '$3x+10$', '$x+4$', '$2x+4$'], correct: 0, explanation: 'Combine constants and $x$-terms separately.' },
        { type: 'mcq', question: 'Which expression is already in simplest form?', options: ['$4x+3x$', '$2a+5b$', '$9y-4y$', '$x+x+x$'], correct: 1, explanation: '$2a+5b$ has unlike terms, so it cannot be combined further.' },
        { type: 'truefalse', question: 'The sum of two polynomials is always a polynomial.', options: ['True', 'False'], correct: 0, explanation: 'Polynomials are closed under addition.' },
        { type: 'fill', question: 'What should be subtracted from $6x$ to get $x$? ____ $x$', correctValue: 5, explanation: '$6x-5x=x$.' },
        { type: 'mcq', question: 'Simplify $(3a^2+2a) + (5a - a^2)$.', options: ['$2a^2+7a$', '$4a^2+7a$', '$8a^2+2a$', '$2a^2-3a$'], correct: 0, explanation: '$3a^2-a^2=2a^2$ and $2a+5a=7a$.' },
        { type: 'mcq', question: 'If the length and breadth of a rectangle are $x+2$ and $x+1$, which is its perimeter?', options: ['$2x+3$', '$4x+6$', '$x^2+3x+2$', '$2x^2+6x+4$'], correct: 1, explanation: '$2[(x+2)+(x+1)] = 2(2x+3)=4x+6$.' },
    ],
    assess: [
        { type: 'mcq', question: 'Which pair are like terms?', options: ['$2x$ and $2x^2$', '$3ab$ and $-5ba$', '$m$ and $n$', '$x^2y$ and $xy^2$'], correct: 1, explanation: 'Both have the same variable part $ab$.' },
        { type: 'mcq', question: 'Simplify $8x-3x$.', options: ['$5x$', '$11x$', '$5x^2$', '$x$'], correct: 0, explanation: '$8-3=5$.' },
        { type: 'mcq', question: 'Add $(2y+7)$ and $(5y-4)$.', options: ['$7y+3$', '$3y+3$', '$7y-11$', '$10y+3$'], correct: 0, explanation: '$2y+5y=7y$ and $7-4=3$.' },
        { type: 'truefalse', question: '$x^2$ and $x$ are like terms.', options: ['True', 'False'], correct: 1, explanation: 'Their powers are different.' },
        { type: 'mcq', question: 'Subtract $(2p-1)$ from $(5p+4)$.', options: ['$3p+5$', '$7p+3$', '$3p+3$', '$-3p+5$'], correct: 0, explanation: '$(5p+4)-(2p-1)=3p+5$.' },
        { type: 'mcq', question: 'Which cannot be simplified further?', options: ['$4a+3a$', '$7x-2x$', '$5m+2n$', '$p+p$'], correct: 2, explanation: '$5m$ and $2n$ are unlike terms.' },
        { type: 'mcq', question: 'Simplify $x^2 + 3x + 2x^2 - x$.', options: ['$3x^2+2x$', '$3x^2+4x$', '$x^2+2x$', '$2x^2+2x$'], correct: 0, explanation: '$x^2+2x^2=3x^2$ and $3x-x=2x$.' },
        { type: 'truefalse', question: 'Changing signs is necessary when subtracting a bracketed expression.', options: ['True', 'False'], correct: 0, explanation: 'Each term inside the subtracted bracket changes sign.' },
        { type: 'mcq', question: 'What must be added to $x-4$ to get $3x+1$?', options: ['$2x+5$', '$2x-5$', '$4x+1$', '$2x+1$'], correct: 0, explanation: 'Subtract: $(3x+1)-(x-4)=2x+5$.' },
        { type: 'mcq', question: 'Simplify $9ab - 4ab + ab$.', options: ['$6ab$', '$5ab$', '$14ab$', '$6a^2b^2$'], correct: 0, explanation: '$9-4+1=6$.' },
    ],
};

export const multiplicationOfExpressions = {
    practice: [
        { type: 'mcq', question: 'Multiply $3x$ and $4y$.', options: ['$7xy$', '$12xy$', '$12x+y$', '$7x+y$'], correct: 1, explanation: '$3 \\times 4 = 12$ and $x \\times y = xy$.' },
        { type: 'fill', question: 'The product of $x^2$ and $x^5$ is $x^{\\_\\_}$.', correctValue: 7, explanation: 'Add exponents of the same base: $2+5=7$.' },
        { type: 'truefalse', question: '$(-2a)(3a^2) = -6a^3$.', options: ['True', 'False'], correct: 0, explanation: 'Multiply coefficients and add exponents of $a$.' },
        { type: 'mcq', question: 'Multiply $2x$ by $(3x+4)$.', options: ['$6x^2+8x$', '$6x^2+4$', '$5x+4$', '$6x+8$'], correct: 0, explanation: 'Distribute $2x$ to both terms.' },
        { type: 'mcq', question: 'Product of $(-xy)$ and $(x^2y)$ is:', options: ['$x^3y^2$', '$-x^3y^2$', '$-x^2y^2$', '$-x^3y$'], correct: 1, explanation: '$-1 \\times 1 = -1$, $x^{1+2}=x^3$, $y^{1+1}=y^2$.' },
        { type: 'fill', question: 'Multiply $-1$, $2a$, and $-5b$. The coefficient is ____.', correctValue: 10, explanation: '$(-1)(2)(-5)=10$.' },
        { type: 'mcq', question: 'Expand $3p(p+2)$.', options: ['$3p^2+6p$', '$3p^2+2$', '$6p^2+2p$', '$3p+2$'], correct: 0, explanation: '$3p \\cdot p + 3p \\cdot 2 = 3p^2 + 6p$.' },
        { type: 'truefalse', question: 'When multiplying same variables, we add their exponents.', options: ['True', 'False'], correct: 0, explanation: '$x^m \\cdot x^n = x^{m+n}$.' },
        { type: 'mcq', question: 'Expand $(x+2)(x+3)$.', options: ['$x^2+5x+6$', '$x^2+6x+5$', '$x^2+5$', '$x^2+6$'], correct: 0, explanation: '$x^2+3x+2x+6 = x^2+5x+6$.' },
        { type: 'fill', question: 'Coefficient of $x$ in $4(x+3)$ after expansion is ____.', correctValue: 4, explanation: '$4(x+3)=4x+12$.' },
        { type: 'mcq', question: 'Multiply $5a^2b$ and $-2ab^2$.', options: ['$-10a^3b^3$', '$10a^3b^3$', '$-7a^3b^3$', '$-10a^2b^2$'], correct: 0, explanation: '$5 \\times -2 = -10$, $a^{2+1}$, $b^{1+2}$.' },
        { type: 'mcq', question: 'Expand $(2x-y)(x+3)$.', options: ['$2x^2+6x-xy-3y$', '$2x^2+3x-y$', '$2x^2+6x-3y$', '$2x^2-xy+3$'], correct: 0, explanation: 'Multiply each term of the first bracket by each term of the second.' },
        { type: 'truefalse', question: 'The product of two binomials can have four terms before simplification.', options: ['True', 'False'], correct: 0, explanation: 'Each of the 2 terms multiplies each of the other 2 terms.' },
        { type: 'fill', question: 'Expand $x(x-5)$. The constant term is ____.', correctValue: 0, explanation: '$x(x-5)=x^2-5x$, so there is no constant term.' },
        { type: 'mcq', question: 'Multiply $(a+b)$ and $c$.', options: ['$ac+b$', '$ac+bc$', '$a+b+c$', '$abc$'], correct: 1, explanation: 'Distribute $c$: $c(a+b)=ac+bc$.' },
        { type: 'mcq', question: 'Expand $(x+1)(x+4)$.', options: ['$x^2+5x+4$', '$x^2+4x+1$', '$x^2+5$', '$x^2+4$'], correct: 0, explanation: '$x^2+4x+x+4=x^2+5x+4$.' },
        { type: 'truefalse', question: '$x^2 \\times y^2 = (xy)^2$.', options: ['True', 'False'], correct: 0, explanation: 'Both expressions simplify to $x^2y^2$.' },
        { type: 'fill', question: 'The product of $4m$, $m$, and $2$ is ____ $m^2$.', correctValue: 8, explanation: '$4 \\cdot 1 \\cdot 2 = 8$ and $m \\cdot m = m^2$.' },
        { type: 'mcq', question: 'Area of a rectangle with sides $(x+2)$ and $3$ is:', options: ['$x+6$', '$3x+6$', '$3x+2$', '$x^2+6$'], correct: 1, explanation: 'Area = $3(x+2)=3x+6$.' },
        { type: 'mcq', question: 'Expand $(x+2)(x+y)$.', options: ['$x^2+xy+2x+2y$', '$x^2+2xy+y$', '$x^2+xy+2$', '$x^2+3xy+2y$'], correct: 0, explanation: 'Multiply each term in the first bracket by each term in the second.' },
    ],
    assess: [
        { type: 'mcq', question: 'Multiply $2x$ and $5x^2$.', options: ['$10x^3$', '$7x^2$', '$10x^2$', '$10x$'], correct: 0, explanation: '$2 \\times 5 = 10$ and $x^{1+2}=x^3$.' },
        { type: 'mcq', question: 'Expand $4a(a-3)$.', options: ['$4a^2-12a$', '$4a^2-3$', '$8a-12$', '$4a^2+12a$'], correct: 0, explanation: 'Distribute $4a$ to both terms.' },
        { type: 'mcq', question: 'What is $(m^2n)(mn^2)$?', options: ['$m^3n^3$', '$m^2n^3$', '$m^3n^2$', '$m^4n^4$'], correct: 0, explanation: 'Add exponents of matching variables.' },
        { type: 'truefalse', question: 'To multiply a monomial by a polynomial, every term must be multiplied.', options: ['True', 'False'], correct: 0, explanation: 'That is the distributive law.' },
        { type: 'mcq', question: 'Expand $(x+5)(x-2)$.', options: ['$x^2+3x-10$', '$x^2-3x-10$', '$x^2+10x-10$', '$x^2+7x+10$'], correct: 0, explanation: '$x^2-2x+5x-10=x^2+3x-10$.' },
        { type: 'mcq', question: 'Multiply $(-3p)$, $(2q)$ and $r$.', options: ['$6pqr$', '$-6pqr$', '$-5pqr$', '$6pq+r$'], correct: 1, explanation: '$-3 \\times 2 \\times 1 = -6$.' },
        { type: 'mcq', question: 'Expand $(2x+1)(x+4)$.', options: ['$2x^2+9x+4$', '$2x^2+8x+1$', '$2x^2+5x+4$', '$x^2+9x+4$'], correct: 0, explanation: '$2x^2+8x+x+4 = 2x^2+9x+4$.' },
        { type: 'truefalse', question: 'The product of two monomials is always a monomial.', options: ['True', 'False'], correct: 0, explanation: 'A single product remains one term.' },
        { type: 'mcq', question: 'Area of a rectangle with sides $2x$ and $(x+3)$ is:', options: ['$2x^2+6x$', '$2x+3$', '$x^2+6$', '$2x^2+3$'], correct: 0, explanation: '$2x(x+3)=2x^2+6x$.' },
        { type: 'mcq', question: 'Expand $(a-b)(c+d)$.', options: ['$ac+ad-bc-bd$', '$ac+bd-ad-bc$', '$a+b+c+d$', '$ac+ad+bc+bd$'], correct: 0, explanation: 'Multiply each term of the first bracket with each of the second.' },
    ],
};

export const algebraicIdentitiesApplications = {
    practice: [
        { type: 'mcq', question: 'What is $(a+b)^2$ equal to?', options: ['$a^2+b^2$', '$a^2+2ab+b^2$', '$a^2-2ab+b^2$', '$2a+2b$'], correct: 1, explanation: 'This is the standard identity for the square of a sum.' },
        { type: 'fill', question: 'Expand $(x-4)^2$. The coefficient of $x$ is ____.', correctValue: -8, explanation: '$(x-4)^2=x^2-8x+16$.' },
        { type: 'truefalse', question: '$(a+b)(a-b)=a^2-b^2$.', options: ['True', 'False'], correct: 0, explanation: 'The middle terms cancel out.' },
        { type: 'mcq', question: 'Find $(102)^2$ using an identity.', options: ['$10404$', '$10204$', '$10004$', '$10400$'], correct: 0, explanation: '$(100+2)^2 = 10000+400+4 = 10404$.' },
        { type: 'mcq', question: 'What is $(x-y)^2$?', options: ['$x^2-y^2$', '$x^2-2xy+y^2$', '$x^2+2xy+y^2$', '$2x-2y$'], correct: 1, explanation: 'Use the standard square-of-difference identity.' },
        { type: 'fill', question: 'Evaluate $51^2 - 49^2$. Answer = ____.', correctValue: 200, explanation: 'Use $a^2-b^2=(a-b)(a+b)=(51-49)(51+49)=2 \\times 100=200$.' },
        { type: 'mcq', question: 'Expand $(2x+y)^2$.', options: ['$4x^2+y^2$', '$4x^2+4xy+y^2$', '$2x^2+2xy+y^2$', '$4x^2+2xy+y^2$'], correct: 1, explanation: '$(2x)^2 + 2(2x)(y) + y^2 = 4x^2+4xy+y^2$.' },
        { type: 'truefalse', question: 'An identity is true for all values of its variables.', options: ['True', 'False'], correct: 0, explanation: 'That is the definition of an identity.' },
        { type: 'mcq', question: 'Evaluate $98 \\times 102$ using identity.', options: ['$9996$', '$10004$', '$9896$', '$10196$'], correct: 0, explanation: '$(100-2)(100+2)=10000-4=9996$.' },
        { type: 'fill', question: 'Expand $(a+3)^2$. Constant term = ____.', correctValue: 9, explanation: '$(a+3)^2 = a^2 + 6a + 9$.' },
        { type: 'mcq', question: 'Which identity is used for $(p+q)(p-q)$?', options: ['Square of a sum', 'Square of a difference', 'Difference of squares', 'Cube identity'], correct: 2, explanation: 'It matches the difference-of-squares pattern.' },
        { type: 'mcq', question: 'Expand $(3m-2)^2$.', options: ['$9m^2-12m+4$', '$9m^2-4$', '$9m^2+12m+4$', '$3m^2-12m+4$'], correct: 0, explanation: 'Use $(a-b)^2 = a^2 - 2ab + b^2$.' },
        { type: 'truefalse', question: '$(a+b)^2 - (a-b)^2 = 4ab$.', options: ['True', 'False'], correct: 0, explanation: 'Subtract the two expansions term by term.' },
        { type: 'fill', question: 'Calculate $11^2$ using identity. Answer = ____.', correctValue: 121, explanation: '$(10+1)^2 = 100 + 20 + 1 = 121$.' },
        { type: 'mcq', question: 'Evaluate $9.8 \\times 10.2$.', options: ['$99.96$', '$100.04$', '$98.04$', '$99.04$'], correct: 0, explanation: '$(10-0.2)(10+0.2)=100-0.04=99.96$.' },
        { type: 'mcq', question: 'Expand $(x+5)(x+2)$.', options: ['$x^2+7x+10$', '$x^2+10x+7$', '$x^2+7$', '$x^2+10$'], correct: 0, explanation: 'It follows the pattern $(x+a)(x+b)=x^2+(a+b)x+ab$.' },
        { type: 'truefalse', question: 'The expression $(x-5)^2$ equals $x^2-25$.', options: ['True', 'False'], correct: 1, explanation: 'It is actually $x^2-10x+25$.' },
        { type: 'fill', question: 'Using identity, $99^2 = $ ____.', correctValue: 9801, explanation: '$(100-1)^2 = 10000-200+1 = 9801$.' },
        { type: 'mcq', question: 'Simplify $(2a+3b)^2 - (2a-3b)^2$.', options: ['$24ab$', '$12ab$', '$4a^2+9b^2$', '$0$'], correct: 0, explanation: 'Use $(x+y)^2-(x-y)^2=4xy$ with $x=2a$ and $y=3b$.' },
        { type: 'mcq', question: 'Which calculation is easiest with $(a+b)(a-b)=a^2-b^2$?', options: ['$47+53$', '$103 \\times 97$', '$12^2$', '$4x+5x$'], correct: 1, explanation: '$103 \\times 97 = (100+3)(100-3)$ is a perfect match.' },
    ],
    assess: [
        { type: 'mcq', question: 'Expand $(x+4)^2$.', options: ['$x^2+8x+16$', '$x^2+16$', '$x^2+4x+16$', '$x^2-8x+16$'], correct: 0, explanation: 'Use $(a+b)^2$.' },
        { type: 'mcq', question: 'What is $(5a-b)(5a+b)$?', options: ['$25a^2+b^2$', '$25a^2-b^2$', '$5a^2-b^2$', '$25a^2-10ab+b^2$'], correct: 1, explanation: 'Use difference of squares.' },
        { type: 'mcq', question: 'Evaluate $(71)^2$.', options: ['$5041$', '$4941$', '$5001$', '$4901$'], correct: 0, explanation: '$(70+1)^2 = 4900+140+1=5041$.' },
        { type: 'truefalse', question: '$(a-b)^2 = a^2 - 2ab + b^2$.', options: ['True', 'False'], correct: 0, explanation: 'This is a standard identity.' },
        { type: 'mcq', question: 'Evaluate $103 \\times 97$.', options: ['$9991$', '$10091$', '$9901$', '$9997$'], correct: 0, explanation: '$(100+3)(100-3)=10000-9=9991$.' },
        { type: 'mcq', question: 'Expand $(x+3)(x-2)$.', options: ['$x^2+x-6$', '$x^2-5x-6$', '$x^2+x+6$', '$x^2-6$'], correct: 0, explanation: 'Use $(x+a)(x+b)=x^2+(a+b)x+ab$.' },
        { type: 'mcq', question: 'What is $(2p-q)^2$?', options: ['$4p^2-4pq+q^2$', '$4p^2-q^2$', '$2p^2-2pq+q^2$', '$4p^2+4pq+q^2$'], correct: 0, explanation: 'Use $(a-b)^2$ with $a=2p$ and $b=q$.' },
        { type: 'truefalse', question: 'The identity $(x+a)(x+b)=x^2+(a+b)x+ab$ works even when $a$ or $b$ is negative.', options: ['True', 'False'], correct: 0, explanation: 'Negative values can be substituted directly into the identity.' },
        { type: 'mcq', question: 'Using identity, $1.02^2 - 0.98^2$ equals:', options: ['$0.08$', '$0.04$', '$0.8$', '$1$'], correct: 0, explanation: '$(1.02-0.98)(1.02+0.98)=0.04 \\times 2 = 0.08$.' },
        { type: 'mcq', question: 'Which identity gives a quick method for $108^2$?', options: ['$(a+b)^2$', '$(a-b)^2$', '$(a+b)(a-b)$', 'None'], correct: 0, explanation: '$108^2=(100+8)^2$ matches $(a+b)^2$.' },
    ],
};
