export const cards5W1H = [
    {
        q: 'WHAT',
        label: 'What is a Triangle?',
        icon: '📐',
        gradFrom: '#10b981',
        gradTo: '#34d399',
        shadow: 'rgba(16,185,129,0.35)',
        content: `A triangle is a simple closed curve made of three line segments. It has three vertices, three sides, and three angles. It is the simplest polygon in geometry, serving as the foundational building block for more complex shapes.`,
        fact: '💡 The word "triangle" comes from the Latin "triangulus", meaning "three-cornered".',
    },
    {
        q: 'WHY',
        label: 'Why do we study them?',
        icon: '🎯',
        gradFrom: '#f59e0b',
        gradTo: '#fbbf24',
        shadow: 'rgba(245,158,11,0.35)',
        content: `Triangles are inherently sturdy! Unlike a square or rectangle, an assemblage of three beams forming a triangle cannot be deformed without altering the length of its sides. They are the foundation of trigonometry, vector analysis, and most modern engineering structures.`,
        fact: '💡 A triangle is the only polygon that is completely rigid — that is why bridges use triangular trusses!',
    },
    {
        q: 'WHO',
        label: 'Who uses triangles?',
        icon: '👷',
        gradFrom: '#f43f5e',
        gradTo: '#fb7185',
        shadow: 'rgba(244,63,94,0.35)',
        content: `Architects and engineers rely on them for designing strong, stable structures like bridges, towers, and roofs. Surveyors, navigators, and astronomers use triangle properties to calculate distances to mountains, ships, or stars.`,
        fact: '💡 Graphic designers and 3D animators use millions of tiny triangles (polygons) to render 3D models in video games and movies.',
    },
    {
        q: 'WHERE',
        label: 'Where do we find them?',
        icon: '🌍',
        gradFrom: '#6366f1',
        gradTo: '#818cf8',
        shadow: 'rgba(99,102,241,0.35)',
        content: `Look around! Roof trusses, the Eiffel Tower, electricity pylons, and bridge supports all use triangular geometry. Even pool ball racks, certain road signs, and the famous Great Pyramids of Giza feature triangular faces.`,
        fact: '💡 The Bermuda Triangle is a famous, loosely defined triangular area in the western part of the North Atlantic Ocean.',
    },
    {
        q: 'WHEN',
        label: 'When do triangles form?',
        icon: '⏱️',
        gradFrom: '#8b5cf6',
        gradTo: '#a78bfa',
        shadow: 'rgba(139,92,246,0.35)',
        content: `A triangle is formed whenever three non-collinear points (points not on the same straight line) are joined by straight paths. However, remember the Triangle Inequality Theorem: a triangle can only be formed if the sum of the lengths of any two sides is always greater than the length of the third side.`,
        fact: '💡 If side lengths are $2$ cm, $3$ cm, and $6$ cm, a triangle cannot be formed because $2 + 3$ is not greater than $6$!',
    },
    {
        q: 'HOW',
        label: 'How do we classify them?',
        icon: '⚙️',
        gradFrom: '#0ea5e9',
        gradTo: '#38bdf8',
        shadow: 'rgba(14,165,233,0.35)',
        content: `Based on Sides: Equilateral (all sides equal), Isosceles (two sides equal), Scalene (no sides equal). Based on Angles: Acute-angled (all angles less than $90°$), Right-angled (one angle equals $90°$), Obtuse-angled (one angle greater than $90°$).`,
        fact: '💡 The sum of all three interior angles of any planar triangle is always exactly $180°$.',
    }
];
