export const cards5W1H = [
    {
        q: 'WHAT',
        label: 'What are Integers?',
        icon: '🔢',
        gradFrom: '#0891b2',
        gradTo: '#06b6d4',
        shadow: 'rgba(6,182,212,0.35)',
        content: `Integers extend whole numbers by including negative numbers. Think of a number line: zero is in the middle, positive numbers go to the right, and negative numbers go to the left. They represent quantities that can go in opposite directions, like ($+5$) and ($-5$).`,
        fact: '💡 The set of integers includes all whole numbers and their negative counterparts, but no fractions or decimals!',
    },
    {
        q: 'WHY',
        label: 'Why do we need them?',
        icon: '📉',
        gradFrom: '#059669',
        gradTo: '#10b981',
        shadow: 'rgba(16,185,129,0.35)',
        content: `Integers allow us to represent real-life changes that go in two directions. We need them to calculate profit and loss, measure temperature rise and fall, or track elevation changes like climbing a mountain versus diving into the ocean.`,
        fact: '💡 Without negative numbers, we couldn\'t accurately describe a bank account in debt or a freezing winter day!',
    },
    {
        q: 'WHO',
        label: 'Who discovered negative numbers?',
        icon: '📜',
        gradFrom: '#b45309',
        gradTo: '#f59e0b',
        shadow: 'rgba(245,158,11,0.35)',
        content: `The concept of negative numbers evolved over centuries. They were first used in ancient Chinese mathematics around 200 BCE to represent debts. Later, Indian mathematicians like Brahmagupta established the first rules for calculating with zero and negative numbers in the 7th century.`,
        fact: '💡 Early European mathematicians called negative numbers "absurd" before finally accepting them in the 1800s!',
    },
    {
        q: 'WHERE',
        label: 'Where are Integers used?',
        icon: '🌍',
        gradFrom: '#be185d',
        gradTo: '#ec4899',
        shadow: 'rgba(236,72,153,0.35)',
        content: `You see them everywhere! In finance to show account balances. In weather apps for temperatures below zero. In geography to measure elevation above or below sea level. In sports to calculate score differentials or golf handicaps.`,
        fact: '💡 The lowest point on dry land is the Dead Sea, which is $-430$ meters (below sea level)!',
    },
    {
        q: 'WHEN',
        label: 'When do we use negative values?',
        icon: '⏱️',
        gradFrom: '#7c3aed',
        gradTo: '#a855f7',
        shadow: 'rgba(168,85,247,0.35)',
        content: `We use negative values whenever a quantity drops below a baseline of zero. If you have $0$ dollars and spend $5$, your balance is $-5$. If the temperature is $0^\\circ$C and drops by $4$ degrees, it becomes $-4^\\circ$C. They represent "less than nothing"!`,
        fact: '💡 Absolute zero, the coldest possible temperature in the universe, is $-273.15^\\circ$C!',
    },
    {
        q: 'HOW',
        label: 'How do we calculate with them?',
        icon: '⚙️',
        gradFrom: '#0369a1',
        gradTo: '#3b82f6',
        shadow: 'rgba(59,130,246,0.35)',
        content: `We calculate using specific "Rules of Signs." When adding numbers with the same sign, we add and keep the sign: $(-3) + (-4) = -7$. When multiplying or dividing, two negative numbers give a positive result: $(-3) \\times (-2) = 6$! It's all about mastering these rules.`,
        fact: '💡 A negative times a negative is positive because taking away a debt makes you richer!',
    },
];
