// Skills data for Ticking Clocks chapter
export const SKILLS = [
    { id: 1, title: 'Reading Clock Time', icon: '🕐', color: '#d97706', desc: 'Tell time by reading hour and minute hands on a clock.' },
    { id: 2, title: 'AM & PM Identification', icon: '🌅', color: '#0284c7', desc: 'Distinguish between AM (morning) and PM (afternoon/evening).' },
    { id: 3, title: 'Duration Calculation', icon: '⏳', color: '#059669', desc: 'Calculate how long an activity lasted using start and end times.' },
    { id: 4, title: 'Calendar — Days & Months', icon: '📆', color: '#7c3aed', desc: 'Know the number of days in each month and days of the week.' },
    { id: 5, title: 'Leap Year Identification', icon: '🐸', color: '#0d9488', desc: 'Determine whether a given year is a leap year or not.' },
    { id: 6, title: 'Date Calculation', icon: '📅', color: '#be185d', desc: 'Find dates after or before a given number of days.' },
    { id: 7, title: 'Time Word Problems', icon: '🧩', color: '#ea580c', desc: 'Solve real-life word problems involving time and calendars.' },
];

export const LEARN_CONTENT = {
    1: {
        title: 'Reading Clock Time',
        points: [
            'A clock has 12 numbers arranged in a circle.',
            'The short thick hand is the HOUR hand — it shows the hour.',
            'The long thin hand is the MINUTE hand — it shows the minutes.',
            'When the minute hand points to 12, it is exactly "o\'clock."',
            'Each number on the clock represents 5 minutes (1→5, 2→10, 3→15...).',
            'Quarter past = 15 min, Half past = 30 min, Quarter to = 45 min.',
        ],
        example: 'If the hour hand is between 3 and 4, and the minute hand points to 6, the time is 3:30 (half past 3).'
    },
    2: {
        title: 'AM & PM Identification',
        points: [
            'AM = Ante Meridiem = "before noon" (12:00 midnight to 11:59 morning).',
            'PM = Post Meridiem = "after noon" (12:00 noon to 11:59 night).',
            '12:00 AM = Midnight, 12:00 PM = Noon.',
            'A full day has 24 hours: 12 hours AM + 12 hours PM.',
            'School usually starts in AM and ends in PM.',
        ],
        example: '7:00 AM = morning (going to school), 7:00 PM = evening (having dinner).'
    },
    3: {
        title: 'Duration Calculation',
        points: [
            'Duration = End Time − Start Time.',
            'If end minutes < start minutes, borrow 1 hour (= 60 min).',
            'Example: 4:15 PM to 6:45 PM → 6:45 − 4:15 = 2 hours 30 minutes.',
            'For crossing noon: split into AM part + PM part.',
            'Always check AM/PM — 2:00 PM to 5:00 PM = 3 hours, not 15 hours!',
        ],
        example: 'A movie starts at 3:30 PM and ends at 5:45 PM. Duration = 5:45 − 3:30 = 2 hours 15 minutes.'
    },
    4: {
        title: 'Calendar — Days & Months',
        points: [
            '1 year = 12 months = 365 days (366 in a leap year).',
            '1 week = 7 days. 1 year ≈ 52 weeks.',
            '31-day months: Jan, Mar, May, Jul, Aug, Oct, Dec (7 months).',
            '30-day months: Apr, Jun, Sep, Nov (4 months).',
            'February: 28 days (29 in leap year).',
            'Knuckle trick: knuckles = 31 days, valleys = 30 days (except Feb).',
        ],
        example: '"30 days hath September, April, June, and November. All the rest have 31, except February."'
    },
    5: {
        title: 'Leap Year Identification',
        points: [
            'A leap year has 366 days (Feb gets 29 days).',
            'Rule: If the year is divisible by 4, it is a leap year.',
            'Exception: Century years (1900, 2100) must be divisible by 400.',
            'So 2000 IS a leap year (÷400=5), but 1900 is NOT (÷400≠whole).',
            'Leap years: 2020, 2024, 2028, 2032...',
        ],
        example: 'Is 2024 a leap year? 2024 ÷ 4 = 506 (no remainder). Yes!'
    },
    6: {
        title: 'Date Calculation',
        points: [
            'To find a date X days later, count forward day by day.',
            'If you cross a month boundary, remember how many days that month has.',
            'Going back? Count backwards.',
            '7 days later = same day of the week.',
            '14 days = 2 weeks, 21 days = 3 weeks, 28 days = 4 weeks.',
        ],
        example: 'Jan 26 + 7 days = Feb 2 (since January has 31 days, Jan 26 + 5 = Jan 31, then +2 = Feb 2).'
    },
    7: {
        title: 'Time Word Problems',
        points: [
            'Read the problem carefully — identify start time, end time, or duration.',
            'Draw a timeline if needed.',
            'Use addition to find end time: Start + Duration = End.',
            'Use subtraction to find duration: End − Start = Duration.',
            'Watch out for AM/PM changes!',
        ],
        example: 'Rani left home at 8:15 AM and reached school at 9:00 AM. Travel time = 45 minutes.'
    },
};

export const PRACTICE_QS = {
    1: [
        { q: 'The hour hand points to 5 and minute hand to 12. What time is it?', opts: ['5:00', '12:05', '12:00', '5:12'], ans: 0, expl: 'Hour hand at 5, minute hand at 12 = 5:00 (5 o\'clock).' },
        { q: 'The minute hand points to 3. How many minutes past the hour is it?', opts: ['3 minutes', '15 minutes', '30 minutes', '45 minutes'], ans: 1, expl: '3 on the clock = 3×5 = 15 minutes.' },
        { q: 'What time is "half past 7"?', opts: ['7:15', '7:30', '7:45', '6:30'], ans: 1, expl: 'Half past = 30 minutes after. So half past 7 = 7:30.' },
        { q: 'The minute hand is at 9. What does that mean?', opts: ['9 minutes', '45 minutes', '15 minutes', '30 minutes'], ans: 1, expl: '9 on the clock = 9×5 = 45 minutes past the hour.' },
        { q: 'What is "quarter past 4"?', opts: ['4:45', '3:15', '4:15', '4:30'], ans: 2, expl: 'Quarter past = 15 min after. Quarter past 4 = 4:15.' },
        { q: 'The hour hand is between 8 and 9, minute hand at 6. Time?', opts: ['8:30', '9:30', '6:08', '8:06'], ans: 0, expl: 'Hour between 8-9 means past 8. Minute at 6 = 30 min. Time = 8:30.' },
        { q: 'What is "quarter to 10"?', opts: ['10:15', '10:45', '9:45', '9:15'], ans: 2, expl: 'Quarter to = 15 min before. Quarter to 10 = 9:45.' },
        { q: 'How many minutes does the minute hand take to go from 12 to 6?', opts: ['6 minutes', '15 minutes', '30 minutes', '60 minutes'], ans: 2, expl: 'From 12 to 6 is half the clock = 30 minutes.' },
        { q: 'At what time are both hands of the clock together?', opts: ['6:00', '3:00', '12:00', '9:00'], ans: 2, expl: 'At 12:00, both the hour and minute hands point to 12.' },
        { q: 'The hour hand points to 11 and minute hand to 2. What time?', opts: ['2:11', '11:10', '11:02', '10:11'], ans: 1, expl: 'Hour at 11, minute at 2 = 2×5 = 10 minutes. Time = 11:10.' },
    ],
    2: [
        { q: 'Which of these is a morning (AM) activity?', opts: ['Eating dinner at 8', 'Sleeping at 10 at night', 'Waking up at 6', 'Watching stars'], ans: 2, expl: 'Waking up at 6 AM is a morning activity.' },
        { q: '12:00 noon is:', opts: ['12:00 AM', '12:00 PM', '0:00 AM', '24:00 PM'], ans: 1, expl: '12:00 noon = 12:00 PM (Post Meridiem = after midnight start).' },
        { q: 'School ends at 2:30 in the afternoon. In time format:', opts: ['2:30 AM', '2:30 PM', '14:30 AM', '12:30 PM'], ans: 1, expl: 'Afternoon = PM. So 2:30 in the afternoon = 2:30 PM.' },
        { q: '12:00 midnight is:', opts: ['12:00 PM', '12:00 AM', '0:00 PM', '24:00 AM'], ans: 1, expl: '12:00 midnight = 12:00 AM.' },
        { q: 'Which is later: 3:00 PM or 3:00 AM?', opts: ['3:00 AM', 'Both are same', '3:00 PM', 'Cannot tell'], ans: 2, expl: '3:00 PM is in the afternoon (15:00), much later in the day than 3:00 AM (early morning).' },
        { q: 'Ravi\'s class starts at 8:00 AM and ends at 1:30 PM. School is in:', opts: ['Only AM', 'Only PM', 'Both AM and PM', 'Neither'], ans: 2, expl: '8:00 AM to 12:00 is AM, then 12:00 to 1:30 PM is PM.' },
        { q: 'The sun sets around:', opts: ['6:00 AM', '6:00 PM', '12:00 AM', '12:00 PM'], ans: 1, expl: 'The sun sets in the evening around 6:00 PM.' },
        { q: 'How many hours is one full AM cycle?', opts: ['24 hours', '6 hours', '12 hours', '8 hours'], ans: 2, expl: 'AM runs from 12:00 midnight to 11:59 morning = 12 hours.' },
        { q: 'Which activity happens in PM?', opts: ['Brushing teeth at 7 AM', 'Going to school at 8 AM', 'Evening homework at 5', 'Morning assembly at 9 AM'], ans: 2, expl: 'Evening homework at 5 PM is in the PM period.' },
        { q: 'What comes right after 11:59 AM?', opts: ['12:00 AM', '12:00 PM', '1:00 AM', '11:60 AM'], ans: 1, expl: 'After 11:59 AM comes 12:00 PM (noon).' },
    ],
    3: [
        { q: 'A movie starts at 3:00 PM and ends at 5:30 PM. Duration?', opts: ['2 hr', '2 hr 30 min', '3 hr', '1 hr 30 min'], ans: 1, expl: '5:30 − 3:00 = 2 hours 30 minutes.' },
        { q: 'Lunch is from 12:30 PM to 1:15 PM. How long?', opts: ['30 min', '45 min', '1 hr', '15 min'], ans: 1, expl: '1:15 − 12:30 = 45 minutes.' },
        { q: 'A train departs at 9:15 AM and arrives at 11:45 AM. Travel time?', opts: ['2 hr 15 min', '2 hr 30 min', '2 hr 45 min', '3 hr'], ans: 1, expl: '11:45 − 9:15 = 2 hours 30 minutes.' },
        { q: 'Rani studies from 4:00 PM to 5:30 PM. How long did she study?', opts: ['30 min', '1 hr', '1 hr 30 min', '2 hr'], ans: 2, expl: '5:30 − 4:00 = 1 hour 30 minutes.' },
        { q: 'A match started at 2:45 PM and lasted 1 hour 30 minutes. When did it end?', opts: ['3:15 PM', '3:45 PM', '4:15 PM', '4:45 PM'], ans: 2, expl: '2:45 + 1:30 = 4:15 PM.' },
        { q: 'Dad left at 8:00 AM and returned at 6:00 PM. How long was he out?', opts: ['8 hours', '10 hours', '12 hours', '6 hours'], ans: 1, expl: '8 AM to 6 PM = 10 hours.' },
        { q: 'A sleeping baby slept from 1:00 PM to 3:30 PM. Duration?', opts: ['1 hr 30 min', '2 hr', '2 hr 30 min', '3 hr'], ans: 2, expl: '3:30 − 1:00 = 2 hours 30 minutes.' },
        { q: 'Class starts at 10:15 AM and ends at 11:00 AM. How long?', opts: ['15 min', '30 min', '45 min', '1 hr'], ans: 2, expl: '11:00 − 10:15 = 45 minutes.' },
        { q: 'If you start walking at 7:30 AM and walk for 45 minutes, when do you finish?', opts: ['8:00 AM', '8:15 AM', '8:30 AM', '7:45 AM'], ans: 1, expl: '7:30 + 0:45 = 8:15 AM.' },
        { q: 'A bus ride from 6:50 AM to 8:20 AM takes how long?', opts: ['1 hr 20 min', '1 hr 30 min', '1 hr 10 min', '2 hr 30 min'], ans: 1, expl: '8:20 − 6:50 = 1 hour 30 minutes.' },
    ],
    4: [
        { q: 'How many days are in January?', opts: ['28', '30', '31', '29'], ans: 2, expl: 'January always has 31 days.' },
        { q: 'Which month comes right after June?', opts: ['May', 'July', 'August', 'April'], ans: 1, expl: 'The order is: June → July.' },
        { q: 'How many days are in a week?', opts: ['5', '6', '7', '10'], ans: 2, expl: 'A week has 7 days: Mon, Tue, Wed, Thu, Fri, Sat, Sun.' },
        { q: 'Which of these months has 30 days?', opts: ['January', 'March', 'April', 'July'], ans: 2, expl: 'April has 30 days. Jan, Mar, Jul all have 31.' },
        { q: 'How many months are in a year?', opts: ['10', '11', '12', '14'], ans: 2, expl: 'A year has 12 months: January through December.' },
        { q: 'Which is the last month of the year?', opts: ['November', 'October', 'December', 'January'], ans: 2, expl: 'December is the 12th and last month.' },
        { q: 'February usually has how many days?', opts: ['30', '31', '28', '27'], ans: 2, expl: 'February normally has 28 days (29 in a leap year).' },
        { q: 'How many days are in a non-leap year?', opts: ['364', '365', '366', '360'], ans: 1, expl: 'A non-leap year has 365 days.' },
        { q: 'What day comes after Saturday?', opts: ['Monday', 'Friday', 'Sunday', 'Tuesday'], ans: 2, expl: 'Sunday follows Saturday.' },
        { q: 'Which month has the fewest days?', opts: ['April', 'June', 'September', 'February'], ans: 3, expl: 'February has only 28 or 29 days — the fewest of any month.' },
    ],
    5: [
        { q: 'Is 2020 a leap year?', opts: ['Yes', 'No'], ans: 0, expl: '2020 ÷ 4 = 505. No remainder, so yes!' },
        { q: 'Is 2023 a leap year?', opts: ['Yes', 'No'], ans: 1, expl: '2023 ÷ 4 = 505.75. Has remainder, so no.' },
        { q: 'Is 1900 a leap year?', opts: ['Yes', 'No'], ans: 1, expl: '1900 is a century year. 1900 ÷ 400 = 4.75. Not divisible by 400, so no.' },
        { q: 'Is 2000 a leap year?', opts: ['Yes', 'No'], ans: 0, expl: '2000 is a century year. 2000 ÷ 400 = 5. Divisible by 400, so yes!' },
        { q: 'February in a leap year has how many days?', opts: ['28', '29', '30', '27'], ans: 1, expl: 'In a leap year, February gets an extra day = 29 days.' },
        { q: 'How many days does a leap year have?', opts: ['365', '364', '366', '367'], ans: 2, expl: 'A leap year has 366 days (one extra day in February).' },
        { q: 'Is 2028 a leap year?', opts: ['Yes', 'No'], ans: 0, expl: '2028 ÷ 4 = 507. No remainder, so yes!' },
        { q: 'Which of these is NOT a leap year?', opts: ['2016', '2018', '2020', '2024'], ans: 1, expl: '2018 ÷ 4 = 504.5. It has a remainder, so it\'s not a leap year.' },
        { q: 'Leap years occur every ___ years.', opts: ['2', '3', '4', '5'], ans: 2, expl: 'Leap years occur every 4 years.' },
        { q: 'Is 2100 a leap year?', opts: ['Yes', 'No'], ans: 1, expl: '2100 is a century year. 2100 ÷ 400 = 5.25. Not exact, so no.' },
    ],
    6: [
        { q: 'What date is 7 days after January 25?', opts: ['January 30', 'January 32', 'February 1', 'February 2'], ans: 2, expl: 'Jan 25 + 6 = Jan 31, then +1 = Feb 1.' },
        { q: 'What date is 10 days after March 25?', opts: ['March 35', 'April 3', 'April 4', 'April 5'], ans: 2, expl: 'Mar 25 + 6 = Mar 31, then remaining 4 days → Apr 4.' },
        { q: 'If today is Wednesday, what day is it after 7 days?', opts: ['Thursday', 'Wednesday', 'Tuesday', 'Monday'], ans: 1, expl: '7 days = 1 week. Same day of the week.' },
        { q: 'What date is 3 days before February 2?', opts: ['January 28', 'January 29', 'January 30', 'January 31'], ans: 2, expl: 'Feb 2 − 2 = Jan 31, then −1 = Jan 30.' },
        { q: 'If Jan 1 is Monday, what day is Jan 8?', opts: ['Sunday', 'Monday', 'Tuesday', 'Saturday'], ans: 1, expl: 'Jan 1 + 7 days = Jan 8. Same day = Monday.' },
        { q: '14 days after a Tuesday is a:', opts: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'], ans: 1, expl: '14 days = 2 weeks. Same day of the week = Tuesday.' },
        { q: 'How many days from March 1 to March 15?', opts: ['14', '15', '16', '13'], ans: 0, expl: 'March 15 − March 1 = 14 days.' },
        { q: 'What is the date 5 days after April 28?', opts: ['May 1', 'May 2', 'May 3', 'May 4'], ans: 2, expl: 'Apr 28 + 2 = Apr 30, then +3 = May 3.' },
        { q: 'If today is Friday, what day was it 3 days ago?', opts: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'], ans: 1, expl: 'Friday − 3 days = Tuesday.' },
        { q: 'How many weeks are in 21 days?', opts: ['2', '3', '4', '5'], ans: 1, expl: '21 ÷ 7 = 3 weeks.' },
    ],
    7: [
        { q: 'Rani left home at 8:15 AM and reached school at 9:00 AM. How long did she take?', opts: ['30 min', '45 min', '15 min', '1 hr'], ans: 1, expl: '9:00 − 8:15 = 45 minutes.' },
        { q: 'A train leaves at 4:30 PM. Ravi reaches the station at 4:45 PM. Did he miss it?', opts: ['Yes, by 15 min', 'No, by 15 min', 'Yes, by 30 min', 'No, he was on time'], ans: 0, expl: '4:45 PM is 15 minutes after 4:30 PM. The train already left!' },
        { q: 'Mom bakes a cake for 1 hour 15 minutes starting at 3:00 PM. When is it done?', opts: ['4:00 PM', '4:15 PM', '3:45 PM', '4:30 PM'], ans: 1, expl: '3:00 PM + 1 hr 15 min = 4:15 PM.' },
        { q: 'A 2-hour movie starts at 6:30 PM. When does it end?', opts: ['8:00 PM', '8:30 PM', '7:30 PM', '9:00 PM'], ans: 1, expl: '6:30 PM + 2 hours = 8:30 PM.' },
        { q: 'Sita sleeps at 9:30 PM and wakes at 6:30 AM. How long did she sleep?', opts: ['8 hours', '9 hours', '10 hours', '7 hours'], ans: 1, expl: '9:30 PM to 6:30 AM = 9 hours.' },
        { q: 'A class is 40 min long. It starts at 10:20 AM. When does it end?', opts: ['10:50 AM', '11:00 AM', '10:40 AM', '11:20 AM'], ans: 1, expl: '10:20 + 40 min = 11:00 AM.' },
        { q: 'Parv\'s birthday is March 15. His friend\'s birthday is 10 days later. When?', opts: ['March 25', 'March 24', 'March 26', 'April 5'], ans: 0, expl: 'March 15 + 10 = March 25.' },
        { q: 'A shop opens at 9:00 AM and closes at 9:00 PM. How long is it open?', opts: ['9 hours', '10 hours', '12 hours', '24 hours'], ans: 2, expl: '9 AM to 9 PM = 12 hours.' },
        { q: 'How many days are left in the year if today is December 25?', opts: ['5', '6', '7', '4'], ans: 1, expl: 'December has 31 days. 31 − 25 = 6 days left.' },
        { q: 'A race started at 11:45 AM and lasted 20 minutes. When did it end?', opts: ['12:00 PM', '12:05 PM', '11:55 AM', '12:15 PM'], ans: 1, expl: '11:45 + 20 min = 12:05 PM.' },
    ],
};

export const ASSESS_QS = {
    1: [
        { q: 'The hour hand is at 2, minute hand at 12. Time?', opts: ['12:02', '2:00', '2:12', '12:10'], ans: 1, expl: 'Hour at 2, minute at 12 = 2:00.' },
        { q: 'What is "quarter to 8"?', opts: ['8:15', '7:45', '8:45', '7:15'], ans: 1, expl: 'Quarter to 8 = 15 min before 8 = 7:45.' },
        { q: 'Minute hand at 4 means ___ minutes.', opts: ['4', '20', '40', '8'], ans: 1, expl: '4 × 5 = 20 minutes.' },
        { q: 'What time is shown if hour hand is at 6 and minute hand at 9?', opts: ['9:30', '6:09', '6:45', '9:06'], ans: 2, expl: 'Hour at 6, minute at 9 = 9×5 = 45. Time = 6:45.' },
        { q: 'How many times does the hour hand go around in a day?', opts: ['1', '2', '12', '24'], ans: 1, expl: 'The hour hand completes 2 full rotations in 24 hours.' },
        { q: '"Half past 11" is:', opts: ['11:15', '11:30', '11:45', '10:30'], ans: 1, expl: 'Half past = 30 min. So 11:30.' },
        { q: 'The minute hand takes ___ to go fully around.', opts: ['12 hours', '1 hour', '24 hours', '30 minutes'], ans: 1, expl: 'The minute hand takes exactly 1 hour (60 minutes) for one full rotation.' },
        { q: 'If the minute hand points to 1, how many minutes?', opts: ['1', '5', '10', '15'], ans: 1, expl: '1 × 5 = 5 minutes past the hour.' },
        { q: 'At 3:00, the hands form what angle?', opts: ['Straight line', 'Right angle', 'No angle', 'Full circle'], ans: 1, expl: 'At 3:00, the hands form a 90° (right) angle.' },
        { q: 'What is "10 minutes to 4"?', opts: ['4:10', '3:50', '3:10', '4:50'], ans: 1, expl: '10 min before 4:00 = 3:50.' },
    ],
    2: [
        { q: '3:30 in the afternoon is:', opts: ['3:30 AM', '3:30 PM', '15:30 AM', '3:30'], ans: 1, expl: 'Afternoon = PM. 3:30 PM.' },
        { q: 'What time period is 11:00 at night?', opts: ['11:00 AM', '11:00 PM', '23:00 AM', '12:00 PM'], ans: 1, expl: 'Night = PM. 11:00 PM.' },
        { q: 'Which comes first in a day: 6 AM or 6 PM?', opts: ['6 PM', 'Both at same time', '6 AM', 'Neither'], ans: 2, expl: '6 AM (morning) comes before 6 PM (evening) in the same day.' },
        { q: 'Midnight is:', opts: ['12:00 PM', '12:00 AM', '0:00 PM', '24:00 AM'], ans: 1, expl: 'Midnight = 12:00 AM.' },
        { q: 'A TV show at "8 in the evening" is:', opts: ['8:00 AM', '8:00 PM', '20:00 AM', '8:00'], ans: 1, expl: 'Evening = PM. 8:00 PM.' },
        { q: 'How many hours from 7 AM to 7 PM?', opts: ['7', '10', '12', '14'], ans: 2, expl: '7 AM to 7 PM = 12 hours.' },
        { q: 'Sunrise is typically in:', opts: ['PM', 'AM', 'Both', 'Neither'], ans: 1, expl: 'Sunrise happens in the morning = AM.' },
        { q: 'After 11:59 PM comes:', opts: ['12:00 PM', '12:00 AM', '1:00 PM', '11:60 PM'], ans: 1, expl: 'After 11:59 PM (almost midnight) comes 12:00 AM (midnight).' },
        { q: '4:00 in the morning is:', opts: ['4:00 PM', '4:00 AM', '16:00', '4:00'], ans: 1, expl: 'Morning = AM. 4:00 AM.' },
        { q: 'A full day has ___ AM hours and ___ PM hours.', opts: ['10 and 14', '12 and 12', '6 and 18', '8 and 16'], ans: 1, expl: 'A full day = 12 AM hours + 12 PM hours = 24 hours.' },
    ],
    3: [
        { q: 'Party from 5:00 PM to 8:00 PM. Duration?', opts: ['2 hr', '3 hr', '4 hr', '5 hr'], ans: 1, expl: '8 − 5 = 3 hours.' },
        { q: 'Meeting 10:30 AM to 12:00 PM. How long?', opts: ['1 hr', '1 hr 30 min', '2 hr', '30 min'], ans: 1, expl: '12:00 − 10:30 = 1 hour 30 minutes.' },
        { q: 'Cooking from 6:15 PM to 7:45 PM. Duration?', opts: ['1 hr 15 min', '1 hr 30 min', '1 hr 45 min', '2 hr'], ans: 1, expl: '7:45 − 6:15 = 1 hour 30 minutes.' },
        { q: 'Bus ride from 7:50 AM to 9:20 AM. How long?', opts: ['1 hr 20 min', '1 hr 30 min', '1 hr 10 min', '2 hr'], ans: 1, expl: '9:20 − 7:50 = 1 hour 30 minutes.' },
        { q: 'If an exam starts at 9:00 AM and lasts 2 hr 15 min, it ends at:', opts: ['11:00 AM', '11:15 AM', '11:30 AM', '12:15 PM'], ans: 1, expl: '9:00 + 2:15 = 11:15 AM.' },
        { q: 'Piano practice 3:45 PM to 4:30 PM. Duration?', opts: ['35 min', '45 min', '50 min', '1 hr'], ans: 1, expl: '4:30 − 3:45 = 45 minutes.' },
        { q: 'Swimming 4:00 PM to 5:15 PM. How long?', opts: ['1 hr', '1 hr 15 min', '1 hr 30 min', '45 min'], ans: 1, expl: '5:15 − 4:00 = 1 hour 15 minutes.' },
        { q: 'If you start at 11:45 AM and spend 30 min, you finish at:', opts: ['12:00 PM', '12:15 PM', '12:30 PM', '11:15 AM'], ans: 1, expl: '11:45 + 30 = 12:15 PM.' },
        { q: 'A nap from 2:00 PM to 3:45 PM. Duration?', opts: ['1 hr', '1 hr 30 min', '1 hr 45 min', '2 hr'], ans: 2, expl: '3:45 − 2:00 = 1 hour 45 minutes.' },
        { q: 'Doctor visit 10:00 AM to 10:20 AM. How long?', opts: ['10 min', '15 min', '20 min', '30 min'], ans: 2, expl: '10:20 − 10:00 = 20 minutes.' },
    ],
    4: [
        { q: 'How many days in September?', opts: ['28', '30', '31', '29'], ans: 1, expl: '"30 days hath September..." — September has 30 days.' },
        { q: 'Which month comes after October?', opts: ['September', 'November', 'December', 'August'], ans: 1, expl: 'October → November.' },
        { q: 'How many Sundays in a 30-day month starting on Sunday?', opts: ['4', '5', '3', '6'], ans: 1, expl: 'Sundays on 1, 8, 15, 22, 29 = 5 Sundays.' },
        { q: 'Which is the 6th month?', opts: ['May', 'June', 'July', 'August'], ans: 1, expl: 'Jan(1), Feb(2), Mar(3), Apr(4), May(5), Jun(6).' },
        { q: 'How many days in August?', opts: ['28', '29', '30', '31'], ans: 3, expl: 'August has 31 days.' },
        { q: 'Total days in April + May + June?', opts: ['89', '90', '91', '92'], ans: 2, expl: 'Apr(30) + May(31) + Jun(30) = 91.' },
        { q: 'How many months have 31 days?', opts: ['5', '6', '7', '8'], ans: 2, expl: 'Jan, Mar, May, Jul, Aug, Oct, Dec = 7 months.' },
        { q: 'Which is the 9th month?', opts: ['August', 'September', 'October', 'November'], ans: 1, expl: 'September is the 9th month.' },
        { q: 'How many weekdays (Mon-Fri) in a week?', opts: ['4', '5', '6', '7'], ans: 1, expl: 'Monday through Friday = 5 weekdays.' },
        { q: 'The first month of the year is:', opts: ['March', 'January', 'April', 'December'], ans: 1, expl: 'January is the 1st month of the year.' },
    ],
    5: [
        { q: 'Is 2032 a leap year?', opts: ['Yes', 'No'], ans: 0, expl: '2032 ÷ 4 = 508. No remainder = Leap year!' },
        { q: 'Is 2025 a leap year?', opts: ['Yes', 'No'], ans: 1, expl: '2025 ÷ 4 = 506.25. Has remainder = Not a leap year.' },
        { q: 'Is 2400 a leap year?', opts: ['Yes', 'No'], ans: 0, expl: '2400 ÷ 400 = 6. Century year divisible by 400 = Leap year!' },
        { q: 'How often do leap years occur?', opts: ['Every 2 years', 'Every 3 years', 'Every 4 years', 'Every 5 years'], ans: 2, expl: 'Leap years come every 4 years.' },
        { q: 'What is special about Feb 29?', opts: ['It is a holiday', 'It only exists in leap years', 'It is always Sunday', 'Nothing'], ans: 1, expl: 'February 29 only exists in leap years!' },
        { q: 'Next leap year after 2024?', opts: ['2025', '2026', '2027', '2028'], ans: 3, expl: '2024 + 4 = 2028.' },
        { q: 'Is 1800 a leap year?', opts: ['Yes', 'No'], ans: 1, expl: '1800 ÷ 400 = 4.5. Century year not divisible by 400 = Not a leap year.' },
        { q: 'In a leap year, total days = ?', opts: ['365', '366', '364', '367'], ans: 1, expl: 'Leap year = 365 + 1 = 366 days.' },
        { q: 'Is 2036 a leap year?', opts: ['Yes', 'No'], ans: 0, expl: '2036 ÷ 4 = 509. No remainder = Leap year!' },
        { q: 'Which rule applies to century years?', opts: ['Divisible by 2', 'Divisible by 4', 'Divisible by 100', 'Divisible by 400'], ans: 3, expl: 'Century years must be divisible by 400 to be leap years.' },
    ],
    6: [
        { q: '15 days after April 20?', opts: ['May 4', 'May 5', 'May 6', 'May 3'], ans: 1, expl: 'Apr 20 + 10 = Apr 30, +5 = May 5.' },
        { q: '8 days before March 3?', opts: ['Feb 22', 'Feb 23', 'Feb 24', 'Feb 21'], ans: 1, expl: 'Mar 3 − 3 = Feb 28, −5 = Feb 23 (non-leap year).' },
        { q: 'If Monday is Jan 1, what day is Jan 15?', opts: ['Sunday', 'Monday', 'Tuesday', 'Saturday'], ans: 1, expl: 'Jan 1 to Jan 15 = 14 days = 2 weeks. Same day = Monday.' },
        { q: '30 days after July 10?', opts: ['Aug 8', 'Aug 9', 'Aug 10', 'Aug 7'], ans: 1, expl: 'Jul 10 + 21 = Jul 31, +9 = Aug 9.' },
        { q: 'How many days from Dec 25 to Jan 1?', opts: ['6', '7', '8', '5'], ans: 1, expl: 'Dec 25 to Dec 31 = 6 days, +1 = Jan 1. Total = 7 days.' },
        { q: 'What day is 21 days after Wednesday?', opts: ['Tuesday', 'Wednesday', 'Thursday', 'Monday'], ans: 1, expl: '21 days = 3 weeks. Same day = Wednesday.' },
        { q: '5 days after Feb 27 (non-leap year)?', opts: ['Mar 3', 'Mar 4', 'Mar 2', 'Mar 5'], ans: 1, expl: 'Feb 27 +1 = Feb 28, +4 = Mar 4.' },
        { q: 'If March 1 is Friday, what day is March 10?', opts: ['Saturday', 'Sunday', 'Monday', 'Tuesday'], ans: 1, expl: 'Mar 1 to Mar 10 = 9 days = 1 week + 2 days. Fri +2 = Sunday.' },
        { q: '50 days after Jan 1 (non-leap)?', opts: ['Feb 19', 'Feb 20', 'Feb 21', 'Feb 18'], ans: 1, expl: 'Jan has 31 days. 31 − 1 = 30 in Jan. 50 − 30 = 20 → Feb 20.' },
        { q: 'How many weeks and days in 25 days?', opts: ['3 weeks 4 days', '3 weeks 3 days', '4 weeks 1 day', '3 weeks 5 days'], ans: 0, expl: '25 ÷ 7 = 3 remainder 4. So 3 weeks and 4 days.' },
    ],
    7: [
        { q: 'Raj wakes at 6:30 AM and takes 45 min to get ready. When is he ready?', opts: ['7:00 AM', '7:15 AM', '7:30 AM', '7:45 AM'], ans: 1, expl: '6:30 + 45 min = 7:15 AM.' },
        { q: 'A flight departs at 11:00 AM and is 3 hr long. Landing time?', opts: ['2:00 PM', '1:00 PM', '3:00 PM', '12:00 PM'], ans: 0, expl: '11:00 AM + 3 hr = 2:00 PM.' },
        { q: 'Meena reads from 4:15 PM to 5:45 PM daily. Weekly reading time?', opts: ['9 hr', '10 hr 30 min', '7 hr', '8 hr 15 min'], ans: 1, expl: 'Daily = 1 hr 30 min. Weekly = 1.5 × 7 = 10 hr 30 min.' },
        { q: 'A shop is open 10 AM to 8 PM. Hours open?', opts: ['8', '10', '12', '6'], ans: 1, expl: '10 AM to 8 PM = 10 hours.' },
        { q: 'Anil\'s birthday is May 10. His exam is 15 days before. Exam date?', opts: ['April 24', 'April 25', 'April 26', 'April 23'], ans: 1, expl: 'May 10 − 10 = Apr 30, −5 = Apr 25.' },
        { q: 'A TV show starts at 7:30 PM and is 1 hr 15 min. End time?', opts: ['8:30 PM', '8:45 PM', '9:00 PM', '8:15 PM'], ans: 1, expl: '7:30 + 1:15 = 8:45 PM.' },
        { q: 'A school year has 200 working days. How many weeks and days?', opts: ['28 weeks 4 days', '28 weeks 2 days', '29 weeks 1 day', '30 weeks'], ans: 0, expl: '200 ÷ 7 = 28 remainder 4. So 28 weeks 4 days.' },
        { q: 'Lunch break is 12:30 PM to 1:00 PM. Total weekly break time (5 days)?', opts: ['2 hr', '2 hr 30 min', '3 hr', '1 hr 30 min'], ans: 1, expl: 'Daily = 30 min. 5 days = 150 min = 2 hr 30 min.' },
        { q: 'Train A leaves at 9:00 AM, Train B at 9:45 AM. Time gap?', opts: ['30 min', '45 min', '1 hr', '15 min'], ans: 1, expl: '9:45 − 9:00 = 45 minutes.' },
        { q: 'If Jan 26 is Republic Day and 60 days later is?', opts: ['Mar 26', 'Mar 27', 'Mar 28', 'Mar 25'], ans: 1, expl: 'Jan has 31 days. 31−26=5 left. 60−5=55. Feb has 28. 55−28=27. Mar 27.' },
    ],
};
