export const trigIntroData = {
  prerequisites: [
    { title: 'Basic Geometry', desc: 'Understanding of angles, triangles, and the Pythagorean theorem.', icon: '📐' },
    { title: 'Sets & Real Numbers', desc: 'Familiarity with the real number line, intervals, and set notation.', icon: '🔢' },
    { title: 'Relations & Functions', desc: 'Understanding of functions as input-output mappings and their domains/ranges.', icon: 'f(x)' },
  ],
  cards5W1H: [
    {
      q: "WHAT",
      label: "are Trigonometric Functions?",
      icon: "🔍",
      gradFrom: "#0891b2",
      gradTo: "#06b6d4",
      shadow: "rgba(6,182,212,0.35)",
      content: `<strong>Trigonometry</strong> (from Greek: <em>trigonon</em> = triangle, <em>metron</em> = measure) is the study of relationships between angles and sides of triangles. The six trigonometric functions — $\\sin\\theta$, $\\cos\\theta$, $\\tan\\theta$, $\\cosec\\theta$, $\\sec\\theta$, and $\\cot\\theta$ — extend the idea of ratios in a right triangle to any angle on the number line. Using the <strong>unit circle</strong> (a circle of radius 1), we define $\\sin\\theta$ as the y-coordinate and $\\cos\\theta$ as the x-coordinate of the point where the terminal ray meets the circle. This gives trig functions meaning for ALL angles, not just those in triangles!`,
      fact: 'The word "trigonometry" first appeared in a book by Bartholomaeus Pitiscus in 1595, but the ideas are over 2000 years older!',
    },
    {
      q: "WHO",
      label: "uses Trigonometric Functions?",
      icon: "👥",
      gradFrom: "#059669",
      gradTo: "#10b981",
      shadow: "rgba(16,185,129,0.35)",
      content: `<strong>Everyone who works with waves, cycles, or angles!</strong> Electrical engineers use sine waves to model alternating current. Architects use trig to calculate roof angles and structural forces. Navigators use it for GPS and ship bearing calculations. Physicists use it to describe oscillations, pendulums, and quantum wavefunctions. Even musicians — Fourier analysis shows that any sound wave is a sum of sine waves! Astronomers have used trig for millennia to measure distances to stars using parallax triangulation.`,
      fact: "Ancient Indian mathematician Aryabhata (476 AD) created the first table of sine values — centuries before European mathematicians even knew these functions existed!",
    },
    {
      q: "WHEN",
      label: "did this concept begin?",
      icon: "📅",
      gradFrom: "#b45309",
      gradTo: "#f59e0b",
      shadow: "rgba(245,158,11,0.35)",
      content: `Trigonometry has roots stretching back to <strong>ancient Babylon (1800 BCE)</strong> and Egypt, where surveyors used angle ratios for land measurement. Greek astronomer <strong>Hipparchus (150 BCE)</strong> is called the "father of trigonometry" for building the first chord tables. Indian mathematicians like <strong>Aryabhata</strong> formalized the sine function around 500 CE. <strong>Al-Battani (920 CE)</strong> introduced the modern sine and cosine. <strong>Euler (1748)</strong> established the unit-circle definitions we use today, linking trig to complex numbers through his famous formula $e^{i\\theta} = \\cos\\theta + i\\sin\\theta$.`,
      fact: "Euler's identity $e^{i\\pi} + 1 = 0$ — called 'the most beautiful equation in mathematics' — comes directly from trigonometry!",
    },
    {
      q: "WHERE",
      label: "do we see them?",
      icon: "🌍",
      gradFrom: "#be185d",
      gradTo: "#ec4899",
      shadow: "rgba(236,72,153,0.35)",
      content: `Trigonometric functions are everywhere once you start looking! <strong>Sound waves</strong> — every audio signal is modelled by sine waves. <strong>Tides</strong> — rise and fall following sinusoidal patterns. <strong>Electricity</strong> — household AC power is $V = 220\\sin(100\\pi t)$ volts. <strong>MRI machines</strong> — use Fourier transforms (sums of sines) to reconstruct body images. <strong>Architecture</strong> — the Cairo Opera House dome and Sydney Opera House were designed using trigonometric curves. Your phone's screen works because of sin waves in LCD technology!`,
      fact: "The entire field of signal processing — from Wi-Fi to Bluetooth to 5G — is built on decomposing signals into sine and cosine components (Fourier Series)!",
    },
    {
      q: "WHY",
      label: "should I learn this?",
      icon: "🚀",
      gradFrom: "#7c3aed",
      gradTo: "#a855f7",
      shadow: "rgba(168,85,247,0.35)",
      content: `Trigonometric functions are the <strong>language of oscillation and waves</strong>. Without them, you cannot study: Physics (simple harmonic motion, waves, optics), Engineering (AC circuits, signal processing, structural analysis), Computer Graphics (rotation matrices, animation), Calculus (trig functions have beautiful derivatives: $\\frac{d}{dx}\\sin x = \\cos x$), or Statistics (circular statistics). They're also directly tested in JEE Mains, JEE Advanced, NEET, and CET — typically 2–3 questions in every competitive exam!`,
      fact: "In JEE Advanced 2023, trigonometric equations and identities appeared in 3 out of 18 maths questions — making this chapter one of the highest-yield in the entire curriculum!",
    },
    {
      q: "HOW",
      label: "do they work?",
      icon: "🎯",
      gradFrom: "#0369a1",
      gradTo: "#3b82f6",
      shadow: "rgba(59,130,246,0.35)",
      content: `Start with an <strong>angle</strong> $\\theta$ measured in degrees or radians (where $\\pi \\text{ rad} = 180°$). Place the angle in <strong>standard position</strong> on the unit circle. The terminal ray meets the circle at point $P = (\\cos\\theta, \\sin\\theta)$. From here: $\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}$, and the three reciprocals $\\cosec$, $\\sec$, $\\cot$ follow. Then use the <strong>ASTC rule</strong> to track signs in each quadrant. Master the <strong>allied angle formulas</strong> (like $\\sin(\\pi - \\theta) = \\sin\\theta$) and the <strong>sum-difference formulas</strong> — and you can evaluate ANY trig expression!`,
      fact: "The Pythagorean identity $\\sin^2\\theta + \\cos^2\\theta = 1$ is literally just the Pythagorean theorem applied to the unit circle! One theorem, infinite applications.",
    }
  ]
};
